"use client";
import Link from "next/link";
import type { getPricingIntelligence,getPricingIntelligenceOptions } from "@/lib/pricingIntelligence/service";
import type { PricingIntelligenceFilters } from "@/lib/pricingIntelligence/filters";
import { pricingIntelligenceQuery } from "@/lib/pricingIntelligence/filters";
type Data=Awaited<ReturnType<typeof getPricingIntelligence>>;type Options=Awaited<ReturnType<typeof getPricingIntelligenceOptions>>;
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const number=(value:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:1}).format(value);
const pct=(value:number)=>`${number(value)}%`;

export default function PricingIntelligenceDashboard({data,options,filters}:{data:Data;options:Options;filters:PricingIntelligenceFilters}){
  const query=pricingIntelligenceQuery(filters),pageSize=25,start=(filters.page-1)*pageSize,items=data.items.slice(start,start+pageSize);
  return <main className="mx-auto max-w-[1500px] p-4 sm:p-8 print:max-w-none print:p-0">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Historical company data</p><h1 className="text-3xl font-bold">Pricing Intelligence</h1><p className="text-slate-600 dark:text-slate-300">{filters.from.toLocaleDateString()} – {filters.to.toLocaleDateString()}</p></div><div className="flex flex-wrap gap-2 print:hidden"><Link className="min-h-11 rounded-xl border px-4 py-3 font-semibold" href={`/api/analytics/pricing/export?${query}&format=csv`}>Export CSV</Link><Link className="min-h-11 rounded-xl border px-4 py-3 font-semibold" href={`/api/analytics/pricing/export?${query}&format=pdf`}>Export PDF</Link><button className="min-h-11 rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white" onClick={()=>window.print()}>Print report</button></div></header>
    <Filters options={options} filters={filters}/>
    {data.meta.truncated&&<p className="mt-4 rounded-xl bg-amber-100 p-3 text-amber-950">The 5,000-estimate safety cap was reached. Narrow the filters for exact results.</p>}
    <Section title="Summary"><Cards rows={[
      ["Average Estimate",money(data.summary.averageEstimate)],["Average Approved Estimate",money(data.summary.averageApprovedEstimate)],["Average Invoice",money(data.summary.averageInvoice)],["Average Job Value",money(data.summary.averageJobValue)],["Average Discount",money(data.summary.averageDiscount)],["Acceptance Rate",pct(data.summary.acceptanceRate)],["Revenue This Week",money(data.summary.revenueThisWeek)],["Revenue This Month",money(data.summary.revenueThisMonth)],["Revenue This Year",money(data.summary.revenueThisYear)],["Average Time to Approval",`${number(data.summary.averageTimeToApprovalDays)} days`],["Average Days Until Payment",`${number(data.summary.averageDaysUntilPayment)} days`],
    ]}/></Section>
    <Section title="Trends"><div className="grid gap-4 lg:grid-cols-3"><Bars title="Revenue trend" rows={data.charts.revenueTrend} moneyValues/><Bars title="Estimate trend" rows={data.charts.estimateTrend}/><Bars title="Acceptance trend" rows={data.charts.acceptanceTrend} percentValues/></div></Section>
    <Section title="Item Analytics"><Table headers={["Item","Category","Quoted","Accepted","Revenue","Avg. price","Avg. discount","Avg. labor","Avg. disposal","Avg. profit"]} rows={items.map(row=>[row.name,row.category,row.quoted,row.accepted,money(row.revenue),money(row.averageSellingPrice),money(row.averageDiscount),number(row.averageLabor),money(row.averageDisposalCost),money(row.averageProfitEstimate)])}/><Pagination page={filters.page} total={data.items.length} query={query}/><div className="grid gap-4 lg:grid-cols-3"><Bars title="Top Items" rows={data.charts.topItems} moneyValues/><Bars title="Most Frequently Removed" rows={data.items.slice().sort((a,b)=>b.accepted-a.accepted).slice(0,10).map(row=>({label:row.name,value:row.accepted}))}/><Bars title="Revenue by Category" rows={data.charts.revenueByCategory} moneyValues/></div></Section>
    <Section title="Pricing Rule Analytics"><Table headers={["Rule","Triggered","Average Value","Revenue","Removed","Edited","Common Trigger"]} rows={data.rules.map(row=>[row.name,row.triggered,money(row.averageValue),money(row.revenue),row.removed,row.edited,row.mostCommonTrigger])}/><Bars title="Top Pricing Rules" rows={data.charts.topRules} moneyValues/></Section>
    <Section title="Pricing Profile Analytics"><Table headers={["Profile","Average Estimate","Acceptance","Revenue","Average Job Size"]} rows={data.profiles.map(row=>[row.name,money(row.averageEstimate),pct(row.acceptanceRate),money(row.revenue),number(row.averageJobSize)])}/><Bars title="Revenue by Profile" rows={data.charts.revenueByProfile} moneyValues/></Section>
    <Section title="Service Area Analytics"><Table headers={["City / ZIP","Revenue","Jobs","Average Ticket","Average Drive Distance"]} rows={data.serviceAreas.map(row=>[row.name,money(row.revenue),row.jobs,money(row.averageTicket),row.averageDriveDistance===null?"Not available":`${number(row.averageDriveDistance)} mi`])}/></Section>
    <Section title="Customer Analytics"><Cards rows={[["Repeat Customers",data.customers.repeatCustomers],["Average Lifetime Value",money(data.customers.averageLifetimeValue)]]}/><Table headers={["Customer","Lifetime Value","Jobs","Average Spend"]} rows={data.customers.highestValue.map(row=>[row.name,money(row.lifetimeValue),row.jobs,money(row.averageSpend)])}/></Section>
    <Section title="Crew Analytics"><Table headers={["Crew","Jobs Completed","Revenue","Average Job","Completion Time","Revenue / Day"]} rows={data.crews.map(row=>[row.name,row.jobsCompleted,money(row.revenueProduced),money(row.averageJobValue),`${number(row.averageCompletionTimeHours)} hr`,money(row.averageRevenuePerDay)])}/></Section>
    <Section title="Pricing Health"><Cards rows={[["Average Discount",money(data.health.averageDiscount)],["Manual Overrides",data.health.manualOverrides],["Rule Overrides",data.health.ruleOverrides],["Missing Disposal Fees",data.health.missingDisposalFees]]}/><div className="grid gap-4 lg:grid-cols-2"><Table headers={["Frequently Disabled Rule","Removal Rate"]} rows={data.health.frequentlyDisabledRules.map(row=>[row.name,pct(row.removalRate)])}/><Table headers={["Potentially Underpriced Category","Revenue"]} rows={data.health.underpricedCategories.map(row=>[row.label,money(row.value)])}/></div></Section>
    <Section title="Rule-Based Insights"><ul className="grid gap-3 md:grid-cols-2">{data.insights.map(insight=><li className="rounded-xl border bg-blue-50 p-4 text-blue-950 dark:bg-blue-950/30 dark:text-blue-100" key={insight}>{insight}</li>)}{!data.insights.length&&<li className="rounded-xl border border-dashed p-5 text-slate-500">More historical data is needed to generate insights.</li>}</ul></Section>
  </main>;
}
function Filters({options,filters}:{options:Options;filters:PricingIntelligenceFilters}){return <form className="mt-6 grid gap-3 rounded-2xl border bg-[var(--surface)] p-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7 print:hidden"><input aria-label="From date" className="min-h-11 rounded-xl border px-3" name="from" type="date" defaultValue={filters.from.toISOString().slice(0,10)}/><input aria-label="To date" className="min-h-11 rounded-xl border px-3" name="to" type="date" defaultValue={filters.to.toISOString().slice(0,10)}/><Select name="profile" label="All profiles" value={filters.pricingProfileId} rows={options.profiles.map(row=>({id:row.id,label:row.name}))}/><Select name="employee" label="All employees" value={filters.employeeId} rows={options.employees.map(row=>({id:row.id,label:[row.firstName,row.lastName].filter(Boolean).join(" ")||row.email}))}/><Select name="serviceArea" label="All service areas" value={filters.serviceArea} rows={options.serviceAreas.map(value=>({id:value,label:value}))}/><Select name="category" label="All categories" value={filters.category} rows={options.categories.map(value=>({id:value,label:value}))}/><Select name="crew" label="All crews" value={filters.crewId} rows={options.crews.map(row=>({id:row.id,label:row.name}))}/><button className="min-h-11 rounded-xl bg-blue-700 px-4 font-semibold text-white">Apply</button><Link href="/analytics/pricing" className="flex min-h-11 items-center justify-center rounded-xl border font-semibold">Reset</Link></form>}
function Select({name,label,value,rows}:{name:string;label:string;value?:string;rows:{id:string;label:string}[]}){return <select aria-label={label} name={name} defaultValue={value??""} className="min-h-11 rounded-xl border px-3"><option value="">{label}</option>{rows.map(row=><option key={row.id} value={row.id}>{row.label}</option>)}</select>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-8 break-inside-avoid"><h2 className="text-xl font-bold">{title}</h2><div className="mt-3 space-y-4">{children}</div></section>}
function Cards({rows}:{rows:[string,string|number][]}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{rows.map(([label,value])=><article className="rounded-xl border bg-[var(--surface)] p-4" key={label}><p className="text-xs uppercase text-slate-500 dark:text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></article>)}</div>}
function Bars({title,rows,moneyValues,percentValues}:{title:string;rows:{label:string;value:number}[];moneyValues?:boolean;percentValues?:boolean}){const max=Math.max(1,...rows.map(row=>row.value));return <figure aria-label={title} className="rounded-xl border bg-[var(--surface)] p-4"><figcaption className="mb-3 font-semibold">{title}</figcaption>{rows.slice(-12).map(row=><div className="mb-2 grid grid-cols-[minmax(80px,140px)_1fr_80px] items-center gap-2" key={row.label}><span className="truncate text-sm">{row.label}</span><span className="h-2 rounded bg-slate-200 dark:bg-slate-700"><span className="block h-2 rounded bg-blue-600" style={{width:`${Math.max(2,row.value/max*100)}%`}}/></span><span className="text-right text-xs">{moneyValues?money(row.value):percentValues?pct(row.value):number(row.value)}</span></div>)}{!rows.length&&<p className="text-sm text-slate-500">No data for this period.</p>}</figure>}
function Table({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="overflow-x-auto rounded-xl border bg-[var(--surface)]"><table className="w-full min-w-[700px] text-sm"><thead><tr>{headers.map(header=><th scope="col" className="p-3 text-left" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr className="border-t" key={index}>{row.map((value,cell)=><td className="p-3" key={cell}>{value}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-4 text-slate-500">No data for this period.</p>}</div>}
function Pagination({page,total,query}:{page:number;total:number;query:string}){const pages=Math.max(1,Math.ceil(total/25)),base=new URLSearchParams(query),links:Array<[string,number]>=[["Previous",page-1],["Next",page+1]];return <div className="flex items-center justify-between print:hidden"><span className="text-sm text-slate-500">{total} items</span><div className="flex gap-2">{links.map(([label,target])=>{base.set("page",String(target));const disabled=target<1||target>pages;return disabled?<span className="rounded-lg border px-4 py-2 opacity-40" key={label}>{label}</span>:<Link className="rounded-lg border px-4 py-2" key={label} href={`?${base}`}>{label}</Link>})}</div></div>}
