import { notFound } from "next/navigation";
import { requirePlatformAdminPage } from "@/lib/admin/platformPageAuth";
import { getPlatformCompanySummary } from "@/lib/admin/platformAnalytics";
import { changeClassificationAction, deleteTestCompanyAction, suspensionAction, trialAction } from "@/app/actions/platformAdmin/companies";
import PlatformAdminShell, { MetricCard, Panel, tableClass } from "@/features/platformAdmin/PlatformAdminShell";
const field="min-h-11 rounded-xl border border-white/15 bg-slate-900 px-3", button="min-h-11 rounded-xl bg-orange-500 px-4 font-bold text-slate-950 disabled:opacity-50";
export default async function Page({params}:{params:Promise<{id:string}>}) { await requirePlatformAdminPage("platform_admin.company_summary_viewed"); const {id}=await params,c=await getPlatformCompanySummary(id); if(!c)notFound(); const paid=Boolean(c.subscription?.stripeSubscriptionId&&c.subscription.lastSuccessfulPaymentAt&&["Active","PastDue","Paused"].includes(c.subscription.status)),d=c.deletionPreview;
return <PlatformAdminShell active="/platform-admin/companies"><h2 className="text-2xl font-bold">{c.name}</h2><p className="mt-2 text-slate-400">Owner-only company management. Private customer and payment details are not exposed.</p>
<section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Classification" value={c.classification}/><MetricCard label="Effective plan" value={c.effectivePlan}/><MetricCard label="Members" value={c._count.users}/><MetricCard label="Estimates" value={c._count.estimates}/></section>
<div className="grid gap-5 lg:grid-cols-2"><Panel title="Overview"><p>Created: {c.createdAt.toLocaleString()}</p><p>Status: {c.active?"Active":"Suspended"}</p><p>Last activity: {c.lastActivity?.toLocaleString()??"None"}</p><p>Trial: {c.subscription?.trialStatus??"None"} · {c.subscription?.trialEnd?.toLocaleString()??"no expiration"}</p></Panel><Panel title="Subscription"><p>Effective plan: {c.effectivePlan}</p><p>Stripe customer present: {c.subscription?.stripeCustomerId?"Yes":"No"}</p><p>Status: {c.subscription?.status??"Free fallback"}</p><p>Interval: {c.subscription?.billingInterval??"—"} · Period end: {c.subscription?.currentPeriodEnd?.toLocaleDateString()??"—"}</p><p>Cancellation scheduled: {c.subscription?.cancelAtPeriodEnd?"Yes":"No"}</p>{paid&&<p className="mt-3 text-amber-200">Paid Stripe billing is authoritative; trial controls are disabled.</p>}</Panel></div>
<div className="grid gap-5 lg:grid-cols-2"><Panel title="Classification"><form action={changeClassificationAction.bind(null,id)} className="grid gap-3"><select name="classification" defaultValue={c.classification} className={field}>{["CUSTOMER","TEST","INTERNAL"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Classification reason" name="reason" required minLength={3} placeholder="Classification reason" className={field}/><button className={button}>Save classification</button></form></Panel><Panel title="Platform status"><p>{c.active?"Operational access is enabled.":`Suspended ${c.suspendedAt?.toLocaleString()??""}.`}</p><form action={suspensionAction.bind(null,id,c.active)} className="mt-3 grid gap-3"><input aria-label="Account status reason" name="reason" required minLength={3} placeholder="Account status reason" className={field}/><button className={c.active?"min-h-11 rounded-xl bg-red-600 px-4 font-bold":"min-h-11 rounded-xl bg-emerald-500 px-4 font-bold text-slate-950"}>{c.active?"Suspend company":"Reactivate company"}</button></form></Panel></div>
<div className="grid gap-5 lg:grid-cols-2"><Panel title="Trial management"><form action={trialAction.bind(null,id,c.subscription?.trialStatus==="Active"?"extend":"grant")} className="grid gap-3"><select name="days" className={field} disabled={paid}><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select><input name="expiration" type="date" aria-label="Custom expiration" className={field} disabled={paid}/><input aria-label="Trial reason" name="reason" required minLength={3} placeholder="Trial reason" className={field} disabled={paid}/><button disabled={paid} className={button}>{c.subscription?.trialStatus==="Active"?"Extend Professional trial":"Grant Professional trial"}</button></form>{c.subscription?.trialStatus==="Active"&&!paid&&<form action={trialAction.bind(null,id,"end")} className="mt-3 grid gap-3"><input name="reason" required minLength={3} placeholder="Reason to end trial" className={field}/><button className="min-h-11 rounded-xl border border-red-400 px-4 text-red-200">End trial</button></form>}</Panel><Panel title="Stripe Connect status"><p>Status: {c.stripeConnectStatus.replaceAll("_"," ")}</p><p>Charges enabled: {c.stripeChargesEnabled?"Yes":"No"}</p><p>Payouts enabled: {c.stripePayoutsEnabled?"Yes":"No"}</p><p>Details submitted: {c.stripeDetailsSubmitted?"Yes":"No"}</p></Panel></div>
<Panel title="Members"><div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>Name</th><th>Email</th><th>Role</th></tr></thead><tbody>{c.memberships.map((m,i)=><tr key={i}><td>{[m.user.firstName,m.user.lastName].filter(Boolean).join(" ")||"—"}</td><td>{m.user.email}</td><td>{m.role}</td></tr>)}</tbody></table></div></Panel>
<Panel title="Audit history"><div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>Time</th><th>Action</th><th>Entity</th></tr></thead><tbody>{c.recent.map((e,i)=><tr key={i}><td>{e.createdAt.toLocaleString()}</td><td>{e.eventType}</td><td>{e.entityType??"—"}</td></tr>)}</tbody></table></div></Panel>
<section className="mt-5 rounded-2xl border border-red-500/50 bg-red-950/30 p-5"><h3 className="text-lg font-bold text-red-200">Danger Zone</h3>{c.classification!=="TEST"?<p className="mt-2">Permanent deletion is unavailable. Only explicitly classified TEST companies may be deleted.</p>:<><p className="mt-2">{d?`${d._count.memberships} members · ${d._count.customers} customers · ${d._count.estimates} estimates · ${d._count.invoices} invoices · ${d._count.payments} payments · subscription ${d.subscription?.status??"none"} · Connect ${d.stripeConnectStatus}`:"Preview unavailable"}</p>{d&&!d.safeToDelete?<p className="mt-3 font-semibold text-amber-200">Deletion blocked by financial-retention evidence. Suspend this company instead.</p>:<form action={deleteTestCompanyAction.bind(null,id)} className="mt-4 grid gap-3"><label>Type <b>{c.name}</b> to confirm<input name="confirmation" required className={`${field} mt-1 w-full`}/></label><input name="reason" required minLength={3} placeholder="Required deletion reason" className={field}/><button className="min-h-11 rounded-xl bg-red-600 px-4 font-bold">Delete Test Company</button></form>}</>}</section></PlatformAdminShell>}
