"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {deleteEstimateAction} from "@/app/actions/estimates/deleteEstimate";
import {listEstimatesAction} from "@/app/actions/estimates/listEstimates";
import {canDeleteEstimate,isEstimateEditable,estimateStatusBadges} from "@/lib/estimates/lifecyclePolicy";
const statuses=["All","Draft","Sent","Viewed","Approved","Scheduled","InProgress","Completed","Invoiced","Paid","Declined","Expired","Canceled"] as const;
type Status=typeof statuses[number];
export default function EstimateManagement(){
 const[status,setStatus]=useState<Status>("All"),[search,setSearch]=useState(""),[page,setPage]=useState(1),[result,setResult]=useState<Awaited<ReturnType<typeof listEstimatesAction>>|null>(null),[error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;void listEstimatesAction({status:status==="All"?undefined:status,search,page}).then(r=>{if(active)setResult(r)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load estimates.")});return()=>{active=false}},[status,search,page]);
 async function remove(id:string){if(!confirm("Delete this estimate? This cannot be undone."))return;try{await deleteEstimateAction(id);setResult(r=>r?{...r,estimates:r.estimates.filter(e=>e.id!==id),total:r.total-1}:r)}catch(e){setError(e instanceof Error?e.message:"Unable to delete estimate.")}}
 const pages=result?Math.max(1,Math.ceil(result.total/result.pageSize)):1;
 return <div className="mx-auto max-w-6xl p-6 sm:p-10"><div className="flex justify-between"><div><h1 className="text-3xl font-bold">Estimates</h1><p className="text-slate-600">Create, resume, and track customer estimates.</p></div><Link href="/estimates?new=1" className="rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white">New Estimate</Link></div><div className="mt-8 flex flex-wrap gap-2">{statuses.map(s=><button key={s} onClick={()=>{setStatus(s);setPage(1)}} className={`rounded-full px-4 py-2 text-sm ${status===s?"bg-slate-900 text-white":"bg-slate-200"}`}>{s==="InProgress"?"In Progress":s}</button>)}</div><input className="mt-6 w-full rounded-xl border p-3" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, address, or estimate ID"/>{error&&<p className="mt-3 text-red-600">{error}</p>}<div className="mt-6 space-y-3">{result?.estimates.map(e=>{const badge=estimateStatusBadges[e.status],editable=isEstimateEditable(e);return <div key={e.id} className="flex flex-wrap items-center gap-4 rounded-2xl border bg-white p-5"><div className="flex-1"><strong>{e.customer.firstName} {e.customer.lastName}</strong><p className="text-sm text-slate-600">{e.property.address}, {e.property.city}</p></div><strong>${e.pricingTotal.toFixed(2)}</strong><span className={`rounded-full px-3 py-1 text-sm ${badge.className}`}>{badge.label}</span><Link className="rounded-lg bg-blue-700 px-4 py-2 text-white" href={editable?`/estimates?estimateId=${e.id}`:`/estimates/${e.id}`}>{editable?"Edit":"View"}</Link>{canDeleteEstimate(e)&&<button className="rounded-lg border border-red-300 px-4 py-2 text-red-700" onClick={()=>void remove(e.id)}>Delete</button>}</div>})}</div><div className="mt-6 flex justify-between"><span>{result?.total??0} estimates</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></div>;
}
