import AppLayout from "@/components/layout/AppLayout";
import Link from "next/link";
import { requireAdminTenant } from "@/lib/auth/tenant";
import { getOnboarding, onboardingSections } from "@/lib/onboarding/service";
import { addEquipmentAction, addServiceAreaAction, addTeamMemberAction, createDemoDataAction, deleteDemoDataAction, finishOnboardingAction, saveBrandingAction, saveCommunicationAction, savePreferencesAction, savePricingAction, saveProfileAction, skipOnboardingAction } from "@/app/actions/onboarding/onboarding";
import { PRICING_MARKETS } from "@/lib/itemLibrary/defaultItems";

export default async function OnboardingPage(){const{companyId}=await requireAdminTenant();const data=await getOnboarding(companyId);const complete=new Set(data.state.completedSections);return <AppLayout><main className="mx-auto max-w-5xl p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold text-blue-700">First-run setup · {data.progress}% complete</p><h1 className="text-3xl font-bold">Make this workspace yours</h1><p className="mt-2 text-slate-600">Complete the essentials, then send your first estimate. Every section is saved independently.</p></div><form action={skipOnboardingAction}><button className="rounded border px-4 py-2">Skip for now</button></form></div><div className="mt-6 h-3 overflow-hidden rounded bg-slate-200"><div className="h-full bg-blue-600" style={{width:`${data.progress}%`}}/></div><div className="mt-3 flex flex-wrap gap-2">{onboardingSections.map(section=><span key={section} className={`rounded-full px-3 py-1 text-xs ${complete.has(section)?"bg-green-100 text-green-800":"bg-slate-100"}`}>{complete.has(section)?"✓ ":""}{section}</span>)}</div>
<Section title="1. Company profile" done={complete.has("profile")}><Form action={saveProfileAction}><Input name="name" label="Company name" value={data.company.name}/><Input name="phone" label="Phone" value={data.company.phone}/><Input name="email" label="Email" type="email" value={data.company.email}/><Input name="website" label="Website" value={data.company.website}/><Input name="address" label="Business address" value={data.company.addressLine1}/><Input name="city" label="City" value={data.company.city}/><Input name="state" label="State" value={data.company.state}/><Input name="postalCode" label="ZIP" value={data.company.postalCode}/><Input name="serviceRadius" label="Service radius (miles)" type="number" value={data.settings.serviceRadiusMiles}/><Input name="timezone" label="Time zone" value={data.company.timezone}/><label className="grid gap-1 text-sm">Logo<input name="logo" type="file" accept="image/png,image/jpeg,image/webp"/></label><Save/></Form></Section>
<Section title="2. Branding" done={complete.has("branding")}><Form action={saveBrandingAction}><Input name="primary" label="Primary color" type="color" value={data.company.primaryColor??"#2563eb"}/><Input name="secondary" label="Secondary color" type="color" value={data.company.secondaryColor??"#0f172a"}/><Check name="pdf" label="Use branding on PDFs" checked={data.settings.pdfBrandingEnabled}/><Check name="portal" label="Use branding in customer portal" checked={data.settings.portalBrandingEnabled}/><Save/></Form></Section>
<Section title="3. Pricing setup" done={complete.has("pricing")}><p className="mb-4 text-sm text-slate-600">Tune the JunkQuote Standard Library once for your market. This multiplier will not change future custom pricing.</p>{complete.has("pricing")?<p className="rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-900">Your first-run library is initialized. Future changes are made explicitly from Item Library settings.</p>:<Form action={savePricingAction}><Input name="region" label="Business region" value={data.settings.pricingRegion??data.company.state??""}/><label className="grid gap-1 text-sm">Market pricing<select name="market" defaultValue={data.settings.pricingMarket??"standard"} className="rounded border p-2">{Object.entries(PRICING_MARKETS).map(([value,market])=><option value={value} key={value}>{market.label} ({market.multiplier.toFixed(2)}×)</option>)}</select></label><Input name="minimum" label="Minimum charge" type="number" value={data.company.defaultMinimumCharge}/><Input name="dump" label="Average dump fees" type="number" value={data.settings.defaultDumpFee}/><Input name="crew" label="Average crew size" type="number" value="2"/><Save label="Apply Standard Library"/></Form>}</Section>
<Section title="4. Service area & travel zones" done={complete.has("service-area")}><Form action={addServiceAreaAction}><label className="grid gap-1 text-sm">Type<select name="kind" className="rounded border p-2"><option value="zip">ZIP code</option><option value="city">City</option></select></label><Input name="value" label="ZIP or city"/><Input name="zone" label="Travel zone"/><Input name="charge" label="Distance charge" type="number" value="0"/><Save label="Add area"/></Form><List values={data.serviceAreas.map(item=>`${item.kind}: ${item.value} · ${item.travelZone??"Base zone"} · $${item.distanceCharge}`)}/></Section>
<Section title="5. Team setup" done={complete.has("team")}><Form action={addTeamMemberAction}><Input name="firstName" label="First name"/><Input name="lastName" label="Last name"/><Input name="email" label="Invite email" type="email"/><label className="grid gap-1 text-sm">Role & permissions<select name="role" className="rounded border p-2"><option>Manager</option><option>Estimator</option><option>CrewLead</option><option>CrewMember</option><option>Office</option></select></label><Save label="Invite team member"/></Form><List values={data.employees.map(item=>`${item.firstName} ${item.lastName} · ${item.role} · ${item.invitationStatus}`)}/></Section>
<Section title="6. Equipment & crews" done={complete.has("equipment")}><Form action={addEquipmentAction}><label className="grid gap-1 text-sm">Type<select name="type" className="rounded border p-2"><option>Truck</option><option>Trailer</option><option>Equipment</option></select></label><Input name="name" label="Equipment name"/><Input name="crew" label="Crew name (optional)"/><Save label="Add equipment"/></Form><List values={[...data.assets.map(item=>`${item.type}: ${item.name}`),...data.crews.map(item=>`Crew: ${item.name}`)]}/></Section>
<Section title="7. Business preferences" done={complete.has("preferences")}><Form action={savePreferencesAction}><Input name="businessHours" label="Business hours" value={data.settings.businessHours}/><Input name="estimateExpiration" label="Estimate expiration (days)" type="number" value={data.company.defaultEstimateExpirationDays}/><Input name="approvalExpiration" label="Approval expiration (days)" type="number" value={data.settings.approvalExpirationDays}/><Input name="invoiceTerms" label="Invoice terms (days)" type="number" value={data.company.defaultPaymentTermsDays}/><Input name="currency" label="Currency" value={data.company.currencyCode}/><Input name="dateFormat" label="Date format" value={data.settings.dateFormat}/><Save/></Form></Section>
<Section title="8. Communication" done={complete.has("communication")}><Form action={saveCommunicationAction}><Input name="sender" label="Sender name" value={data.settings.communicationSenderName}/><Input name="replyTo" label="Reply-to address" type="email" value={data.settings.communicationReplyTo}/><Input name="estimateEmail" label="Estimate email message" value={data.settings.estimateEmailTemplate}/><Input name="approvalEmail" label="Approval email message" value={data.settings.approvalEmailTemplate}/><Input name="invoiceEmail" label="Invoice email message" value={data.settings.invoiceEmailTemplate}/><Save/></Form></Section>
<Section title="9. Demo walkthrough" done={complete.has("demo")}><p className="text-sm text-slate-600">Create a linked sample customer, approved estimate, completed job, and draft invoice.</p><div className="mt-3 flex gap-2">{data.state.demoDataIds?<><Link href="/customers" className="rounded bg-blue-700 px-4 py-2 text-white">Explore demo</Link><form action={deleteDemoDataAction}><button className="rounded border px-4 py-2">Delete demo data</button></form></>:<form action={createDemoDataAction}><button className="rounded bg-blue-700 px-4 py-2 text-white">Create demo walkthrough</button></form>}</div></Section>
<section className="mt-8 rounded-2xl bg-slate-900 p-6 text-white"><h2 className="text-2xl font-bold">Ready for your first estimate?</h2><p className="mt-2 text-slate-300">You can return to any setup section later.</p><div className="mt-4 flex gap-3"><form action={finishOnboardingAction}><button className="rounded bg-white px-5 py-3 font-semibold text-slate-900">Create First Estimate</button></form><Link href="/dashboard" className="rounded border border-slate-500 px-5 py-3">Dashboard</Link></div></section></main></AppLayout>}
function Section({title,done,children}:{title:string;done:boolean;children:React.ReactNode}){return <section className="mt-6 rounded-2xl border bg-white p-5"><div className="flex justify-between"><h2 className="text-xl font-bold">{title}</h2>{done&&<span className="text-green-700">Complete</span>}</div><div className="mt-4">{children}</div></section>}
function Form({action,children}:{action:(data:FormData)=>Promise<void>;children:React.ReactNode}){return <form action={action} className="grid gap-3 md:grid-cols-2">{children}</form>}
function Input({name,label,type="text",value}:{name:string;label:string;type?:string;value?:string|number|null}){return <label className="grid gap-1 text-sm">{label}<input name={name} type={type} step={type==="number"?"0.01":undefined} defaultValue={value??""} className="rounded border p-2"/></label>}
function Check({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="flex items-center gap-2 text-sm"><input name={name} type="checkbox" defaultChecked={checked}/>{label}</label>}
function Save({label="Save section"}:{label?:string}){return <button className="self-end rounded bg-blue-700 px-4 py-2 text-white">{label}</button>}
function List({values}:{values:string[]}){return values.length?<ul className="mt-4 list-disc pl-6 text-sm text-slate-600">{values.map(value=><li key={value}>{value}</li>)}</ul>:null}
