import "server-only";
import type { FieldChangeOrderType, FieldJobStage, FieldTimeEventType, Prisma } from "@/generated/prisma/client";
import { prisma } from "@/lib/prisma";
import { recordEstimateEventInTransaction, type EstimateEventActor } from "@/lib/estimates/estimateEvents";
import { updateJob } from "@/lib/jobs/updateJob";
import { createInvoiceFromJob } from "@/lib/invoices/createInvoice";
import { assertCoordinate, canTransitionFieldStage, validNextTimeEvents, REQUIRED_FIELD_CHECKLIST } from "./policy";
import type { TenantContext } from "@/lib/auth/tenant";

export type FieldActor = { userId: string; employeeId: string; displayName: string; manager: boolean; platformAdmin?: boolean };
const eventActor = (actor: FieldActor): EstimateEventActor => ({ type: actor.platformAdmin ? "PlatformAdmin" : "Employee", id: actor.employeeId, userId: actor.userId, displayName: actor.displayName });

export async function runFieldQuery<T>(name:string,query:()=>Promise<T>):Promise<T>{
  try{return await query()}catch(error){console.error(`FIELD_QUERY_FAILED ${name}`,error);throw error}
}

export async function resolveFieldActor(context:TenantContext,options:{allowUnlinked?:boolean}={}):Promise<FieldActor> {
  const employee=await runFieldQuery("active_employee",()=>prisma.employee.findFirst({where:{companyId:context.companyId,userId:context.user.id,status:"Active"},select:{id:true,firstName:true,lastName:true}}));
  if(!employee&&!options.allowUnlinked)throw new Error("An active employee profile linked to this account is required for field operations.");
  const fallbackName=[context.user.firstName,context.user.lastName].filter(Boolean).join(" ")||context.user.email;
  return {userId:context.user.id,employeeId:employee?.id??`unlinked:${context.user.id}`,displayName:employee?`${employee.firstName} ${employee.lastName}`.trim():fallbackName,manager:context.user.platformAdmin||["Owner","Admin","Manager","Office"].includes(context.role),platformAdmin:context.user.platformAdmin};
}

async function assignedJob(companyId: string, jobId: string, actor: FieldActor) {
  const job = await prisma.job.findFirst({ where: { id: jobId, companyId, ...(actor.manager || actor.platformAdmin ? {} : { assignments: { some: { OR: [{ employeeId: actor.employeeId }, { crew: { members: { some: { employeeId: actor.employeeId } } } }] } } }) }, select: { id:true,companyId:true,estimateId:true,fieldStage:true,fieldVersion:true,status:true,enRouteAt:true,arrivedAt:true,completedAt:true,completionNotes:true,crewConfirmedAt:true,invoice:{select:{id:true}} } });
  if (!job) throw new Error("Job not found or is not assigned to this crew member.");
  return job;
}
export async function assertFieldJobAccess(companyId:string,jobId:string,actor:FieldActor){return assignedJob(companyId,jobId,actor);}

export async function recordFieldPhotoEvent(companyId:string,jobId:string,actor:FieldActor,photoIds:string[],action:"added"|"updated"|"removed") { const job=await assignedJob(companyId,jobId,actor); return prisma.$transaction(tx=>recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:action==="removed"?"Photos Removed":"Photos Added",category:"Photos",actor:eventActor(actor),jobId,summary:`${actor.displayName} ${action} ${photoIds.length} field photo(s).`,attachments:action==="removed"?undefined:photoIds.map(id=>({referenceType:"Photo",referenceId:id,displayName:"Field photo"})),metadata:{photoIds,action}})); }

export async function getFieldDashboard(companyId: string, actor: FieldActor, now = new Date()) {
  const start = new Date(now); start.setHours(0,0,0,0); const end = new Date(start); end.setDate(end.getDate()+1);
  const assignment = actor.manager || actor.platformAdmin ? {} : { assignments:{some:{OR:[{employeeId:actor.employeeId},{crew:{members:{some:{employeeId:actor.employeeId}}}}]}} };
  const base = { companyId, ...assignment };
  const select = { id:true,jobNumber:true,fieldStage:true,status:true,scheduledStart:true,scheduledEnd:true,customer:{select:{firstName:true,lastName:true,phone:true}},property:{select:{address:true,city:true,state:true,zip:true}} } as const;
  const [today,upcoming,overdue,completed,current] = await Promise.all([
    runFieldQuery("field_dashboard_today_jobs",()=>prisma.job.findMany({where:{...base,scheduledStart:{gte:start,lt:end}},select,orderBy:{scheduledStart:"asc"},take:50})),
    runFieldQuery("field_dashboard_upcoming_jobs",()=>prisma.job.findMany({where:{...base,scheduledStart:{gte:end},fieldStage:{notIn:["Completed","ReadyForInvoice"]}},select,orderBy:{scheduledStart:"asc"},take:50})),
    runFieldQuery("field_dashboard_overdue_jobs",()=>prisma.job.findMany({where:{...base,scheduledStart:{lt:start},fieldStage:{notIn:["Completed","ReadyForInvoice"]}},select,orderBy:{scheduledStart:"asc"},take:50})),
    runFieldQuery("field_dashboard_completed_jobs",()=>prisma.job.findMany({where:{...base,completedAt:{gte:start,lt:end}},select,orderBy:{completedAt:"desc"},take:50})),
    runFieldQuery("field_dashboard_current_job",()=>prisma.job.findFirst({where:{...base,fieldStage:{in:["EnRoute","Arrived","Working","Loading","Cleanup"]}},select,orderBy:{updatedAt:"desc"}})),
  ]);
  return { today, upcoming, overdue, completedToday:completed, currentJob:current };
}

export async function getFieldJob(companyId:string,jobId:string,actor:FieldActor) {
  await assignedJob(companyId,jobId,actor);
  return prisma.job.findUnique({where:{id:jobId},include:{customer:true,property:true,estimate:{include:{jobSites:{include:{items:true}}}},photos:{orderBy:[{category:"asc"},{sortOrder:"asc"}]},assignments:{include:{employee:true,crew:{include:{members:{include:{employee:true}}}}}},fieldChecklistItems:{orderBy:{createdAt:"asc"}},fieldChangeOrders:{orderBy:{createdAt:"desc"}},completionSignature:true,fieldTimeEvents:{where:{employeeId:actor.employeeId},orderBy:{timestamp:"asc"}},disposalRecords:{orderBy:{createdAt:"desc"}}}});
}

const stageEvents:Record<FieldJobStage,string>={Scheduled:"Estimate Scheduled",EnRoute:"Crew En Route",Arrived:"Crew Arrived",Working:"Work Started",Loading:"Loading Started",Cleanup:"Cleanup Started",Completed:"Job Completed",ReadyForInvoice:"Ready for Invoice"};
export async function transitionFieldStage(companyId:string,jobId:string,actor:FieldActor,to:FieldJobStage,input:{latitude?:number;longitude?:number;authorizedSkip?:boolean;baseVersion?:number}={}) {
  assertCoordinate(input.latitude,"latitude"); assertCoordinate(input.longitude,"longitude");
  const job=await assignedJob(companyId,jobId,actor);
  if(!canTransitionFieldStage(job.fieldStage,to,Boolean(input.authorizedSkip&&actor.manager))) throw new Error(`Invalid field status transition: ${job.fieldStage} to ${to}. Complete each required stage in order.`);
  if(input.baseVersion!==undefined&&input.baseVersion!==job.fieldVersion) throw new Error("This job changed while offline. Refresh and resolve the conflict before retrying.");
  if(to==="Completed") await assertCompletionReady(companyId,jobId,actor);
  if(to==="Working"&&job.status!=="InProgress") await updateJob(companyId,{id:jobId,status:"InProgress"});
  if(to==="Completed"&&job.status!=="Completed") await updateJob(companyId,{id:jobId,status:"Completed"});
  const now=new Date();
  const updated=await prisma.$transaction(async tx=>{
    const row=await tx.job.update({where:{id:jobId},data:{fieldStage:to,fieldVersion:{increment:1},...(to==="EnRoute"?{enRouteAt:now,departureLatitude:input.latitude,departureLongitude:input.longitude}:{}),...(to==="Arrived"?{arrivedAt:now,arrivalLatitude:input.latitude,arrivalLongitude:input.longitude,...(job.enRouteAt?{travelDurationMinutes:Math.max(0,Math.round((now.getTime()-job.enRouteAt.getTime())/60000))}:{})}:{}),...(to==="Completed"?{completedAt:now,completionLatitude:input.latitude,completionLongitude:input.longitude}:{})}});
    // updateJob already records the canonical Job Completed lifecycle event.
    if(to!=="Completed") await recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:stageEvents[to] as never,category:"Job",actor:eventActor(actor),jobId,summary:`${actor.displayName} moved the job to ${to}.`,visibility:"Internal",metadata:{from:job.fieldStage,to,latitude:input.latitude,longitude:input.longitude}});
    return row;
  });
  if(to==="ReadyForInvoice"&&!job.invoice) await createInvoiceFromJob(companyId,jobId);
  return updated;
}

export async function ensureFieldChecklist(companyId:string,jobId:string,actor:FieldActor) { await assignedJob(companyId,jobId,actor); await prisma.fieldChecklistItem.createMany({data:REQUIRED_FIELD_CHECKLIST.map(([key,label])=>({companyId,jobId,key,label})),skipDuplicates:true}); return prisma.fieldChecklistItem.findMany({where:{companyId,jobId},orderBy:{createdAt:"asc"}}); }
export async function updateFieldChecklist(companyId:string,jobId:string,actor:FieldActor,key:string,completed:boolean,notes="") { const job=await assignedJob(companyId,jobId,actor); await ensureFieldChecklist(companyId,jobId,actor); return prisma.$transaction(async tx=>{const item=await tx.fieldChecklistItem.update({where:{jobId_key:{jobId,key}},data:{completedAt:completed?new Date():null,completedByEmployeeId:completed?actor.employeeId:null,notes:notes.trim()}}); await recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:"Checklist Updated",category:"Job",actor:eventActor(actor),jobId,summary:`${actor.displayName} ${completed?"completed":"reopened"} ${item.label}.`,metadata:{key,completed}}); return item;}); }

export async function addFieldNote(companyId:string,jobId:string,actor:FieldActor,note:string) {
  const job=await assignedJob(companyId,jobId,actor);
  const value=note.trim();
  if(!value||value.length>5_000)throw new Error("Field note is required and must be 5,000 characters or fewer.");
  return prisma.$transaction(async tx=>{
    const current=await tx.job.findUniqueOrThrow({where:{id:jobId},select:{crewNotes:true}});
    const updated=await tx.job.update({where:{id:jobId},data:{crewNotes:[current.crewNotes.trim(),value].filter(Boolean).join("\n")}});
    await recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:"Field Notes Updated",category:"Notes",actor:eventActor(actor),jobId,summary:`${actor.displayName} added a field note.`,visibility:"Internal"});
    return updated;
  });
}

export async function requestFieldChangeOrder(companyId:string,jobId:string,actor:FieldActor,input:{type:FieldChangeOrderType;description:string;proposedAmount:number}) { const job=await assignedJob(companyId,jobId,actor); if(!input.description.trim())throw new Error("Change order description is required."); if(!Number.isFinite(input.proposedAmount)||input.proposedAmount<0)throw new Error("Proposed amount must be zero or greater."); const estimate=await prisma.estimate.findUniqueOrThrow({where:{id:job.estimateId},select:{pricingTotal:true}});return prisma.$transaction(async tx=>{const order=await tx.fieldChangeOrder.create({data:{companyId,jobId,requestedByEmployeeId:actor.employeeId,type:input.type,description:input.description.trim(),proposedAmount:input.proposedAmount,originalAmount:estimate.pricingTotal,status:"Submitted"}}); await recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:"Change Order Requested",category:"Pricing",actor:eventActor(actor),jobId,summary:`${actor.displayName} requested a change order: ${input.description.trim()}.`,metadata:{changeOrderId:order.id,type:order.type,proposedAmount:order.proposedAmount,originalAmount:order.originalAmount},notification:{title:"Field change order requested",body:input.description.trim()}}); return order;}); }

export async function respondToFieldChangeOrder(companyId:string,orderId:string,actor:FieldActor,approved:boolean,customerName:string) { if(!actor.manager&&!actor.platformAdmin)throw new Error("Manager authorization is required."); const order=await prisma.fieldChangeOrder.findFirst({where:{id:orderId,companyId,status:"Pending"},include:{job:{select:{estimateId:true}}}}); if(!order)throw new Error("Pending change order not found."); return prisma.$transaction(async tx=>{const updated=await tx.fieldChangeOrder.update({where:{id:order.id},data:{status:approved?"Approved":"Declined",customerName:customerName.trim(),...(approved?{customerApprovedAt:new Date()}:{customerDeclinedAt:new Date()})}}); await recordEstimateEventInTransaction(tx,{companyId,estimateId:order.job.estimateId,eventType:approved?"Change Order Approved":"Change Order Declined",category:"Pricing",actor:eventActor(actor),jobId:order.jobId,summary:`${customerName.trim()||"Customer"} ${approved?"approved":"declined"} the field change order.`,visibility:"Both",metadata:{changeOrderId:order.id}}); return updated;}); }

export async function getManagerChangeOrders(companyId:string,actor:FieldActor){if(!actor.manager&&!actor.platformAdmin)throw new Error("Manager authorization is required.");return prisma.fieldChangeOrder.findMany({where:{companyId,status:{in:["Submitted","ManagerReview","ChangesRequested","CustomerApprovalRequired"]}},orderBy:{createdAt:"asc"},take:100,include:{requestedByEmployee:{select:{firstName:true,lastName:true,userId:true}},job:{select:{id:true,jobNumber:true,estimateId:true,customer:{select:{firstName:true,lastName:true}},photos:{where:{category:{in:["AdditionalItems","Damage"]}},take:12,orderBy:{createdAt:"desc"}}}}}});}
export async function reviewFieldChangeOrder(companyId:string,orderId:string,actor:FieldActor,input:{decision:"approve"|"reject"|"changes";note?:string;version:number;requiresCustomerApproval?:boolean}){if(!actor.manager&&!actor.platformAdmin)throw new Error("Manager authorization is required.");if(input.decision!=="approve"&&!input.note?.trim())throw new Error("A manager note is required for rejection or requested changes.");const order=await prisma.fieldChangeOrder.findFirst({where:{id:orderId,companyId},include:{job:{select:{estimateId:true}},requestedByEmployee:{select:{userId:true}}}});if(!order)throw new Error("Change order not found.");if(!["Submitted","ManagerReview","ChangesRequested"].includes(order.status))throw new Error("This change order has already been reviewed.");const next=input.decision==="approve"?(input.requiresCustomerApproval===false?"Approved":"CustomerApprovalRequired"):input.decision==="reject"?"Rejected":"ChangesRequested";return prisma.$transaction(async tx=>{const changed=await tx.fieldChangeOrder.updateMany({where:{id:order.id,companyId,version:input.version,status:{in:["Submitted","ManagerReview","ChangesRequested"]}},data:{status:next,managerNote:input.note?.trim()||null,requiresCustomerApproval:input.requiresCustomerApproval!==false,managerReviewedAt:new Date(),version:{increment:1}}});if(changed.count!==1)throw new Error("This change order changed while you were reviewing it. Refresh and try again.");const updated=await tx.fieldChangeOrder.findUniqueOrThrow({where:{id:order.id}});await recordEstimateEventInTransaction(tx,{companyId,estimateId:order.job.estimateId,eventType:next==="Approved"?"Change Order Approved":next==="Rejected"?"Change Order Declined":"Change Order Requested",category:"Pricing",actor:eventActor(actor),jobId:order.jobId,summary:`${actor.displayName} ${input.decision==="approve"?"approved":input.decision==="reject"?"rejected":"requested changes to"} the change order.`,visibility:next==="CustomerApprovalRequired"?"Both":"Internal",metadata:{changeOrderId:order.id,status:next,managerNote:input.note},notification:{userId:order.requestedByEmployee.userId??undefined,title:"Change order updated",body:`Change order is now ${next}.`}});return updated;});}

export async function saveCompletionSignature(companyId:string,jobId:string,actor:FieldActor,input:{printedName:string;signatureData:string;device:string;notes?:string;deviceSignedAt?:Date;deviceTimeZone?:string;consentTextSnapshot?:string;offlineIdempotencyKey?:string}) {
  const job=await assignedJob(companyId,jobId,actor);
  if(!input.printedName.trim()||!input.signatureData.trim()||!input.device.trim())throw new Error("Printed name, signature, and device are required.");
  const data={companyId,jobId,employeeId:actor.employeeId,printedName:input.printedName.trim(),signatureData:input.signatureData,device:input.device.trim(),notes:input.notes?.trim()??"",deviceSignedAt:input.deviceSignedAt,deviceTimeZone:input.deviceTimeZone,consentTextSnapshot:input.consentTextSnapshot,offlineIdempotencyKey:input.offlineIdempotencyKey};
  return prisma.$transaction(async tx=>{
    const signature=input.offlineIdempotencyKey
      ? await tx.jobCompletionSignature.create({data})
      : await tx.jobCompletionSignature.upsert({where:{jobId},create:data,update:{...data,companyId:undefined,jobId:undefined,signedAt:new Date()}});
    await recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:"Completion Signed",category:"Job",actor:eventActor(actor),jobId,summary:`${input.printedName.trim()} signed the job completion.`,visibility:"Both",metadata:{signatureId:signature.id,device:signature.device}});
    return signature;
  });
}

export async function recordFieldTimeEvent(companyId:string,jobId:string,actor:FieldActor,type:FieldTimeEventType,coordinates?:{latitude?:number;longitude?:number}) { const job=await assignedJob(companyId,jobId,actor); const last=await prisma.fieldTimeEvent.findFirst({where:{companyId,jobId,employeeId:actor.employeeId},orderBy:{timestamp:"desc"},select:{type:true}}); const valid=validNextTimeEvents(last?.type);if(!valid.includes(type))throw new Error(`Invalid time event. Next allowed action: ${valid.join(" or ")}.`); return prisma.$transaction(async tx=>{const event=await tx.fieldTimeEvent.create({data:{companyId,jobId,employeeId:actor.employeeId,type,latitude:coordinates?.latitude,longitude:coordinates?.longitude}}); await recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:"Time Tracking Updated",category:"Job",actor:eventActor(actor),jobId,summary:`${actor.displayName}: ${type}.`,metadata:{timeEventId:event.id,type}}); return event;}); }

export async function recordDisposal(companyId:string,jobId:string,actor:FieldActor,input:{category:"Landfill"|"Donation"|"Recycling"|"ScrapMetal"|"HazardousWaste"|"Other";facility:string;occurredAt?:Date;weight?:number;weightUnit?:string;cost:number;paymentMethod?:"Cash"|"Check"|"CreditCard"|"DebitCard"|"ACH"|"CashApp"|"ApplePay"|"Other";receiptUrl?:string;notes?:string}) { const job=await assignedJob(companyId,jobId,actor); if(!input.facility.trim())throw new Error("Disposal facility is required."); if(!Number.isFinite(input.cost)||input.cost<0||!Number.isFinite(input.weight??0)||(input.weight??0)<0||(input.weight??0)>1_000_000)throw new Error("Disposal weight and cost must be realistic non-negative values.");const occurredAt=input.occurredAt??new Date();if(occurredAt.getTime()>Date.now()+5*60_000)throw new Error("Disposal time cannot be in the future.");const duplicate=await prisma.disposalRecord.findFirst({where:{companyId,jobId,facility:input.facility.trim(),cost:input.cost,occurredAt:{gte:new Date(occurredAt.getTime()-60_000),lte:new Date(occurredAt.getTime()+60_000)}}});if(duplicate)throw new Error("This disposal entry appears to be a duplicate."); return prisma.$transaction(async tx=>{const row=await tx.disposalRecord.create({data:{companyId,jobId,...input,occurredAt,facility:input.facility.trim(),weightUnit:input.weightUnit?.trim()||"lb",paymentMethod:input.paymentMethod??"Other",createdByEmployeeId:actor.employeeId,notes:input.notes?.trim()??""}});const total=await tx.disposalRecord.aggregate({where:{companyId,jobId},_sum:{cost:true}});await tx.job.update({where:{id:jobId},data:{actualDisposalCost:total._sum.cost??0}}); await recordEstimateEventInTransaction(tx,{companyId,estimateId:job.estimateId,eventType:"Disposal Recorded",category:"Job",actor:eventActor(actor),jobId,summary:`${actor.displayName} recorded ${input.category} disposal at ${input.facility.trim()}.`,attachments:input.receiptUrl?[{referenceType:"Document",referenceId:row.id,displayName:"Disposal receipt",url:input.receiptUrl}]:undefined,metadata:{disposalRecordId:row.id,weight:row.weight,weightUnit:row.weightUnit,cost:row.cost,totalCost:total._sum.cost??0}}); return {...row,totalCost:total._sum.cost??0};}); }

async function assertCompletionReady(companyId:string,jobId:string,actor:FieldActor) { await ensureFieldChecklist(companyId,jobId,actor); const [missing,photos,signature,job,pending]=await Promise.all([prisma.fieldChecklistItem.count({where:{companyId,jobId,required:true,completedAt:null}}),prisma.jobPhoto.count({where:{companyId,jobId,category:{in:["Before","After"]}}}),prisma.jobCompletionSignature.findUnique({where:{jobId},select:{id:true}}),prisma.job.findUnique({where:{id:jobId},select:{completionNotes:true,crewConfirmedAt:true}}),prisma.fieldChangeOrder.count({where:{companyId,jobId,status:{not:"Approved"}}})]); const failures=[];if(missing)failures.push(`${missing} required checklist item(s)`);if(photos<2)failures.push("before and after photos");if(!signature)failures.push("customer signature");if(!job?.completionNotes.trim())failures.push("completion notes");if(!job?.crewConfirmedAt)failures.push("crew confirmation");if(pending)failures.push("unapproved change orders");if(failures.length)throw new Error(`Job cannot be completed. Missing: ${failures.join(", ")}.`); }

export async function confirmFieldCompletion(companyId:string,jobId:string,actor:FieldActor,completionNotes:string) { await assignedJob(companyId,jobId,actor); if(!completionNotes.trim())throw new Error("Completion notes are required."); return prisma.job.update({where:{id:jobId},data:{completionNotes:completionNotes.trim(),crewConfirmedAt:new Date(),fieldVersion:{increment:1}}}); }

type OfflineInput={clientOperationId:string;jobId:string;operationType:"stage"|"checklist"|"note";payload:Record<string,unknown>;baseVersion:number};
export async function syncFieldOperations(companyId:string,actor:FieldActor,operations:OfflineInput[]) { if(operations.length>100)throw new Error("Sync batches are limited to 100 operations."); const results=[]; for(const op of operations){await assignedJob(companyId,op.jobId,actor); const existing=await prisma.fieldOfflineOperation.findUnique({where:{companyId_clientOperationId:{companyId,clientOperationId:op.clientOperationId}}});if(existing){results.push(existing);continue;} const job=await prisma.job.findUniqueOrThrow({where:{id:op.jobId},select:{fieldVersion:true}});if(job.fieldVersion!==op.baseVersion){results.push(await prisma.fieldOfflineOperation.create({data:{companyId,jobId:op.jobId,employeeId:actor.employeeId,clientOperationId:op.clientOperationId,operationType:op.operationType,payload:op.payload as Prisma.InputJsonValue,baseVersion:op.baseVersion,status:"Conflict",conflictMessage:"Server version changed. Refresh before retrying."}}));continue;} try{if(op.operationType==="stage")await transitionFieldStage(companyId,op.jobId,actor,String(op.payload.stage) as FieldJobStage,{baseVersion:op.baseVersion,latitude:Number(op.payload.latitude)||undefined,longitude:Number(op.payload.longitude)||undefined});else if(op.operationType==="checklist")await updateFieldChecklist(companyId,op.jobId,actor,String(op.payload.key),Boolean(op.payload.completed),String(op.payload.notes??""));else await confirmFieldCompletion(companyId,op.jobId,actor,String(op.payload.notes??""));results.push(await prisma.fieldOfflineOperation.create({data:{companyId,jobId:op.jobId,employeeId:actor.employeeId,clientOperationId:op.clientOperationId,operationType:op.operationType,payload:op.payload as Prisma.InputJsonValue,baseVersion:op.baseVersion,status:"Applied",appliedAt:new Date()}}));}catch(error){results.push(await prisma.fieldOfflineOperation.create({data:{companyId,jobId:op.jobId,employeeId:actor.employeeId,clientOperationId:op.clientOperationId,operationType:op.operationType,payload:op.payload as Prisma.InputJsonValue,baseVersion:op.baseVersion,status:"Failed",conflictMessage:error instanceof Error?error.message:"Operation failed."}}));}} return results; }
