export type OfflinePhotoState="queued"|"uploading"|"failed"|"synced";
export type OfflinePhotoType="Before"|"During"|"After"|"Damage"|"AdditionalItems"|"Receipt";
export interface OfflinePhotoRecord {localId:string;clientOperationId:string;companyId:string;userId:string;jobId:string;file:Blob;fileName:string;mimeType:string;photoType:OfflinePhotoType;customerVisible:boolean;caption:string;annotationMetadata?:unknown;originalLocalId?:string;createdAt:number;retryCount:number;syncState:OfflinePhotoState;error?:string;serverPhotoId?:string}
const DB_NAME="junkquote-field-photos-v1",STORE="photos",MAX_FILE=10*1024*1024,MAX_TOTAL=200*1024*1024;
export const offlinePhotoLimits={maxFileBytes:MAX_FILE,maxTotalBytes:MAX_TOTAL};

function request<T>(value:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{value.onsuccess=()=>resolve(value.result);value.onerror=()=>reject(value.error??new Error("IndexedDB operation failed."));});}
export async function openOfflinePhotoDatabase(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const store=db.createObjectStore(STORE,{keyPath:"localId"});store.createIndex("scope",["companyId","userId","jobId"]);store.createIndex("sync",["companyId","userId","syncState"]);store.createIndex("clientOperationId","clientOperationId",{unique:true});}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error??new Error("Offline photo storage is unavailable."));});}
async function store(mode:IDBTransactionMode){const db=await openOfflinePhotoDatabase();const tx=db.transaction(STORE,mode);return {db,tx,store:tx.objectStore(STORE)};}
export async function listOfflinePhotos(scope:{companyId:string;userId:string;jobId?:string}){const {db,store:objectStore}=await store("readonly");const all=await request(objectStore.getAll()) as OfflinePhotoRecord[];db.close();return all.filter(row=>row.companyId===scope.companyId&&row.userId===scope.userId&&(!scope.jobId||row.jobId===scope.jobId)).sort((a,b)=>a.createdAt-b.createdAt);}
export async function enqueueOfflinePhoto(input:Omit<OfflinePhotoRecord,"localId"|"clientOperationId"|"createdAt"|"retryCount"|"syncState">){if(input.file.size<=0||input.file.size>MAX_FILE)throw new Error("Photo must be between 1 byte and 10 MB.");if(!["image/jpeg","image/png","image/webp","image/heic"].includes(input.mimeType))throw new Error("Only JPEG, PNG, WebP, and HEIC photos are supported.");const scoped=await listOfflinePhotos({companyId:input.companyId,userId:input.userId});if(scoped.reduce((sum,row)=>sum+(row.syncState==="synced"?0:row.file.size),0)+input.file.size>MAX_TOTAL)throw new Error("Offline photo storage limit of 200 MB would be exceeded.");const localId=crypto.randomUUID(),row:OfflinePhotoRecord={...input,localId,clientOperationId:localId,createdAt:Date.now(),retryCount:0,syncState:"queued"};const {db,tx,store:objectStore}=await store("readwrite");objectStore.add(row);await new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();return row;}
export async function updateOfflinePhoto(localId:string,changes:Partial<OfflinePhotoRecord>){const {db,tx,store:objectStore}=await store("readwrite");const row=await request(objectStore.get(localId)) as OfflinePhotoRecord|undefined;if(!row)throw new Error("Queued photo not found.");objectStore.put({...row,...changes,localId:row.localId,companyId:row.companyId,userId:row.userId,jobId:row.jobId,clientOperationId:row.clientOperationId});await new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();}
export async function removeOfflinePhoto(localId:string,scope:{companyId:string;userId:string}){const {db,tx,store:objectStore}=await store("readwrite");const row=await request(objectStore.get(localId)) as OfflinePhotoRecord|undefined;if(row&&(row.companyId!==scope.companyId||row.userId!==scope.userId))throw new Error("Queued photo does not belong to this account.");if(row)objectStore.delete(localId);await new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();}
export async function syncOfflinePhotos(scope:{companyId:string;userId:string;jobId?:string},upload:(row:OfflinePhotoRecord)=>Promise<{id:string}>){const rows=(await listOfflinePhotos(scope)).filter(row=>row.syncState!=="synced"&&row.syncState!=="uploading");const results=[];for(const row of rows){if(!navigator.onLine)break;await updateOfflinePhoto(row.localId,{syncState:"uploading",error:undefined});try{const saved=await upload(row);await updateOfflinePhoto(row.localId,{syncState:"synced",serverPhotoId:saved.id,error:undefined});results.push({localId:row.localId,state:"synced" as const});}catch(error){await updateOfflinePhoto(row.localId,{syncState:"failed",retryCount:row.retryCount+1,error:error instanceof Error?error.message:"Upload failed."});results.push({localId:row.localId,state:"failed" as const});}}return results;}
export function inOfflinePhotoScope(row:OfflinePhotoRecord,scope:{companyId:string;userId:string;jobId?:string}){return row.companyId===scope.companyId&&row.userId===scope.userId&&(!scope.jobId||row.jobId===scope.jobId)}
export async function syncPhotoBatch(rows:OfflinePhotoRecord[],online:()=>boolean,upload:(row:OfflinePhotoRecord)=>Promise<{id:string}>,update:(id:string,changes:Partial<OfflinePhotoRecord>)=>Promise<void>){const results=[];for(const row of rows.filter(value=>value.syncState!=="synced"&&value.syncState!=="uploading")){if(!online())break;await update(row.localId,{syncState:"uploading",error:undefined});try{const saved=await upload(row);await update(row.localId,{syncState:"synced",serverPhotoId:saved.id,error:undefined});results.push({localId:row.localId,state:"synced" as const});}catch(error){await update(row.localId,{syncState:"failed",retryCount:row.retryCount+1,error:error instanceof Error?error.message:"Upload failed."});results.push({localId:row.localId,state:"failed" as const});}}return results;}
export async function retryOfflinePhoto(localId:string){await updateOfflinePhoto(localId,{syncState:"queued",error:undefined});}
export async function compressPhoto(file:File,maxDimension=2200,quality=.86):Promise<File>{if(file.type!=="image/jpeg"&&file.type!=="image/png"&&file.type!=="image/webp")return file;const bitmap=await createImageBitmap(file,{imageOrientation:"from-image"});if(Math.max(bitmap.width,bitmap.height)<=maxDimension&&file.size<=4*1024*1024){bitmap.close();return file;}const scale=Math.min(1,maxDimension/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("Could not resize photo.")),"image/jpeg",quality));return new File([blob],file.name.replace(/\.[^.]+$/,"")+".jpg",{type:"image/jpeg",lastModified:file.lastModified});}
