import type { EmployeeRole, EmployeeStatus } from "@/generated/prisma/client";
import { prisma } from "../prisma";

export interface ListEmployeesInput { search?: string; role?: EmployeeRole; status?: EmployeeStatus; page?: number; pageSize?: number; sort?: "name" | "role" | "newest" | "oldest"; }
export interface EmployeeInput { firstName: string; lastName: string; email?: string; phone?: string; role: EmployeeRole; hourlyRate?: number | null; color?: string; notes?: string; }
export interface CrewInput { name: string; color?: string; }

export async function listEmployees(companyId: string, input: ListEmployeesInput = {}) { const pageSize = Math.min(50, Math.max(1, input.pageSize ?? 20)); const page = Math.max(1, input.page ?? 1); const search = input.search?.trim(); const where = { companyId, ...(input.role ? { role: input.role } : {}), ...(input.status ? { status: input.status } : {}), ...(search ? { OR: [{ firstName: { contains: search, mode: "insensitive" as const } }, { lastName: { contains: search, mode: "insensitive" as const } }, { email: { contains: search, mode: "insensitive" as const } }, { phone: { contains: search, mode: "insensitive" as const } }] } : {}) }; const orderBy = input.sort === "newest" ? { createdAt: "desc" as const } : input.sort === "oldest" ? { createdAt: "asc" as const } : input.sort === "role" ? { role: "asc" as const } : { firstName: "asc" as const }; const [employees, total] = await prisma.$transaction([prisma.employee.findMany({ where, orderBy, skip: (page - 1) * pageSize, take: pageSize, include: { crewMembers: { where: { crew: { companyId } }, include: { crew: true } } } }), prisma.employee.count({ where })]); return { employees, total, page, pageSize }; }
export async function getEmployee(companyId: string, employeeId: string) { return prisma.employee.findFirst({ where: { id: employeeId, companyId }, include: { crewMembers: { where: { crew: { companyId } }, include: { crew: true } }, assignments: { where: { companyId, job: { companyId } }, include: { job: true } } } }); }
export const getEmployeeDetail = getEmployee;
export async function createEmployee(companyId: string, input: EmployeeInput) { return prisma.employee.create({ data: { companyId, firstName: input.firstName.trim(), lastName: input.lastName.trim(), email: input.email?.trim() || null, phone: input.phone?.trim() || null, role: input.role, hourlyRate: input.hourlyRate ?? null, color: input.color?.trim() || null, notes: input.notes?.trim() || null } }); }
export async function updateEmployee(companyId: string, employeeId: string, input: EmployeeInput) { const employee = await getEmployee(companyId, employeeId); if (!employee) throw new Error("Employee not found."); return prisma.employee.update({ where: { id: employee.id }, data: { firstName: input.firstName.trim(), lastName: input.lastName.trim(), email: input.email?.trim() || null, phone: input.phone?.trim() || null, role: input.role, hourlyRate: input.hourlyRate ?? null, color: input.color?.trim() || null, notes: input.notes?.trim() || null } }); }
export async function setEmployeeStatus(companyId: string, employeeId: string, status: EmployeeStatus) { const employee = await getEmployee(companyId, employeeId); if (!employee) throw new Error("Employee not found."); return prisma.employee.update({ where: { id: employee.id }, data: { status } }); }
export function archiveEmployee(companyId: string, employeeId: string) { return setEmployeeStatus(companyId, employeeId, "Inactive"); }

export async function listCrews(companyId: string, active?: boolean) { return prisma.crew.findMany({ where: { companyId, ...(active === undefined ? {} : { active }) }, orderBy: { name: "asc" }, include: { members: { where: { employee: { companyId } }, include: { employee: true } } } }); }
export async function getCrew(companyId: string, crewId: string) { return prisma.crew.findFirst({ where: { id: crewId, companyId }, include: { members: { where: { employee: { companyId } }, include: { employee: true } }, assignments: { where: { companyId, job: { companyId } }, include: { job: true } } } }); }
export const getCrewDetail = getCrew;
export async function createCrew(companyId: string, input: CrewInput) { return prisma.crew.create({ data: { companyId, name: input.name.trim(), color: input.color?.trim() || null } }); }
export async function updateCrew(companyId: string, crewId: string, input: CrewInput) { const crew = await getCrew(companyId, crewId); if (!crew) throw new Error("Crew not found."); return prisma.crew.update({ where: { id: crew.id }, data: { name: input.name.trim(), color: input.color?.trim() || null } }); }
export async function setCrewStatus(companyId: string, crewId: string, active: boolean) { const crew = await getCrew(companyId, crewId); if (!crew) throw new Error("Crew not found."); return prisma.crew.update({ where: { id: crew.id }, data: { active } }); }
export async function deleteCrew(companyId: string, crewId: string) { const crew = await getCrew(companyId, crewId); if (!crew) throw new Error("Crew not found."); return prisma.crew.delete({ where: { id: crew.id } }); }
export async function addCrewMember(companyId: string, crewId: string, employeeId: string) { const [crew, employee] = await Promise.all([getCrew(companyId, crewId), getEmployee(companyId, employeeId)]); if (!crew || !employee) throw new Error("Crew or employee not found."); return prisma.crewMember.create({ data: { crewId: crew.id, employeeId: employee.id } }); }
export async function removeCrewMember(companyId: string, crewId: string, employeeId: string) { const [crew, employee] = await Promise.all([getCrew(companyId, crewId), getEmployee(companyId, employeeId)]); if (!crew || !employee) throw new Error("Crew or employee not found."); return prisma.crewMember.delete({ where: { crewId_employeeId: { crewId: crew.id, employeeId: employee.id } } }); }
export async function setCrewLead(companyId: string, crewId: string, employeeId: string) { const crew = await getCrew(companyId, crewId); if (!crew) throw new Error("Crew lead must be an active crew member."); const member = crew.members.find((item) => item.employeeId === employeeId); if (!member || member.employee.status !== "Active") throw new Error("Crew lead must be an active crew member."); return prisma.$transaction([prisma.crewMember.updateMany({ where: { crewId: crew.id, crew: { companyId } }, data: { isLead: false } }), prisma.crewMember.update({ where: { crewId_employeeId: { crewId: crew.id, employeeId } }, data: { isLead: true } })]); }
