import { DEVELOPMENT_COMPANY_ID } from "@/lib/config";
import { prisma } from "../prisma";
import type { EmployeeRole, EmployeeStatus } from "@/generated/prisma/client";

export async function listEmployees(input: { search?: string; role?: EmployeeRole; status?: EmployeeStatus; page?: number; pageSize?: number; sort?: "name" | "role" | "newest" | "oldest" } = {}) { const pageSize = Math.min(50, Math.max(1, input.pageSize ?? 20)); const page = Math.max(1, input.page ?? 1); const search = input.search?.trim(); const where = { companyId: DEVELOPMENT_COMPANY_ID, ...(input.role ? { role: input.role } : {}), ...(input.status ? { status: input.status } : {}), ...(search ? { OR: [{ firstName: { contains: search, mode: "insensitive" as const } }, { lastName: { contains: search, mode: "insensitive" as const } }, { email: { contains: search, mode: "insensitive" as const } }, { phone: { contains: search, mode: "insensitive" as const } }] } : {}) }; const orderBy = input.sort === "newest" ? { createdAt: "desc" as const } : input.sort === "oldest" ? { createdAt: "asc" as const } : input.sort === "role" ? { role: "asc" as const } : { firstName: "asc" as const }; const [employees, total] = await prisma.$transaction([prisma.employee.findMany({ where, orderBy, skip: (page - 1) * pageSize, take: pageSize, include: { crewMembers: { include: { crew: true } } } }), prisma.employee.count({ where })]); return { employees, total, page, pageSize }; }
export async function getEmployeeDetail(id: string) { return prisma.employee.findFirst({ where: { id, companyId: DEVELOPMENT_COMPANY_ID }, include: { crewMembers: { include: { crew: true } }, assignments: { include: { job: true } } } }); }
export async function createEmployee(input: { firstName: string; lastName: string; email?: string; phone?: string; role: EmployeeRole; hourlyRate?: number | null; color?: string; notes?: string }) { return prisma.employee.create({ data: { companyId: DEVELOPMENT_COMPANY_ID, firstName: input.firstName.trim(), lastName: input.lastName.trim(), email: input.email?.trim() || null, phone: input.phone?.trim() || null, role: input.role, hourlyRate: input.hourlyRate ?? null, color: input.color?.trim() || null, notes: input.notes?.trim() || null } }); }
export async function updateEmployee(id: string, input: Parameters<typeof createEmployee>[0]) { const employee = await getEmployeeDetail(id); if (!employee) throw new Error("Employee not found."); return prisma.employee.update({ where: { id }, data: { firstName: input.firstName.trim(), lastName: input.lastName.trim(), email: input.email?.trim() || null, phone: input.phone?.trim() || null, role: input.role, hourlyRate: input.hourlyRate ?? null, color: input.color?.trim() || null, notes: input.notes?.trim() || null } }); }
export async function setEmployeeStatus(id: string, status: EmployeeStatus) { const employee = await getEmployeeDetail(id); if (!employee) throw new Error("Employee not found."); return prisma.employee.update({ where: { id }, data: { status } }); }
export async function listCrews(active?: boolean) { return prisma.crew.findMany({ where: { companyId: DEVELOPMENT_COMPANY_ID, ...(active === undefined ? {} : { active }) }, orderBy: { name: "asc" }, include: { members: { include: { employee: true } } } }); }
export async function getCrewDetail(id: string) { return prisma.crew.findFirst({ where: { id, companyId: DEVELOPMENT_COMPANY_ID }, include: { members: { include: { employee: true } }, assignments: { include: { job: true } } } }); }
export async function createCrew(input: { name: string; color?: string }) { return prisma.crew.create({ data: { companyId: DEVELOPMENT_COMPANY_ID, name: input.name.trim(), color: input.color?.trim() || null } }); }
export async function updateCrew(id: string, input: { name: string; color?: string }) { const crew = await getCrewDetail(id); if (!crew) throw new Error("Crew not found."); return prisma.crew.update({ where: { id }, data: { name: input.name.trim(), color: input.color?.trim() || null } }); }
export async function setCrewStatus(id: string, active: boolean) { const crew = await getCrewDetail(id); if (!crew) throw new Error("Crew not found."); return prisma.crew.update({ where: { id }, data: { active } }); }
export async function addCrewMember(crewId: string, employeeId: string) { const [crew, employee] = await Promise.all([getCrewDetail(crewId), getEmployeeDetail(employeeId)]); if (!crew || !employee) throw new Error("Crew or employee not found."); return prisma.crewMember.create({ data: { crewId, employeeId } }); }
export async function removeCrewMember(crewId: string, employeeId: string) { const crew = await getCrewDetail(crewId); if (!crew) throw new Error("Crew not found."); return prisma.crewMember.delete({ where: { crewId_employeeId: { crewId, employeeId } } }); }
export async function setCrewLead(crewId: string, employeeId: string) { const crew = await getCrewDetail(crewId); const member = crew?.members.find((item) => item.employeeId === employeeId); if (!member || member.employee.status !== "Active") throw new Error("Crew lead must be an active crew member."); return prisma.$transaction([prisma.crewMember.updateMany({ where: { crewId }, data: { isLead: false } }), prisma.crewMember.update({ where: { crewId_employeeId: { crewId, employeeId } }, data: { isLead: true } })]); }
