import { prisma } from "@/lib/prisma";
import { Prisma, type EmployeeRole, type FleetAssetType } from "@/generated/prisma/client";
import { withDistributedLock } from "@/lib/distributed/locks";

export const onboardingSections = ["profile", "branding", "pricing", "service-area", "team", "equipment", "preferences", "communication", "demo"] as const;
export type OnboardingSection = typeof onboardingSections[number];
export function onboardingProgress(completedSections:string[]){return Math.round(new Set(completedSections).size/onboardingSections.length*100)}
export function validateOnboardingProfile(input:{name:string;email?:string;website?:string;serviceRadiusMiles:number}){if(!input.name.trim())throw new Error("Company name is required.");if(input.email&&!/^\S+@\S+\.\S+$/.test(input.email))throw new Error("Enter a valid email address.");if(input.website&&!/^https?:\/\//i.test(input.website))throw new Error("Website must begin with http:// or https://.");if(!Number.isFinite(input.serviceRadiusMiles)||input.serviceRadiusMiles<0||input.serviceRadiusMiles>1000)throw new Error("Service radius must be between 0 and 1,000 miles.")}
export async function getOnboarding(companyId: string) {
  const state = await prisma.companyOnboarding.upsert({ where: { companyId }, create: { companyId }, update: {} });
  const [company, settings, serviceAreas, employees, assets, crews] = await Promise.all([
    prisma.company.findUniqueOrThrow({ where: { id: companyId } }),
    prisma.companySettings.upsert({ where: { companyId }, create: { companyId }, update: {} }),
    prisma.serviceAreaRule.findMany({ where: { companyId }, orderBy: [{ kind: "asc" }, { value: "asc" }] }),
    prisma.employee.findMany({ where: { companyId }, orderBy: { createdAt: "asc" } }),
    prisma.fleetAsset.findMany({ where: { companyId }, orderBy: { createdAt: "asc" } }),
    prisma.crew.findMany({ where: { companyId }, orderBy: { createdAt: "asc" } }),
  ]);
  return { state, company, settings, serviceAreas, employees, assets, crews, progress: onboardingProgress(state.completedSections) };
}
export async function completeSection(companyId: string, section: OnboardingSection) {
  const current = await prisma.companyOnboarding.findUnique({ where: { companyId } });
  const completedSections = Array.from(new Set([...(current?.completedSections ?? []), section]));
  const complete = onboardingSections.every((item) => completedSections.includes(item));
  return prisma.companyOnboarding.upsert({ where: { companyId }, create: { companyId, completedSections, currentStep: Math.min(10, onboardingSections.indexOf(section) + 2), completedAt: complete ? new Date() : null }, update: { completedSections, currentStep: Math.min(10, onboardingSections.indexOf(section) + 2), completedAt: complete ? new Date() : undefined, skippedAt: null } });
}
export async function saveProfile(companyId: string, input: { name: string; phone?: string; email?: string; website?: string; addressLine1?: string; city?: string; state?: string; postalCode?: string; timezone: string; serviceRadiusMiles: number }) {
  validateOnboardingProfile(input);
  await prisma.$transaction([prisma.company.update({ where: { id: companyId }, data: { name: input.name.trim(), legalName: input.name.trim(), displayName: input.name.trim(), phone: input.phone?.trim() || null, email: input.email?.trim().toLowerCase() || null, website: input.website?.trim() || null, addressLine1: input.addressLine1?.trim() || null, city: input.city?.trim() || null, state: input.state?.trim() || null, postalCode: input.postalCode?.trim() || null, timezone: input.timezone } }), prisma.companySettings.upsert({ where: { companyId }, create: { companyId, timezone: input.timezone, serviceRadiusMiles: input.serviceRadiusMiles }, update: { timezone: input.timezone, serviceRadiusMiles: input.serviceRadiusMiles } })]);
  return completeSection(companyId, "profile");
}
export async function savePricing(companyId: string, input: { minimum: number; labor: number; dump: number; tax: number; heavy: number; appliance: number; yard: number; construction: number }) {
  if (Object.values(input).some((value) => !Number.isFinite(value) || value < 0)) throw new Error("Pricing values cannot be negative.");
  if (input.tax > 100) throw new Error("Tax rate cannot exceed 100%.");
  await prisma.$transaction([prisma.company.update({ where: { id: companyId }, data: { defaultMinimumCharge: input.minimum, defaultTaxRate: input.tax } }), prisma.companySettings.upsert({ where: { companyId }, create: { companyId, defaultLaborRate: input.labor, defaultDumpFee: input.dump, taxRate: input.tax, heavyItemSurcharge: input.heavy, appliancePrice: input.appliance, yardDebrisPrice: input.yard, constructionDebrisPrice: input.construction }, update: { defaultLaborRate: input.labor, defaultDumpFee: input.dump, taxRate: input.tax, heavyItemSurcharge: input.heavy, appliancePrice: input.appliance, yardDebrisPrice: input.yard, constructionDebrisPrice: input.construction } })]);
  return completeSection(companyId, "pricing");
}
export async function addServiceArea(companyId: string, input: { kind: string; value: string; zone?: string; charge: number }) { if (!input.value.trim()) throw new Error("ZIP code or city is required."); await prisma.serviceAreaRule.upsert({ where: { companyId_kind_value: { companyId, kind: input.kind, value: input.value.trim() } }, create: { companyId, kind: input.kind, value: input.value.trim(), travelZone: input.zone?.trim() || null, distanceCharge: input.charge }, update: { travelZone: input.zone?.trim() || null, distanceCharge: input.charge } }); return completeSection(companyId, "service-area"); }
export async function addTeamMember(companyId: string, input: { firstName: string; lastName: string; email?: string; role: EmployeeRole }) { if (!input.firstName.trim() || !input.lastName.trim()) throw new Error("Team member name is required."); const employee=await prisma.employee.create({ data: { companyId, firstName: input.firstName.trim(), lastName: input.lastName.trim(), email: input.email?.trim().toLowerCase() || null, role: input.role, certifications: [],invitationStatus:input.email?"Invited":"NotInvited",invitationSentAt:input.email?new Date():null } }); await completeSection(companyId, "team");return employee; }
export async function addEquipment(companyId: string, input: { type: FleetAssetType; name: string; crewName?: string }) { if (!input.name.trim()) throw new Error("Equipment name is required."); await prisma.fleetAsset.create({ data: { companyId, type: input.type, name: input.name.trim() } }); if (input.crewName?.trim()) await prisma.crew.create({ data: { companyId, name: input.crewName.trim() } }); return completeSection(companyId, "equipment"); }
export async function createDemoData(companyId: string) { return withDistributedLock("onboarding-demo", companyId, 60_000, async () => prisma.$transaction(async (tx) => { const state = await tx.companyOnboarding.upsert({ where: { companyId }, create: { companyId }, update: {} }); if (state.demoDataIds) return state; const pricingProfile = await tx.pricingProfile.findFirst({ where: { companyId, active: true, defaultProfile: true }, select: { id: true } }); if (!pricingProfile) throw new Error("A default pricing profile is required."); const customer = await tx.customer.create({ data: { companyId, firstName: "Jamie", lastName: "Sample", phone: "555-0100", email: "sample@example.com", notes: "Onboarding demo data" } }); const property = await tx.property.create({ data: { customerId: customer.id, nickname: "Sample Home", address: "123 Demo Street", city: "Your City", state: "NY", zip: "10001" } }); const estimate = await tx.estimate.create({ data: { companyId, pricingProfileId: pricingProfile.id, customerId: customer.id, propertyId: property.id, status: "Approved", pricingSubtotal: 450, pricingLabor: 150, pricingDisposal: 75, pricingTotal: 675, signedAt: new Date(), signerName: "Jamie Sample", signatureMethod: "PublicLink" } }); const site = await tx.jobSite.create({ data: { estimateId: estimate.id, name: "Garage", sortOrder: 0 } }); await tx.estimateItem.create({ data: { jobSiteId: site.id, itemId: "demo-sofa", name: "Sofa", category: "Furniture", quantity: 1, sortOrder: 0, priceOverride: 150 } }); const job = await tx.job.create({ data: { companyId, estimateId: estimate.id, customerId: customer.id, propertyId: property.id, status: "Completed", completedAt: new Date(), completionNotes: "Sample completed job", finalInvoiceAmount: 675 } }); const last = await tx.invoice.aggregate({ _max: { invoiceNumber: true } }); const invoice = await tx.invoice.create({ data: { companyId, customerId: customer.id, propertyId: property.id, jobId: job.id, estimateId: estimate.id, invoiceNumber: (last._max.invoiceNumber ?? 0) + 1, subtotal: 675, total: 675, balanceDue: 675, status: "Draft", lineItems: { create: [{ description: "Sample junk removal", quantity: 1, unitPrice: 675, amount: 675 }] } } }); const demoDataIds = { customerId: customer.id, propertyId: property.id, estimateId: estimate.id, jobId: job.id, invoiceId: invoice.id } as Prisma.InputJsonValue; const completedSections=Array.from(new Set([...state.completedSections,"demo"])); return tx.companyOnboarding.update({ where: { companyId }, data: { demoDataIds,completedSections,currentStep:10,completedAt:onboardingSections.every(section=>completedSections.includes(section))?new Date():undefined } }); })); }
export async function deleteDemoData(companyId: string) { return withDistributedLock("onboarding-demo", companyId, 60_000, async () => { const state = await prisma.companyOnboarding.findUnique({ where: { companyId } }); const ids = state?.demoDataIds as { customerId?: string } | null; if (!ids?.customerId) return; await prisma.$transaction([prisma.customer.deleteMany({ where: { id: ids.customerId, companyId, notes: "Onboarding demo data" } }), prisma.companyOnboarding.update({ where: { companyId }, data: { demoDataIds: Prisma.JsonNull } })]); }); }
