import { describe, expect, it } from "vitest";
import { calculatePricingOutcome, type PricingOutcomeInput } from "./outcomeCalculator";
const complete = (overrides: Partial<PricingOutcomeInput> = {}): PricingOutcomeInput => ({ quotedAmount: 500, invoicedAmount: 550, collectedAmount: 550, refundAmount: 0, discountAmount: 0, laborHoursEstimated: 3, laborHoursActual: 4, laborCostEstimated: 100, laborCostActual: 120, disposalCostEstimated: 50, disposalCostActual: 60, travelCostEstimated: 20, travelCostActual: 20, otherCostActual: 0, ...overrides });
describe("pricing outcome calculation", () => {
  it("calculates complete outcomes reproducibly", () => { const result = calculatePricingOutcome(complete()); expect(result).toMatchObject({ estimateVarianceAmount: 50, estimateVariancePercent: 10, grossProfit: 350, completenessScore: 100, classification: "underbid", collectionStatus: "collected" }); expect(result.grossMarginPercent).toBeCloseTo(63.636); });
  it("reports missing actual costs instead of treating them as zero", () => { const result = calculatePricingOutcome(complete({ laborCostActual: null, travelCostActual: null })); expect(result.grossProfit).toBeNull(); expect(result.actualCostTotal).toBeNull(); expect(result.missingData).toEqual(expect.arrayContaining(["laborCostActual", "travelCostActual"])); expect(result.completenessScore).toBeLessThan(100); });
  it("classifies partial, full, and refunded collection", () => { expect(calculatePricingOutcome(complete({ collectedAmount: 200 })).collectionStatus).toBe("partially-collected"); expect(calculatePricingOutcome(complete()).collectionStatus).toBe("collected"); const refunded = calculatePricingOutcome(complete({ refundAmount: 100 })); expect(refunded.netCollected).toBe(450); expect(refunded.collectionStatus).toBe("partially-collected"); });
  it("classifies overbids and on-target estimates", () => { expect(calculatePricingOutcome(complete({ invoicedAmount: 400 })).classification).toBe("overbid"); expect(calculatePricingOutcome(complete({ invoicedAmount: 500 })).classification).toBe("on-target"); });
  it("handles zero quotes without invalid percentages", () => { const result = calculatePricingOutcome(complete({ quotedAmount: 0 })); expect(result.estimateVariancePercent).toBeNull(); expect(result.collectedVariancePercent).toBeNull(); });
  it("reports nullable estimated labor inputs", () => { const result = calculatePricingOutcome(complete({ laborHoursEstimated: null, laborCostEstimated: null })); expect(result.missingData).toEqual(expect.arrayContaining(["laborHoursEstimated", "laborCostEstimated"])); expect(result.estimatedCostTotal).toBeNull(); });
});
