import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "About Chris, Founder of JunkQuote Pro",
  description: "JunkQuote Pro was built by a junk removal business owner for the people doing the work.",
};

export default function About() {
  return <main className="min-h-screen bg-[#050806] px-5 py-12 text-white sm:px-8"><div className="mx-auto max-w-4xl"><Link href="/" className="font-black text-[#a4ef29]">JunkQuote Pro</Link><section className="mt-12 grid items-start gap-10 md:grid-cols-[220px_1fr]"><Image src="/branding/chris-founder.jpeg" alt="Chris, founder of JunkQuote Pro" width={220} height={220} className="aspect-square rounded-3xl object-cover object-[32%_25%]" /><article><p className="font-bold uppercase tracking-[.2em] text-[#a4ef29]">Meet the founder</p><h1 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">Built by a Junk Removal Business Owner, for the People Doing the Work</h1><div className="mt-8 space-y-5 text-lg leading-relaxed text-slate-300"><p>JunkQuote Pro was born from a problem I experienced firsthand.</p><p>I own and operate a junk removal business, and I know how much time can be wasted trying to build accurate estimates, keep track of jobs, manage customers, and keep everything organized while you&apos;re also out there doing the actual work.</p><p>Most estimating software is either too complicated, too expensive, or built around industries that don&apos;t really understand how junk removal works.</p><p>So I decided to build something different.</p><p className="font-semibold text-white">I&apos;m the founder of JunkQuote Pro, and I built it around the way junk removal businesses actually operate.</p><p>The goal isn&apos;t to create another piece of software that looks impressive but makes your day harder. The goal is to give junk removal companies a simple system that helps them quote jobs faster, stay organized, and look more professional to their customers.</p><p>JunkQuote Pro is being built from real-world experience, with features designed around the problems I&apos;ve personally dealt with in my own business.</p><p>And we&apos;re still building.</p><p>As JunkQuote Pro grows, the goal is simple: <strong className="text-white">help small junk removal businesses spend less time fighting with paperwork and estimates, and more time making money doing the work they already know how to do.</strong></p></div><p className="mt-8 font-bold text-[#a4ef29]">— Chris<br /><span className="text-slate-200">Founder, JunkQuote Pro</span></p><Link href="/sign-up" className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-[#a4ef29] px-6 font-black text-black">Start your 30-day trial</Link></article></section></div></main>;
}
