import Image from "next/image";
import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { marketingMetadata } from "@/lib/marketing/metadata";
import { founderLinkedInUrl } from "@/lib/marketing/homepage";

export const metadata = marketingMetadata(
  "/about",
  "About the Founder | JunkQuote Pro",
  "Meet the junk removal business owner behind JunkQuote Pro and learn why the software was built around the way junk removal companies actually work.",
);

export default function About() {
  return <main className="min-h-screen overflow-x-hidden bg-[#050806] text-white">
    <header className="border-b border-[#a4ef29]/20 bg-black/80"><nav aria-label="Public navigation" className="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-x-4 px-5 py-2 sm:px-8"><Link href="/" className="inline-flex min-h-11 items-center text-lg font-black tracking-tight">JunkQuote <span className="ml-1 text-[#a4ef29]">Pro</span></Link><div className="flex flex-wrap items-center justify-end gap-1"><Link href="/features" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Features</Link><Link href="/pricing" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Pricing</Link><Link href="/about" aria-current="page" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">About</Link><Link href="/sign-in" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Sign in</Link></div></nav></header>
    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-5xl items-start gap-10 md:grid-cols-[260px_1fr]"><Image src="/branding/chris-founder.jpg" alt="Chris, founder of JunkQuote Pro" width={260} height={260} priority className="h-auto w-full max-w-[260px] rounded-3xl object-cover object-[32%_25%]" /><article><p className="font-bold uppercase tracking-[.2em] text-[#a4ef29]">Meet the founder</p><h1 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">Built by Someone Who Knows the Work</h1><div className="mt-8 space-y-5 text-lg leading-relaxed text-slate-300"><p>JunkQuote Pro was born from a problem I experienced firsthand.</p><p>I own and operate a junk removal business, and I know how much time can be wasted trying to build accurate estimates, keep track of jobs, manage customers, and keep everything organized while you&apos;re also out there doing the actual work.</p></div></article></div></section>
    <section className="border-y border-white/10 bg-[#090d0a] px-5 py-16 sm:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black sm:text-4xl">Why I Built JunkQuote Pro</h2><div className="mt-6 space-y-5 text-lg leading-relaxed text-slate-300"><p>Most estimating software is either too complicated, too expensive, or built around industries that don&apos;t really understand how junk removal works.</p><p>So I decided to build something different.</p><p>I&apos;m the founder of JunkQuote Pro, and I built it around the way junk removal businesses actually operate.</p><p>The goal isn&apos;t to create another piece of software that looks impressive but makes your day harder. The goal is to give junk removal companies a simple system that helps them quote jobs faster, stay organized, and look more professional to their customers.</p></div></div></section>
    <section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black sm:text-4xl">Built Around Real-World Work</h2><div className="mt-6 space-y-5 text-lg leading-relaxed text-slate-300"><p>JunkQuote Pro is being built from real-world experience, with features designed around the problems I&apos;ve personally dealt with in my own business.</p><p>As JunkQuote Pro grows, the goal is simple: help small junk removal businesses spend less time fighting with paperwork and estimates, and more time making money doing the work they already know how to do.</p></div><p className="mt-8 font-bold text-white">Chris<br /><span className="text-slate-300">Founder, JunkQuote Pro</span></p><a href={founderLinkedInUrl} target="_blank" rel="noopener noreferrer" aria-label="Chris on LinkedIn" className="mt-3 inline-flex min-h-11 items-center gap-2 font-bold text-[#a4ef29] underline decoration-2 underline-offset-4"><ExternalLink aria-hidden="true" size={18} /><span>LinkedIn</span></a></div></section>
    <section className="border-t border-white/10 bg-[#090d0a] px-5 py-16 text-center sm:px-8"><h2 className="text-3xl font-black">Ready to See What JunkQuote Pro Can Do?</h2><Link href="/sign-up" className="mt-6 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#a4ef29] px-6 py-3 text-center font-black text-black">Start Your 30-Day Professional Trial</Link></section>
  </main>;
}
