"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireAdminTenant } from "@/lib/auth/tenant";
import { prisma } from "@/lib/prisma";
import { addEquipment, addServiceArea, addTeamMember, completeSection, createDemoData, deleteDemoData, savePricing, saveProfile } from "@/lib/onboarding/service";
import { uploadCompanyLogo } from "@/lib/company/branding";
import type { EmployeeRole, FleetAssetType } from "@/generated/prisma/client";
import { recordAuditEvent } from "@/lib/audit/audit";
import { createNotification } from "@/lib/notifications/service";

const text = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const number = (data: FormData, key: string) => Number(data.get(key) ?? 0);
async function context() { return requireAdminTenant(); }
async function done(companyId:string,userId:string,section:string){await recordAuditEvent({companyId,actingUserId:userId,eventType:"onboarding.section_completed",entityType:"Company",entityId:companyId,metadata:{section}});revalidatePath("/onboarding");revalidatePath("/dashboard")}
export async function saveProfileAction(data:FormData){const c=await context();await saveProfile(c.companyId,{name:text(data,"name"),phone:text(data,"phone"),email:text(data,"email"),website:text(data,"website"),addressLine1:text(data,"address"),city:text(data,"city"),state:text(data,"state"),postalCode:text(data,"postalCode"),timezone:text(data,"timezone")||"America/New_York",serviceRadiusMiles:number(data,"serviceRadius")});const logo=data.get("logo");if(logo instanceof File&&logo.size>0)await uploadCompanyLogo(c.companyId,logo);await done(c.companyId,c.user.id,"profile")}
export async function saveBrandingAction(data:FormData){const c=await context();const color=(key:string)=>{const value=text(data,key);if(value&&!/^#[0-9a-f]{6}$/i.test(value))throw new Error("Brand colors must be six-digit hex values.");return value||null};await prisma.$transaction([prisma.company.update({where:{id:c.companyId},data:{primaryColor:color("primary"),secondaryColor:color("secondary")}}),prisma.companySettings.upsert({where:{companyId:c.companyId},create:{companyId:c.companyId,pdfBrandingEnabled:data.get("pdf")==="on",portalBrandingEnabled:data.get("portal")==="on"},update:{pdfBrandingEnabled:data.get("pdf")==="on",portalBrandingEnabled:data.get("portal")==="on"}})]);await completeSection(c.companyId,"branding");await done(c.companyId,c.user.id,"branding")}
export async function savePricingAction(data:FormData){const c=await context();await savePricing(c.companyId,{minimum:number(data,"minimum"),labor:number(data,"labor"),dump:number(data,"dump"),tax:number(data,"tax"),heavy:number(data,"heavy"),appliance:number(data,"appliance"),yard:number(data,"yard"),construction:number(data,"construction")});const items=text(data,"items").split(",").map(value=>value.trim()).filter(Boolean).slice(0,100);await prisma.companySettings.update({where:{companyId:c.companyId},data:{itemLibraryDefaults:items}});await done(c.companyId,c.user.id,"pricing")}
export async function addServiceAreaAction(data:FormData){const c=await context();await addServiceArea(c.companyId,{kind:text(data,"kind"),value:text(data,"value"),zone:text(data,"zone"),charge:number(data,"charge")});await done(c.companyId,c.user.id,"service-area")}
export async function addTeamMemberAction(data:FormData){const c=await context();const email=text(data,"email");const employee=await addTeamMember(c.companyId,{firstName:text(data,"firstName"),lastName:text(data,"lastName"),email,role:text(data,"role") as EmployeeRole});if(email)await createNotification({companyId:c.companyId,channel:"email",to:email,title:`You’re invited to ${c.company.name}`,body:`You were invited as ${employee.role}. Contact the company owner to activate your staff account.`});await done(c.companyId,c.user.id,"team")}
export async function addEquipmentAction(data:FormData){const c=await context();await addEquipment(c.companyId,{type:text(data,"type") as FleetAssetType,name:text(data,"name"),crewName:text(data,"crew")});await done(c.companyId,c.user.id,"equipment")}
export async function savePreferencesAction(data:FormData){const c=await context();await prisma.$transaction([prisma.company.update({where:{id:c.companyId},data:{defaultEstimateExpirationDays:number(data,"estimateExpiration"),defaultPaymentTermsDays:number(data,"invoiceTerms"),currencyCode:text(data,"currency")||"USD"}}),prisma.companySettings.upsert({where:{companyId:c.companyId},create:{companyId:c.companyId,businessHours:text(data,"businessHours"),approvalExpirationDays:number(data,"approvalExpiration"),dateFormat:text(data,"dateFormat")},update:{businessHours:text(data,"businessHours"),approvalExpirationDays:number(data,"approvalExpiration"),dateFormat:text(data,"dateFormat")}})]);await completeSection(c.companyId,"preferences");await done(c.companyId,c.user.id,"preferences")}
export async function saveCommunicationAction(data:FormData){const c=await context();const reply=text(data,"replyTo");if(reply&&!/^\S+@\S+\.\S+$/.test(reply))throw new Error("Enter a valid reply-to address.");await prisma.companySettings.upsert({where:{companyId:c.companyId},create:{companyId:c.companyId,communicationSenderName:text(data,"sender"),communicationReplyTo:reply,estimateEmailTemplate:text(data,"estimateEmail"),invoiceEmailTemplate:text(data,"invoiceEmail"),approvalEmailTemplate:text(data,"approvalEmail")},update:{communicationSenderName:text(data,"sender"),communicationReplyTo:reply,estimateEmailTemplate:text(data,"estimateEmail"),invoiceEmailTemplate:text(data,"invoiceEmail"),approvalEmailTemplate:text(data,"approvalEmail")}});await completeSection(c.companyId,"communication");await done(c.companyId,c.user.id,"communication")}
export async function createDemoDataAction(){const c=await context();await createDemoData(c.companyId);await done(c.companyId,c.user.id,"demo")}
export async function deleteDemoDataAction(){const c=await context();await deleteDemoData(c.companyId);await done(c.companyId,c.user.id,"demo_deleted")}
export async function skipOnboardingAction(){const c=await context();await prisma.companyOnboarding.upsert({where:{companyId:c.companyId},create:{companyId:c.companyId,skippedAt:new Date()},update:{skippedAt:new Date()}});redirect("/dashboard")}
export async function finishOnboardingAction(){const c=await context();await prisma.companyOnboarding.update({where:{companyId:c.companyId},data:{completedAt:new Date(),dismissedAt:null}});redirect("/estimates")}
export async function dismissOnboardingAction(){const c=await context();await prisma.companyOnboarding.update({where:{companyId:c.companyId},data:{dismissedAt:new Date()}});revalidatePath("/dashboard")}
