-- AlterTable
ALTER TABLE "companies" ADD COLUMN     "addressLine1" TEXT,
ADD COLUMN     "addressLine2" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "currencyCode" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN     "defaultEstimateExpirationDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "defaultMinimumCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "defaultPaymentTermsDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "defaultTaxRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "displayName" TEXT NOT NULL DEFAULT 'JunkQuote Pro',
ADD COLUMN     "estimatePrefix" TEXT NOT NULL DEFAULT 'EST',
ADD COLUMN     "invoicePrefix" TEXT NOT NULL DEFAULT 'INV',
ADD COLUMN     "legalName" TEXT NOT NULL DEFAULT 'JunkQuote Pro',
ADD COLUMN     "logoUrl" TEXT,
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "primaryColor" TEXT,
ADD COLUMN     "secondaryColor" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "timezone" TEXT NOT NULL DEFAULT 'America/New_York';
