import type { JobPhotoCategory } from "@/generated/prisma/client";
import { DEVELOPMENT_COMPANY_ID } from "@/lib/config";
import { prisma } from "../prisma";
import { localJobPhotoStorage } from "../storage/jobPhotoStorage";

const allowedMimeTypes = ["image/jpeg", "image/png", "image/webp", "image/heic"];
export const maxJobPhotoSize = 10 * 1024 * 1024;
export function validateJobPhotoFile(file: File) { if (!allowedMimeTypes.includes(file.type)) throw new Error("Only JPEG, PNG, WebP, and HEIC images are supported."); if (file.size <= 0 || file.size > maxJobPhotoSize) throw new Error("Image must be no larger than 10 MB."); }

async function assertJob(jobId: string) { const job = await prisma.job.findFirst({ where: { id: jobId, companyId: DEVELOPMENT_COMPANY_ID }, select: { id: true, estimateId: true } }); if (!job) throw new Error("Job not found."); return job; }

export async function uploadJobPhotos(input: { jobId: string; jobSiteId?: string; category: JobPhotoCategory; files: File[] }) { const job = await assertJob(input.jobId); if (!input.files.length) throw new Error("Select at least one photo."); if (input.jobSiteId) { const site = await prisma.jobSite.findFirst({ where: { id: input.jobSiteId, estimateId: job.estimateId }, select: { id: true } }); if (!site) throw new Error("Job site not found for this job."); }
  const current = await prisma.jobPhoto.count({ where: { jobId: job.id, category: input.category } }); const uploaded = [];
  for (const [index, file] of input.files.entries()) { validateJobPhotoFile(file); const stored = await localJobPhotoStorage.save(file); try { uploaded.push(await prisma.jobPhoto.create({ data: { companyId: DEVELOPMENT_COMPANY_ID, jobId: job.id, ...(input.jobSiteId ? { jobSiteId: input.jobSiteId } : {}), category: input.category, fileUrl: stored.fileUrl, thumbnailUrl: stored.thumbnailUrl, fileName: file.name, mimeType: file.type, fileSize: file.size, sortOrder: current + index } })); } catch (error) { await localJobPhotoStorage.remove(stored.fileUrl); throw error; } }
  return uploaded;
}
export async function listJobPhotos(jobId: string) { await assertJob(jobId); return prisma.jobPhoto.findMany({ where: { jobId, companyId: DEVELOPMENT_COMPANY_ID }, orderBy: [{ category: "asc" }, { sortOrder: "asc" }], select: { id: true, jobSiteId: true, category: true, fileUrl: true, thumbnailUrl: true, fileName: true, mimeType: true, fileSize: true, caption: true, sortOrder: true, takenAt: true, createdAt: true } }); }
export async function updateJobPhoto(input: { id: string; category?: JobPhotoCategory; caption?: string | null; jobSiteId?: string | null; takenAt?: Date | null }) { const photo = await prisma.jobPhoto.findFirst({ where: { id: input.id, companyId: DEVELOPMENT_COMPANY_ID }, select: { id: true, job: { select: { estimateId: true } } } }); if (!photo) throw new Error("Photo not found."); if (input.jobSiteId) { const site = await prisma.jobSite.findFirst({ where: { id: input.jobSiteId, estimateId: photo.job.estimateId }, select: { id: true } }); if (!site) throw new Error("Job site not found for this job."); } return prisma.jobPhoto.update({ where: { id: photo.id }, data: { ...(input.category ? { category: input.category } : {}), ...(input.caption !== undefined ? { caption: input.caption?.trim() || null } : {}), ...(input.jobSiteId !== undefined ? { jobSiteId: input.jobSiteId } : {}), ...(input.takenAt !== undefined ? { takenAt: input.takenAt } : {}) } }); }
export async function deleteJobPhoto(photoId: string) { const photo = await prisma.jobPhoto.findFirst({ where: { id: photoId, companyId: DEVELOPMENT_COMPANY_ID }, select: { id: true, fileUrl: true, thumbnailUrl: true } }); if (!photo) throw new Error("Photo not found."); await prisma.jobPhoto.delete({ where: { id: photo.id } }); await localJobPhotoStorage.remove(photo.fileUrl); if (photo.thumbnailUrl && photo.thumbnailUrl !== photo.fileUrl) await localJobPhotoStorage.remove(photo.thumbnailUrl); }
export async function reorderJobPhotos(jobId: string, photoIds: string[]) { await assertJob(jobId); const photos = await prisma.jobPhoto.findMany({ where: { id: { in: photoIds }, jobId, companyId: DEVELOPMENT_COMPANY_ID }, select: { id: true } }); if (photos.length !== photoIds.length) throw new Error("Invalid photo order."); await prisma.$transaction(photoIds.map((id, sortOrder) => prisma.jobPhoto.update({ where: { id }, data: { sortOrder } }))); }
export async function getJobPhotoReportData(jobId: string) { const job = await prisma.job.findFirst({ where: { id: jobId, companyId: DEVELOPMENT_COMPANY_ID }, select: { scheduledStart: true, customer: { select: { firstName: true, lastName: true } }, property: { select: { address: true, city: true, state: true, zip: true } }, company: { select: { name: true, displayName: true, logoUrl: true, primaryColor: true, secondaryColor: true } }, photos: { where: { category: { in: ["Before", "After"] } }, orderBy: { sortOrder: "asc" }, select: { category: true, fileUrl: true, caption: true } } } }); if (!job) throw new Error("Job not found."); return job; }
