import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ findJob: vi.fn(), findSite: vi.fn(), count: vi.fn(), findMany: vi.fn(), findPhoto: vi.fn(), create: vi.fn(), update: vi.fn(), remove: vi.fn(), transaction: vi.fn(), saveFile: vi.fn(), removeFile: vi.fn() }));
vi.mock("../prisma", () => ({ prisma: { job: { findFirst: mocks.findJob }, jobSite: { findFirst: mocks.findSite }, jobPhoto: { count: mocks.count, findMany: mocks.findMany, findFirst: mocks.findPhoto, create: mocks.create, update: mocks.update, delete: mocks.remove }, $transaction: mocks.transaction } }));
vi.mock("../storage/jobPhotoStorage", () => ({ sanitizeJobPhotoFilename: (name: string) => name, localJobPhotoStorage: { save: mocks.saveFile, remove: mocks.removeFile } }));
import { deleteJobPhoto, getJobPhotoReportData, listJobPhotos, reorderJobPhotos, updateJobPhoto, uploadJobPhotos } from "./jobPhotos";
const file = { name: "before.jpg", type: "image/jpeg", size: 100 } as File;

describe("job photo tenant isolation", () => {
  beforeEach(() => vi.clearAllMocks());
  it("lists only photos belonging to an authenticated tenant job", async () => { mocks.findJob.mockResolvedValue({ id: "job-a", estimateId: "estimate-a" }); mocks.findMany.mockResolvedValue([]); await listJobPhotos("tenant-a", "job-a"); expect(mocks.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ companyId: "tenant-a", jobId: "job-a", job: { companyId: "tenant-a" } }), orderBy: [{ category: "asc" }, { sortOrder: "asc" }] })); });
  it("rejects listing and uploading to another tenant's job", async () => { mocks.findJob.mockResolvedValue(null); await expect(listJobPhotos("tenant-a", "job-b")).rejects.toThrow("Job not found"); await expect(uploadJobPhotos("tenant-a", "job-b", { category: "Before", files: [file] })).rejects.toThrow("Job not found"); expect(mocks.saveFile).not.toHaveBeenCalled(); });
  it("generates storage ownership server-side and preserves category ordering", async () => { mocks.findJob.mockResolvedValue({ id: "job-a", estimateId: "estimate-a" }); mocks.count.mockResolvedValue(2); mocks.saveFile.mockResolvedValue({ fileUrl: "/uploads/job-photos/tenant-a/job-a/id.jpg", thumbnailUrl: null }); mocks.create.mockResolvedValue({ id: "photo-a" }); await uploadJobPhotos("tenant-a", "job-a", { category: "After", files: [file] }); expect(mocks.saveFile).toHaveBeenCalledWith("tenant-a", "job-a", file); expect(mocks.create).toHaveBeenCalledWith({ data: expect.objectContaining({ companyId: "tenant-a", jobId: "job-a", category: "After", sortOrder: 2 }) }); });
  it("rejects updating and deleting another tenant's photo", async () => { mocks.findPhoto.mockResolvedValue(null); await expect(updateJobPhoto("tenant-a", "photo-b", { caption: "hidden" })).rejects.toThrow("Photo not found"); await expect(deleteJobPhoto("tenant-a", "photo-b")).rejects.toThrow("Photo not found"); expect(mocks.update).not.toHaveBeenCalled(); expect(mocks.remove).not.toHaveBeenCalled(); expect(mocks.removeFile).not.toHaveBeenCalled(); });
  it("deletes storage only after verified database ownership", async () => { mocks.findPhoto.mockResolvedValue({ id: "photo-a", jobId: "job-a", fileUrl: "/uploads/job-photos/tenant-a/job-a/id.jpg", thumbnailUrl: null }); mocks.remove.mockResolvedValue({}); await deleteJobPhoto("tenant-a", "photo-a"); expect(mocks.removeFile).toHaveBeenCalledWith("tenant-a", "job-a", "/uploads/job-photos/tenant-a/job-a/id.jpg"); });
  it("rejects another tenant's photo report", async () => { mocks.findJob.mockResolvedValue(null); await expect(getJobPhotoReportData("tenant-a", "job-b")).rejects.toThrow("Job not found"); });
  it("rejects cross-tenant IDs during reorder", async () => { mocks.findJob.mockResolvedValue({ id: "job-a", estimateId: "estimate-a" }); mocks.findMany.mockResolvedValue([{ id: "photo-a" }]); await expect(reorderJobPhotos("tenant-a", "job-a", ["photo-a", "photo-b"])).rejects.toThrow("Invalid photo order"); expect(mocks.transaction).not.toHaveBeenCalled(); });
});
