import type{Prisma}from"@/generated/prisma/client";
import{prisma}from"@/lib/prisma";
import{transitionEstimateInTransaction}from"@/lib/estimates/estimateLifecycle";
import{recordEstimateEventInTransaction}from"@/lib/estimates/estimateEvents";

export interface PortalIdentity{companyId:string;customerId:string;portalAccessId:string;displayName:string}
export interface PortalResponseInput{estimateId:string;response:"approve"|"decline";customerName:string;signatureData?:string;consentAccepted:boolean;termsVersion:string;declineReason?:string;ipAddress?:string;userAgent?:string}

export async function respondToPortalEstimate(identity:PortalIdentity,input:PortalResponseInput){
  if(!input.customerName.trim())throw new Error("Enter your name.");if(!input.termsVersion.trim())throw new Error("Terms version is required.");if(input.response==="approve"&&!input.consentAccepted)throw new Error("Consent is required to approve this estimate.");
  return prisma.$transaction(async tx=>{const estimate=await tx.estimate.findFirst({where:{id:input.estimateId,companyId:identity.companyId,customerId:identity.customerId},select:{id:true,status:true,approvalTokenExpiresAt:true,revisionRootId:true,revisionNumber:true}});if(!estimate)throw new Error("Estimate not found.");
    const existing=await tx.portalEstimateResponse.findUnique({where:{estimateId:estimate.id}});if(existing){if(existing.response===(input.response==="approve"?"Approved":"Declined"))return existing;throw new Error("This estimate already has a response.");}
    const rootId=estimate.revisionRootId??estimate.id;const latest=await tx.estimate.findFirst({where:{companyId:identity.companyId,customerId:identity.customerId,OR:[{id:rootId},{revisionRootId:rootId}]},orderBy:{revisionNumber:"desc"},select:{id:true}});if(latest?.id!==estimate.id)throw new Error("Only the current estimate revision can be approved or declined.");
    if(!["Sent","Viewed"].includes(estimate.status))throw new Error(`This estimate cannot be ${input.response==="approve"?"approved":"declined"} in its current state.`);if(!estimate.approvalTokenExpiresAt||estimate.approvalTokenExpiresAt<=new Date())throw new Error("This estimate has expired and must be resent.");
    const now=new Date(),next=input.response==="approve"?"Approved":"Declined";const response=await tx.portalEstimateResponse.create({data:{companyId:identity.companyId,customerId:identity.customerId,estimateId:estimate.id,revisionId:estimate.id,portalAccessId:identity.portalAccessId,response:next,customerName:input.customerName.trim(),declineReason:input.declineReason?.trim()||null,signatureData:input.signatureData||null,consentAccepted:input.consentAccepted,termsVersion:input.termsVersion,ipAddress:input.ipAddress,userAgent:input.userAgent?.slice(0,500)}});
    await transitionEstimateInTransaction(tx,identity.companyId,estimate.id,next,{actor:{label:input.customerName.trim(),type:"Customer",id:identity.portalAccessId,portalAccessId:identity.portalAccessId},metadata:{portalResponseId:response.id,revisionId:estimate.id,customerId:identity.customerId,termsVersion:input.termsVersion,declineReason:input.declineReason?.trim()||undefined},data:input.response==="approve"?{signerName:input.customerName.trim(),signatureData:input.signatureData||"consent",signedAt:now,signatureMethod:"PublicLink",approvalToken:null,approvalTokenExpiresAt:null}:{approvalToken:null,approvalTokenExpiresAt:null}});return response;
  },{isolationLevel:"Serializable"});
}

export async function requestJobReschedule(identity:PortalIdentity,input:{jobId:string;preferredStart:Date;preferredEnd?:Date;reason:string;customerNote?:string}){if(!input.reason.trim())throw new Error("A reschedule reason is required.");if(Number.isNaN(input.preferredStart.getTime())||input.preferredStart<=new Date())throw new Error("Choose a future preferred time.");if(input.preferredEnd&&input.preferredEnd<=input.preferredStart)throw new Error("Preferred end must be after the start.");return prisma.$transaction(async tx=>{const job=await tx.job.findFirst({where:{id:input.jobId,companyId:identity.companyId,customerId:identity.customerId},select:{id:true,estimateId:true}});if(!job)throw new Error("Job not found.");const request=await tx.customerRescheduleRequest.create({data:{companyId:identity.companyId,customerId:identity.customerId,jobId:job.id,portalAccessId:identity.portalAccessId,preferredStart:input.preferredStart,preferredEnd:input.preferredEnd,reason:input.reason.trim(),customerNote:input.customerNote?.trim()||null}});await recordEstimateEventInTransaction(tx,{companyId:identity.companyId,estimateId:job.estimateId,eventType:"Reschedule Requested",category:"Scheduling",actor:{type:"Customer",id:identity.portalAccessId,displayName:identity.displayName,portalAccessId:identity.portalAccessId},summary:`${identity.displayName} requested a schedule change`,visibility:"Both",jobId:job.id,metadata:{requestId:request.id,preferredStart:input.preferredStart.toISOString(),reason:input.reason.trim()},notification:{title:"Reschedule requested",body:`${identity.displayName} requested a schedule change.`}});return request});}

export interface MessageAttachment{fileName:string;mimeType:string;size:number;url:string}
const allowed=new Set(["image/jpeg","image/png","image/webp","application/pdf"]);
export function validateMessageAttachments(items:MessageAttachment[]){if(items.length>5)throw new Error("Attach no more than 5 files.");for(const item of items)if(!allowed.has(item.mimeType)||item.size>10*1024*1024)throw new Error("Attachment type or size is not allowed.")}
export async function createCustomerMessage(identity:PortalIdentity,input:{subject:string;body:string;estimateId?:string;jobId?:string;invoiceId?:string;attachments?:MessageAttachment[]}){const targets=[input.estimateId,input.jobId,input.invoiceId].filter(Boolean);if(targets.length!==1)throw new Error("A message must belong to one estimate, job, or invoice.");if(!input.body.trim()||input.body.trim().length>5000)throw new Error("Enter a message up to 5,000 characters.");validateMessageAttachments(input.attachments??[]);return prisma.$transaction(async tx=>{let estimateId=input.estimateId;if(input.estimateId&&!await tx.estimate.findFirst({where:{id:input.estimateId,companyId:identity.companyId,customerId:identity.customerId},select:{id:true}}))throw new Error("Estimate not found.");if(input.jobId){const row=await tx.job.findFirst({where:{id:input.jobId,companyId:identity.companyId,customerId:identity.customerId},select:{estimateId:true}});if(!row)throw new Error("Job not found.");estimateId=row.estimateId}if(input.invoiceId){const row=await tx.invoice.findFirst({where:{id:input.invoiceId,companyId:identity.companyId,customerId:identity.customerId},select:{estimateId:true}});if(!row)throw new Error("Invoice not found.");estimateId=row.estimateId}const thread=await tx.customerMessageThread.create({data:{companyId:identity.companyId,customerId:identity.customerId,portalAccessId:identity.portalAccessId,estimateId:input.estimateId,jobId:input.jobId,invoiceId:input.invoiceId,subject:input.subject.trim().slice(0,200)||"Customer message",messages:{create:{senderType:"Customer",senderId:identity.portalAccessId,senderDisplayName:identity.displayName,body:input.body.trim(),attachments:input.attachments as unknown as Prisma.InputJsonValue}}},include:{messages:true}});await recordEstimateEventInTransaction(tx,{companyId:identity.companyId,estimateId:estimateId!,eventType:"Customer Message Sent",category:"Communication",actor:{type:"Customer",id:identity.portalAccessId,displayName:identity.displayName,portalAccessId:identity.portalAccessId},summary:`${identity.displayName} sent a message`,visibility:"Both",metadata:{threadId:thread.id},notification:{title:"New customer message",body:`${identity.displayName} sent a message.`}});return thread});}

export function listCustomerMessages(identity:PortalIdentity,cursor?:string,limit=25){return prisma.customerMessageThread.findMany({where:{companyId:identity.companyId,customerId:identity.customerId,portalAccessId:identity.portalAccessId},orderBy:[{updatedAt:"desc"},{id:"desc"}],take:Math.min(50,Math.max(1,limit)),...(cursor?{cursor:{id:cursor},skip:1}:{}),include:{messages:{orderBy:[{createdAt:"asc"},{id:"asc"}],take:100}}})}
