import { reviewTaxDocumentAction, uploadTaxDocumentAction } from "@/app/actions/tax/tax";
import { TaxShell, taxField, yearFrom } from "@/features/tax/TaxShell";
import { requireTenantContext } from "@/lib/auth/tenant";
import { requireTaxCapability } from "@/lib/tax/permissions";
import { getTaxCenterData } from "@/lib/tax/service";

const categories = ["W9", "W2Copy", "Form1099Copy", "BusinessLicense", "ResaleCertificate", "InsuranceCertificate", "CpaCorrespondence", "IrsCorrespondence", "StateCorrespondence", "TaxReturn", "EstimatedPaymentConfirmation", "PayrollReport", "AccountantWorkpaper", "Other"] as const;
export default async function TaxDocumentsPage({ searchParams }: { searchParams: Promise<{ year?: string }> }) {
  const tenant = await requireTenantContext(); requireTaxCapability(tenant.role, "tax.documents.view");
  const year = yearFrom((await searchParams).year); const data = await getTaxCenterData(tenant.companyId, year);
  return <TaxShell active="/tax/documents" title="Tax Documents" description="Private, tenant-scoped records with audited access and no public URLs." year={year}>
    <details className="glass-card p-5"><summary className="flex min-h-11 cursor-pointer items-center font-semibold text-blue-200">Upload tax document</summary><form action={uploadTaxDocumentAction} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="taxYear" value={year} /><label>Title<input name="title" required className={taxField} /></label><label>Category<select name="category" className={taxField}>{categories.map((x) => <option key={x}>{x}</option>)}</select></label><label className="md:col-span-2">Document<input name="document" type="file" required accept=".pdf,image/jpeg,image/png,image/webp" className={`${taxField} file:mr-3 file:rounded-lg file:border-0 file:bg-orange-500 file:px-3 file:py-2 file:text-slate-950`} /></label><label className="md:col-span-2">Notes<textarea name="notes" className={taxField} /></label><button className="ui-button ui-button--primary min-h-11 rounded-xl px-4 md:w-fit">Upload securely</button></form></details>
    <section className="glass-card mt-5 overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="text-xl font-bold">{year} vault</h2></div><div className="divide-y divide-white/10">{data.documents.map((document) => <article key={document.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><span><strong>{document.title}</strong><small className="block text-slate-400">{document.category} · {document.originalFilename} · {document.reviewStatus}</small></span><div className="flex gap-2"><a href={`/api/tax/documents/${document.id}`} className="ui-button ui-button--secondary inline-flex min-h-11 items-center rounded-xl px-3">Download</a>{document.reviewStatus !== "Reviewed" && <form action={reviewTaxDocumentAction}><input type="hidden" name="documentId" value={document.id} /><button className="ui-button ui-button--primary min-h-11 rounded-xl px-3">Mark reviewed</button></form>}</div></article>)}{!data.documents.length && <p className="p-8 text-center text-slate-400">No tax documents for {year}.</p>}</div></section>
  </TaxShell>;
}
