import{prisma}from"@/lib/prisma";import{plans,type BillingFeature}from"./config";import type{SubscriptionPlan,SubscriptionStatus}from"@/generated/prisma/client";
export class BillingAccessError extends Error{constructor(message:string,public code:"RESTRICTED"|"PLAN_LIMIT"|"FEATURE_UNAVAILABLE"="RESTRICTED"){super(message);this.name="BillingAccessError"}}
export function deriveAccess(subscription:{plan:SubscriptionPlan;status:SubscriptionStatus;trialEnd:Date|null;gracePeriodEnd:Date|null},now=new Date()){const trial=subscription.status==="Trialing"&&Boolean(subscription.trialEnd&&subscription.trialEnd>now);const active=subscription.status==="Active";const grace=subscription.status==="PastDue"&&Boolean(subscription.gracePeriodEnd&&subscription.gracePeriodEnd>now);return{allowed:trial||active||grace,restricted:!(trial||active||grace),reason:trial?"trial":active?"active":grace?"grace":"inactive" as const,trialDaysRemaining:subscription.trialEnd?Math.max(0,Math.ceil((subscription.trialEnd.getTime()-now.getTime())/864e5)):0,graceDaysRemaining:subscription.gracePeriodEnd?Math.max(0,Math.ceil((subscription.gracePeriodEnd.getTime()-now.getTime())/864e5)):0};}
export async function getCompanyEntitlements(companyId:string,now=new Date()){const subscription=await prisma.companySubscription.findUnique({where:{companyId}});if(!subscription)return{companyId,subscription:null,plan:"Starter"as const,config:plans.Starter,...{allowed:false,restricted:true,reason:"inactive"as const,trialDaysRemaining:0,graceDaysRemaining:0}};return{companyId,subscription,plan:subscription.plan,config:plans[subscription.plan],...deriveAccess(subscription,now)};}
export async function canAccessFeature(companyId:string,feature:BillingFeature){const e=await getCompanyEntitlements(companyId);return e.allowed&&e.config.features.includes(feature);}
export async function requireSubscriptionAccess(companyId:string){const e=await getCompanyEntitlements(companyId);if(!e.allowed)throw new BillingAccessError("Your subscription is inactive. Existing records remain available, but creating new records requires an active plan or trial.");return e;}
export async function requireFeature(companyId:string,feature:BillingFeature){const e=await requireSubscriptionAccess(companyId);if(!e.config.features.includes(feature))throw new BillingAccessError(`The ${feature} feature is not included in the ${e.config.name} plan.`,"FEATURE_UNAVAILABLE");return e;}
export async function canCreateEstimate(companyId:string){const e=await requireSubscriptionAccess(companyId);if(e.config.monthlyEstimateLimit===Number.MAX_SAFE_INTEGER)return true;const start=new Date();start.setDate(1);start.setHours(0,0,0,0);const count=await prisma.estimate.count({where:{companyId,createdAt:{gte:start}}});if(count>=e.config.monthlyEstimateLimit)throw new BillingAccessError(`The ${e.config.name} plan limit of ${e.config.monthlyEstimateLimit} estimates per month has been reached.`,"PLAN_LIMIT");return true;}
export async function canInviteUser(companyId:string){const e=await requireSubscriptionAccess(companyId);const count=await prisma.companyMembership.count({where:{companyId,status:"Active"}});if(count>=e.config.userLimit)throw new BillingAccessError(`The ${e.config.name} plan allows ${e.config.userLimit} active user${e.config.userLimit===1?"":"s"}.`,"PLAN_LIMIT");return true;}
export async function requireCrewCapacity(companyId:string){const e=await requireFeature(companyId,"operations");const count=await prisma.crew.count({where:{companyId,active:true}});if(count>=e.config.crewLimit)throw new BillingAccessError(`The ${e.config.name} crew limit has been reached.`,"PLAN_LIMIT");}
export async function requireTruckCapacity(companyId:string){const e=await requireFeature(companyId,"operations");const count=await prisma.fleetAsset.count({where:{companyId,type:"Truck",status:{not:"Retired"}}});if(count>=e.config.truckLimit)throw new BillingAccessError(`The ${e.config.name} truck limit has been reached.`,"PLAN_LIMIT");}
