CREATE TYPE "PaymentProvider" AS ENUM ('Manual','Stripe','Square');
CREATE TYPE "ProviderPaymentStatus" AS ENUM ('Pending','Captured','Failed','Refunded');
CREATE TYPE "FinancialAdjustmentType" AS ENUM ('Credit','WriteOff','Adjustment');
CREATE TYPE "ReconciliationStatus" AS ENUM ('Pending','Matched','Duplicate','FailedCapture','Orphaned','Ignored');
ALTER TABLE "payments" ADD COLUMN "provider" "PaymentProvider" NOT NULL DEFAULT 'Manual', ADD COLUMN "providerStatus" "ProviderPaymentStatus" NOT NULL DEFAULT 'Captured', ADD COLUMN "externalTransactionId" TEXT, ADD COLUMN "idempotencyKey" TEXT, ADD COLUMN "processingFee" DOUBLE PRECISION NOT NULL DEFAULT 0, ADD COLUMN "capturedAt" TIMESTAMP(3), ADD COLUMN "failedAt" TIMESTAMP(3), ADD COLUMN "failureReason" TEXT;
CREATE UNIQUE INDEX "payments_companyId_provider_externalTransactionId_key" ON "payments"("companyId","provider","externalTransactionId");
CREATE UNIQUE INDEX "payments_companyId_idempotencyKey_key" ON "payments"("companyId","idempotencyKey");
CREATE INDEX "payments_companyId_provider_providerStatus_paymentDate_idx" ON "payments"("companyId","provider","providerStatus","paymentDate");
CREATE TABLE "financial_adjustments" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"type" "FinancialAdjustmentType" NOT NULL,"amount" DOUBLE PRECISION NOT NULL,"reason" TEXT NOT NULL,"effectiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "financial_adjustments_pkey" PRIMARY KEY("id"));
CREATE TABLE "payment_reconciliation_runs" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"provider" "PaymentProvider" NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),"matchedCount" INTEGER NOT NULL DEFAULT 0,"exceptionCount" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "payment_reconciliation_runs_pkey" PRIMARY KEY("id"));
CREATE TABLE "payment_reconciliation_items" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"runId" TEXT NOT NULL,"paymentId" TEXT,"externalTransactionId" TEXT NOT NULL,"amount" DOUBLE PRECISION NOT NULL,"occurredAt" TIMESTAMP(3) NOT NULL,"status" "ReconciliationStatus" NOT NULL,"message" TEXT,"raw" JSONB,CONSTRAINT "payment_reconciliation_items_pkey" PRIMARY KEY("id"));
CREATE TABLE "ar_reminder_policies" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"name" TEXT NOT NULL,"daysOffset" INTEGER NOT NULL,"channel" TEXT NOT NULL DEFAULT 'Email',"enabled" BOOLEAN NOT NULL DEFAULT true,"subject" TEXT NOT NULL,"body" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ar_reminder_policies_pkey" PRIMARY KEY("id"));
CREATE INDEX "financial_adjustments_companyId_invoiceId_effectiveAt_idx" ON "financial_adjustments"("companyId","invoiceId","effectiveAt");
CREATE INDEX "payment_reconciliation_runs_companyId_provider_startedAt_idx" ON "payment_reconciliation_runs"("companyId","provider","startedAt");
CREATE UNIQUE INDEX "payment_reconciliation_items_runId_externalTransactionId_key" ON "payment_reconciliation_items"("runId","externalTransactionId");
CREATE INDEX "payment_reconciliation_items_companyId_status_occurredAt_idx" ON "payment_reconciliation_items"("companyId","status","occurredAt");
CREATE UNIQUE INDEX "ar_reminder_policies_companyId_daysOffset_channel_key" ON "ar_reminder_policies"("companyId","daysOffset","channel");
CREATE INDEX "ar_reminder_policies_companyId_enabled_daysOffset_idx" ON "ar_reminder_policies"("companyId","enabled","daysOffset");
ALTER TABLE "financial_adjustments" ADD CONSTRAINT "financial_adjustments_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "financial_adjustments" ADD CONSTRAINT "financial_adjustments_invoiceId_fkey" FOREIGN KEY("invoiceId") REFERENCES "invoices"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "payment_reconciliation_runs" ADD CONSTRAINT "payment_reconciliation_runs_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payment_reconciliation_items" ADD CONSTRAINT "payment_reconciliation_items_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payment_reconciliation_items" ADD CONSTRAINT "payment_reconciliation_items_runId_fkey" FOREIGN KEY("runId") REFERENCES "payment_reconciliation_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payment_reconciliation_items" ADD CONSTRAINT "payment_reconciliation_items_paymentId_fkey" FOREIGN KEY("paymentId") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ar_reminder_policies" ADD CONSTRAINT "ar_reminder_policies_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
