import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";
import { prisma } from "@/lib/prisma";
import { DatabaseJobQueue } from "@/lib/backgroundJobs/databaseQueue";
import { OneShotJobWorker } from "@/lib/backgroundJobs/worker";
import { createTenantFixtures, resetIntegrationDatabase } from "./fixtures";

describe("database background job queue", () => {
  const queue = new DatabaseJobQueue();
  beforeEach(resetIntegrationDatabase);
  afterAll(resetIntegrationDatabase);
  it("enqueues idempotently and records creator audit data", async () => { const { a } = await createTenantFixtures(); const input = { companyId: a.company.id, type: "Future" as const, payload: { value: 1 }, createdByUserId: a.user.id, idempotencyKey: "same" }; const first = await queue.enqueue(input); const second = await queue.enqueue(input); expect(second.id).toBe(first.id); expect(await prisma.backgroundJob.count({ where: { companyId: a.company.id } })).toBe(1); expect(first.createdByUserId).toBe(a.user.id); });
  it("reserves highest priority once and prevents duplicate processing", async () => { const { a } = await createTenantFixtures(); await queue.enqueue({ companyId: a.company.id, type: "Future", payload: {}, priority: "Low" }); const high = await queue.enqueue({ companyId: a.company.id, type: "Future", payload: {}, priority: "Critical" }); expect((await queue.reserve({ companyId: a.company.id }))?.id).toBe(high.id); const second = await queue.reserve({ companyId: a.company.id }); expect(second?.priority).toBe("Low"); expect(await queue.reserve({ companyId: a.company.id })).toBeNull(); });
  it("retries with backoff and reaches terminal failure", async () => { const { a } = await createTenantFixtures(); const pending = await queue.enqueue({ companyId: a.company.id, type: "Future", payload: {}, maxAttempts: 2 }); const now = new Date(Date.now() + 1_000); const running = await queue.reserve({ companyId: a.company.id, now }); const retrying = await queue.fail(a.company.id, running!.id, { error: new Error("first"), now }); expect(retrying.status).toBe("Pending"); expect(retrying.availableAt.getTime()).toBeGreaterThan(now.getTime()); const runningAgain = await queue.reserve({ companyId: a.company.id, now: retrying.availableAt }); const failed = await queue.fail(a.company.id, runningAgain!.id, { error: new Error("second"), now: retrying.availableAt }); expect(failed.status).toBe("Failed"); expect(failed.id).toBe(pending.id); });
  it("supports cancellation, manual retry, and tenant isolation", async () => { const { a, b } = await createTenantFixtures(); const job = await queue.enqueue({ companyId: b.company.id, type: "Future", payload: {} }); await expect(queue.cancel(a.company.id, job.id)).rejects.toThrow("not found"); const cancelled = await queue.cancel(b.company.id, job.id); expect(cancelled.status).toBe("Cancelled"); expect((await queue.retry(b.company.id, job.id)).status).toBe("Pending"); expect(await queue.reserve({ companyId: a.company.id })).toBeNull(); });
  it("recovers stale running jobs", async () => { const { a } = await createTenantFixtures(); const job = await queue.enqueue({ companyId: a.company.id, type: "Future", payload: {} }); await prisma.backgroundJob.update({ where: { id: job.id }, data: { status: "Running", startedAt: new Date("2020-01-01") } }); expect(await queue.recoverStale({ companyId: a.company.id, now: new Date("2026-01-01"), staleAfterMs: 60_000 })).toBe(1); expect(await prisma.backgroundJob.findUnique({ where: { id: job.id } })).toMatchObject({ status: "Pending", startedAt: null }); });
  it("one-shot worker completes an idempotent job once", async () => { const { a } = await createTenantFixtures(); await queue.enqueue({ companyId: a.company.id, type: "Future", payload: {}, idempotencyKey: "worker-once" }); const handler = vi.fn().mockResolvedValue(undefined); const worker = new OneShotJobWorker(queue, { Future: handler }, { log: vi.fn() }); await worker.processOne({ companyId: a.company.id }); await worker.processOne({ companyId: a.company.id }); expect(handler).toHaveBeenCalledOnce(); expect(await prisma.backgroundJob.findFirst({ where: { companyId: a.company.id, idempotencyKey: "worker-once" } })).toMatchObject({ status: "Completed", attempts: 1 }); });
});
