import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { prisma } from "@/lib/prisma";
import { consumePortalMagicLink, revokePortalAccess, upsertPortalAccess } from "@/lib/portal/access";
import { getPortalInvoice, getPortalJob, listPortalPayments } from "@/lib/portal/data";
import { generatePortalToken, hashPortalToken } from "@/lib/portal/tokens";
import { createTenantFixtures, resetIntegrationDatabase } from "./fixtures";
import{createCustomerMessage,requestJobReschedule,respondToPortalEstimate}from"@/lib/portal/workflows";
import{queryEstimateEvents}from"@/lib/estimates/estimateEvents";

describe("customer portal real database", () => {
  beforeEach(resetIntegrationDatabase); afterAll(resetIntegrationDatabase);
  it("isolates access and customer records across tenants", async () => { const {a,b}=await createTenantFixtures();const access=await upsertPortalAccess(a.company.id,a.customer.id,"customer@test.invalid");expect(access.customerId).toBe(a.customer.id);await expect(upsertPortalAccess(a.company.id,b.customer.id,"wrong@test.invalid")).rejects.toThrow("Customer not found");expect(await getPortalInvoice(b.company.id,b.customer.id,a.invoice.id)).toBeNull();expect(await listPortalPayments(b.company.id,b.customer.id)).toHaveLength(1); });
  it("consumes magic links once and rejects expired links",async()=>{const{a}=await createTenantFixtures();const access=await upsertPortalAccess(a.company.id,a.customer.id,"customer@test.invalid");const raw=generatePortalToken();await prisma.customerPortalToken.create({data:{portalAccessId:access.id,tokenHash:hashPortalToken(raw),purpose:"SignIn",expiresAt:new Date(Date.now()+60_000)}});const result=await consumePortalMagicLink(raw);expect(result.rawSession).toBeTruthy();await expect(consumePortalMagicLink(raw)).rejects.toThrow();const expired=generatePortalToken();await prisma.customerPortalToken.create({data:{portalAccessId:access.id,tokenHash:hashPortalToken(expired),purpose:"SignIn",expiresAt:new Date(Date.now()-1)}});await expect(consumePortalMagicLink(expired)).rejects.toThrow("invalid or expired");});
  it("revocation invalidates outstanding tokens and sessions",async()=>{const{a}=await createTenantFixtures();const access=await upsertPortalAccess(a.company.id,a.customer.id,"customer@test.invalid");const raw=generatePortalToken();await prisma.customerPortalToken.create({data:{portalAccessId:access.id,tokenHash:hashPortalToken(raw),purpose:"SignIn",expiresAt:new Date(Date.now()+60_000)}});await revokePortalAccess(a.company.id,access.id);await expect(consumePortalMagicLink(raw)).rejects.toThrow();expect(await prisma.customerPortalAccess.findUnique({where:{id:access.id}})).toMatchObject({status:"Revoked"});});
  it("returns only explicitly customer-visible job photos",async()=>{const{a}=await createTenantFixtures();await prisma.jobPhoto.create({data:{companyId:a.company.id,jobId:a.job.id,category:"After",fileUrl:"/visible.jpg",fileName:"visible.jpg",mimeType:"image/jpeg",fileSize:1,sortOrder:1,customerVisible:true}});const job=await getPortalJob(a.company.id,a.customer.id,a.job.id);expect(job?.photos.map(p=>p.fileUrl)).toEqual(["/visible.jpg"]);});
  it("approves atomically and idempotently while rejecting cross-tenant and expired estimates",async()=>{const{a,b}=await createTenantFixtures();const access=await upsertPortalAccess(a.company.id,a.customer.id,"approve@test.invalid"),identity={companyId:a.company.id,customerId:a.customer.id,portalAccessId:access.id,displayName:"Test Customer"};await prisma.estimate.update({where:{id:a.estimate.id},data:{status:"Sent",approvalTokenExpiresAt:new Date(Date.now()+60_000)}});const input={estimateId:a.estimate.id,response:"approve"as const,customerName:"Test Customer",consentAccepted:true,termsVersion:"portal-v1"};const first=await respondToPortalEstimate(identity,input),second=await respondToPortalEstimate(identity,input);expect(second.id).toBe(first.id);expect(await prisma.portalEstimateResponse.count({where:{estimateId:a.estimate.id}})).toBe(1);await expect(respondToPortalEstimate({...identity,companyId:b.company.id,customerId:b.customer.id},{...input,estimateId:a.estimate.id})).rejects.toThrow("not found");await prisma.estimate.update({where:{id:b.estimate.id},data:{status:"Sent",approvalTokenExpiresAt:new Date(0)}});const bAccess=await upsertPortalAccess(b.company.id,b.customer.id,"expired@test.invalid");await expect(respondToPortalEstimate({companyId:b.company.id,customerId:b.customer.id,portalAccessId:bAccess.id,displayName:"B"},{...input,estimateId:b.estimate.id})).rejects.toThrow("expired")});
  it("rejects stale revisions and preserves a declined estimate with its reason and customer-visible event",async()=>{const{a}=await createTenantFixtures();const access=await upsertPortalAccess(a.company.id,a.customer.id,"decline@test.invalid"),identity={companyId:a.company.id,customerId:a.customer.id,portalAccessId:access.id,displayName:"Test Customer"};await prisma.estimate.update({where:{id:a.estimate.id},data:{status:"Sent",approvalTokenExpiresAt:new Date(Date.now()+60_000)}});const revision=await prisma.estimate.create({data:{companyId:a.company.id,customerId:a.customer.id,propertyId:a.property.id,status:"Sent",revisionRootId:a.estimate.id,revisionNumber:1,approvalTokenExpiresAt:new Date(Date.now()+60_000)}});await expect(respondToPortalEstimate(identity,{estimateId:a.estimate.id,response:"approve",customerName:"Test",consentAccepted:true,termsVersion:"v1"})).rejects.toThrow("current estimate revision");const response=await respondToPortalEstimate(identity,{estimateId:revision.id,response:"decline",customerName:"Test",consentAccepted:false,termsVersion:"v1",declineReason:"Timing"});expect(response.declineReason).toBe("Timing");expect((await queryEstimateEvents(a.company.id,{audience:"customer",customerId:a.customer.id,estimateId:revision.id})).events[0]).toMatchObject({eventType:"Customer Declined",visibility:"Both"})});
  it("creates isolated reschedule requests and customer message threads",async()=>{const{a,b}=await createTenantFixtures();const access=await upsertPortalAccess(a.company.id,a.customer.id,"message@test.invalid"),identity={companyId:a.company.id,customerId:a.customer.id,portalAccessId:access.id,displayName:"Test Customer"};const request=await requestJobReschedule(identity,{jobId:a.job.id,preferredStart:new Date(Date.now()+86400000),reason:"Unavailable"});expect(request.status).toBe("Pending");const thread=await createCustomerMessage(identity,{jobId:a.job.id,subject:"Arrival",body:"Please call first."});expect(thread.messages[0].body).toBe("Please call first.");await expect(createCustomerMessage(identity,{jobId:b.job.id,subject:"Wrong",body:"Hidden"})).rejects.toThrow("not found")});
});
