import{beforeEach,describe,expect,it}from"vitest";
import{prisma}from"@/lib/prisma";
import{queryEstimateEvents,recordEstimateEvent}from"@/lib/estimates/estimateEvents";
import{createTenantFixtures,resetIntegrationDatabase}from"./fixtures";

describe("Estimate Timeline & Activity System v1.0",()=>{
  beforeEach(resetIntegrationDatabase);
  const actor={type:"Employee" as const,id:"user-a",displayName:"John Smith"};
  it("creates one canonical event with activity, audit, notification and attachments",async()=>{const{a}=await createTenantFixtures();const event=await recordEstimateEvent({companyId:a.company.id,estimateId:a.estimate.id,eventType:"Photos Added",category:"Photos",actor,summary:"John added sofa photos",visibility:"Both",metadata:{count:1},attachments:[{referenceType:"Photo",referenceId:"photo-1",displayName:"Sofa"}],notification:{title:"Photos added",body:"New estimate photos are available."}});expect(event.attachments).toHaveLength(1);expect(await prisma.estimateActivityFeedItem.count({where:{estimateId:a.estimate.id,eventType:"Photos Added"}})).toBe(1);expect(await prisma.auditEvent.count({where:{entityId:a.estimate.id,metadata:{path:["eventId"],equals:event.id}}})).toBe(1);expect(await prisma.systemNotification.count({where:{companyId:a.company.id,title:"Photos added"}})).toBe(1)});
  it("orders newest first and cursor-paginates without duplicates",async()=>{const{a}=await createTenantFixtures();const first=await recordEstimateEvent({companyId:a.company.id,estimateId:a.estimate.id,eventType:"Estimate Updated",category:"Estimate",actor,summary:"First",visibility:"Internal"});const second=await recordEstimateEvent({companyId:a.company.id,estimateId:a.estimate.id,eventType:"Notes Updated",category:"Notes",actor,summary:"Second",visibility:"Internal"});await prisma.estimateTimelineEvent.update({where:{id:first.id},data:{timestamp:new Date("2026-01-01")}});await prisma.estimateTimelineEvent.update({where:{id:second.id},data:{timestamp:new Date("2026-01-02")}});const page1=await queryEstimateEvents(a.company.id,{audience:"employee",estimateId:a.estimate.id,limit:1});const page2=await queryEstimateEvents(a.company.id,{audience:"employee",estimateId:a.estimate.id,limit:1,cursor:page1.nextCursor!});expect(page1.events[0].id).toBe(second.id);expect(page2.events[0].id).toBe(first.id);expect(page2.events[0].id).not.toBe(page1.events[0].id)});
  it("filters by user, category, customer, estimate and job and searches event text",async()=>{const{a}=await createTenantFixtures();await recordEstimateEvent({companyId:a.company.id,estimateId:a.estimate.id,eventType:"Crew Assigned",category:"Scheduling",actor,summary:"John assigned the Blue Crew",visibility:"Internal",jobId:"job-search"});const result=await queryEstimateEvents(a.company.id,{audience:"employee",actorId:actor.id,category:"Scheduling",customerId:a.customer.id,estimateId:a.estimate.id,jobId:"job-search",search:"blue crew"});expect(result.events).toHaveLength(1);expect(result.events[0].summary).toContain("Blue Crew")});
  it("enforces customer, employee and platform visibility",async()=>{const{a}=await createTenantFixtures();for(const visibility of["Internal","Customer","Both"]as const)await recordEstimateEvent({companyId:a.company.id,estimateId:a.estimate.id,eventType:"Estimate Updated",category:"Estimate",actor,summary:visibility,visibility});expect((await queryEstimateEvents(a.company.id,{audience:"employee"})).events.map(e=>e.visibility)).toEqual(expect.arrayContaining(["Internal","Both"]));expect((await queryEstimateEvents(a.company.id,{audience:"customer"})).events.map(e=>e.visibility).sort()).toEqual(["Both","Customer"]);expect((await queryEstimateEvents(a.company.id,{audience:"platformAdmin"})).events).toHaveLength(3)});
  it("eager-loads attachments and related estimate context in the page query",async()=>{const{a}=await createTenantFixtures();await recordEstimateEvent({companyId:a.company.id,estimateId:a.estimate.id,eventType:"Invoice Generated",category:"Invoice",actor,summary:"Invoice generated",attachments:[{referenceType:"Invoice",referenceId:"invoice-1",displayName:"INV-1"}]});const page=await queryEstimateEvents(a.company.id,{audience:"employee"});expect(page.events[0]).toMatchObject({estimate:{customer:{firstName:a.customer.firstName}},attachments:[{referenceId:"invoice-1"}]})});
});
