import {beforeEach,describe,expect,it} from "vitest";
import {prisma} from "@/lib/prisma";
import {createTenantFixtures,resetIntegrationDatabase} from "./fixtures";
import {transitionEstimate} from "@/lib/estimates/estimateLifecycle";
import {saveEstimateProgress} from "@/lib/estimates/saveEstimateProgress";
import {deleteEstimate} from "@/lib/estimates/deleteEstimate";
import {getEstimateLifecycleDashboardCounts} from "@/lib/estimates/dashboardCounts";

describe("Estimate Lifecycle v1.0",()=>{
  beforeEach(resetIntegrationDatabase);
  const progress=(estimateId:string,total=123)=>({estimateId,currentStep:2,pricingSubtotal:total,pricingLabor:0,pricingDisposal:0,pricingDiscount:0,pricingTotal:total,estimatedLaborHours:null,estimatedLaborCost:null});
  it("persists a valid transition through timeline, audit, activity and centralized notification, and clearly rejects an invalid transition",async()=>{const{a}=await createTenantFixtures();const draft=await prisma.estimate.create({data:{companyId:a.company.id,customerId:a.customer.id,propertyId:a.property.id,status:"Draft"}});await transitionEstimate(a.company.id,draft.id,"Sent",{actor:{label:"Owner A",userId:a.user.id}});expect((await prisma.estimate.findUniqueOrThrow({where:{id:draft.id}})).status).toBe("Sent");expect(await prisma.estimateTimelineEvent.count({where:{estimateId:draft.id,eventType:"Estimate Sent"}})).toBe(1);expect(await prisma.estimateActivityFeedItem.count({where:{estimateId:draft.id,message:"Owner A sent estimate"}})).toBe(1);expect(await prisma.auditEvent.count({where:{companyId:a.company.id,entityId:draft.id,eventType:"estimate.sent"}})).toBe(1);expect(await prisma.systemNotification.count({where:{companyId:a.company.id,title:"Estimate Sent"}})).toBe(1);await expect(transitionEstimate(a.company.id,draft.id,"Paid")).rejects.toThrow("cannot move from Sent to Paid")});
  it("enforces editable and read-only states at the persistence boundary",async()=>{const{a}=await createTenantFixtures();for(const status of ["Draft","Sent","Viewed","Declined","Expired"] as const){const row=await prisma.estimate.create({data:{companyId:a.company.id,customerId:a.customer.id,propertyId:a.property.id,status}});await expect(saveEstimateProgress(a.company.id,progress(row.id))).resolves.toBeUndefined()}for(const status of ["Approved","Scheduled","InProgress","Completed","Invoiced","Paid","Canceled"] as const){const row=await prisma.estimate.create({data:{companyId:a.company.id,customerId:a.customer.id,propertyId:a.property.id,status}});await expect(saveEstimateProgress(a.company.id,progress(row.id))).rejects.toThrow("read-only")}});
  it("allows only lifecycle-approved deletions and returns a clear block message",async()=>{const{a}=await createTenantFixtures();for(const status of ["Draft","Sent","Viewed","Declined","Expired"] as const){const row=await prisma.estimate.create({data:{companyId:a.company.id,customerId:a.customer.id,propertyId:a.property.id,status}});await deleteEstimate(a.company.id,row.id);expect(await prisma.estimate.findUnique({where:{id:row.id}})).toBeNull()}const blocked=await prisma.estimate.create({data:{companyId:a.company.id,customerId:a.customer.id,propertyId:a.property.id,status:"Approved"}});await expect(deleteEstimate(a.company.id,blocked.id)).rejects.toThrow("cannot be deleted")});
  it("computes dashboard lifecycle cards from authoritative states and events",async()=>{const{a}=await createTenantFixtures();for(const status of ["Draft","Draft","Sent","Viewed","Scheduled","InProgress","Invoiced"] as const)await prisma.estimate.create({data:{companyId:a.company.id,customerId:a.customer.id,propertyId:a.property.id,status}});await prisma.estimateTimelineEvent.createMany({data:[{companyId:a.company.id,estimateId:a.estimate.id,eventType:"Job Completed",actor:"Crew"},{companyId:a.company.id,estimateId:a.estimate.id,eventType:"Invoice Paid",actor:"Owner"}]});expect(await getEstimateLifecycleDashboardCounts(a.company.id)).toMatchObject({draftEstimates:2,awaitingApproval:2,approved:1,scheduled:1,inProgress:1,completedToday:1,invoicesAwaitingPayment:1,paidThisMonth:1})});
});
