import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { prisma } from "@/lib/prisma";
import { createTenantFixtures, resetIntegrationDatabase } from "./fixtures";
import { recordRefund } from "@/lib/payments/refunds";
import { deletePayment } from "@/lib/payments/paymentMutations";
import { rebuildPricingOutcomes, syncPricingOutcomeForJob } from "@/lib/smartPricing/outcomes";
import { getSmartPricingAccuracy, getSmartPricingFilterOptions } from "@/lib/smartPricing/analytics";

describe("Smart Pricing completion-pass integration", () => {
  beforeEach(resetIntegrationDatabase); afterAll(resetIntegrationDatabase);
  async function completeFixture() { const fixtures = await createTenantFixtures(); const { a } = fixtures; await prisma.property.update({ where: { id: a.property.id }, data: { propertyType: "house" } }); await prisma.estimate.update({ where: { id: a.estimate.id }, data: { estimatedLaborHours: 2.5, estimatedLaborCost: 80, pricingLabor: 80, pricingDisposal: 20 } }); await prisma.job.update({ where: { id: a.job.id }, data: { status: "Completed", actualLaborHours: 3, actualLaborCost: 90, actualDisposalCost: 25, actualTravelCost: 10, otherActualCost: 0 } }); return fixtures; }
  it("subtracts durable refunds and keeps outcome synchronization idempotent", async () => { const { a } = await completeFixture(); await recordRefund(a.company.id, a.payment.id, { amount: 3, refundedAt: new Date(), createdByUserId: a.user.id }); await recordRefund(a.company.id, a.payment.id, { amount: 2, refundedAt: new Date(), createdByUserId: a.user.id }); await expect(deletePayment(a.company.id, a.payment.id)).rejects.toThrow("durable refunds"); expect(await prisma.refund.count({ where: { paymentId: a.payment.id } })).toBe(2); await syncPricingOutcomeForJob(a.company.id, a.job.id); await syncPricingOutcomeForJob(a.company.id, a.job.id); const outcomes = await prisma.pricingOutcome.findMany({ where: { companyId: a.company.id, jobId: a.job.id } }); expect(outcomes).toHaveLength(1); expect(outcomes[0]).toMatchObject({ collectedAmount: 20, refundAmount: 5, laborHoursEstimated: 2.5, laborCostEstimated: 80, propertyType: "house" }); });
  it("rebuilds without duplicates and leaves decision snapshots immutable", async () => { const { a } = await completeFixture(); const decision = await prisma.smartPricingDecision.create({ data: { companyId: a.company.id, estimateId: a.estimate.id, recommendedPrice: 110, confidenceScore: 75, historicalSampleSize: 10, manualPrice: 100, decision: "Ignored", finalQuotedAmount: 100, difference: -10, decidedAt: new Date(), actingUserId: a.user.id } }); const first = await rebuildPricingOutcomes(a.company.id); const second = await rebuildPricingOutcomes(a.company.id); expect(first.processed).toBe(1); expect(second.processed).toBe(1); expect(await prisma.pricingOutcome.count({ where: { companyId: a.company.id } })).toBe(1); expect(Array.isArray(second.incomplete)).toBe(true); expect(await prisma.smartPricingDecision.findUnique({ where: { id: decision.id } })).toMatchObject({ decision: "Ignored", difference: -10, historicalSampleSize: 10 }); });
  it("tenant-scopes dashboard options and combined filters", async () => { const { a, b } = await completeFixture(); await prisma.jobAssignment.create({ data: { companyId: a.company.id, jobId: a.job.id, crewId: a.crew.id } }); const site = await prisma.jobSite.create({ data: { estimateId: a.estimate.id, name: "Garage", sortOrder: 0 } }); await prisma.estimateItem.create({ data: { jobSiteId: site.id, itemId: "test-item", name: "Sofa", category: "Furniture", sortOrder: 0 } }); await prisma.smartPricingDecision.create({ data: { companyId: a.company.id, estimateId: a.estimate.id, recommendedPrice: 100, confidenceScore: 70, historicalSampleSize: 5, manualPrice: 100, actingUserId: a.user.id } }); await syncPricingOutcomeForJob(a.company.id, a.job.id); const options = await getSmartPricingFilterOptions(a.company.id); expect(options.crews.map((row) => row.id)).toContain(a.crew.id); expect(options.crews.map((row) => row.id)).not.toContain(b.crew.id); const result = await getSmartPricingAccuracy(a.company.id, { propertyType: "house", crewId: a.crew.id, estimatorId: a.user.id, category: "Furniture", from: new Date(Date.now() - 86400000), to: new Date(Date.now() + 86400000) }); expect(result.sampleSize).toBe(1); await expect(getSmartPricingAccuracy(a.company.id, { crewId: b.crew.id })).rejects.toThrow("not available"); });
});
