"use client";

import { Archive, Copy, Download, MoreHorizontal, Plus, RotateCcw, Trash2, Upload } from "lucide-react";
import { useState } from "react";
import {
  bulkUpdateItemLibraryAction, createItemLibraryItemAction, deleteItemLibraryItemAction,
  duplicateItemLibraryItemAction, exportItemLibraryAction, importItemLibraryAction,
  listItemLibraryAction, previewItemImportAction, setItemLibraryActiveAction,
  updateItemLibraryItemAction, upsertItemOverrideAction, applyStandardLibraryAction,
  previewStandardLibraryAction,
} from "@/app/actions/itemLibrary/itemLibrary";
import type { ItemLibrary, PricingProfile } from "@/generated/prisma/client";
import { STANDARD_ITEM_CATEGORIES, WEIGHT_CLASSES, type BulkItemUpdate, type ItemLibraryInput, type ItemLibraryQuery } from "@/lib/itemLibrary/types";

type Row = ItemLibrary & { _count: { estimateItems: number } };
type Data = { items: Row[]; total: number; page: number; pageSize: number; pageCount: number; categories: string[] };
const empty: ItemLibraryInput = {
  category: "Miscellaneous", name: "", description: "", active: true, displayOrder: 0,
  basePrice: 0, disposalFee: 0, laborHours: .25, weightClass: "Medium", estimatedVolume: 0,
  recyclable: false, donationEligible: false, hazardous: false, refrigerant: false,
  electronics: false, mattress: false, tire: false, appliance: false,
  constructionDebris: false, yardWaste: false, requiresTwoPeople: false,
  requiresDisassembly: false, requiresSpecialEquipment: false, estimateRequired: false, notes: "",
};

export default function ItemLibraryManagement({ initialData, profiles, canManage }: { initialData: Data; profiles: PricingProfile[]; canManage: boolean }) {
  const [data, setData] = useState(initialData), [query, setQuery] = useState<ItemLibraryQuery>({ active: true, page: 1, pageSize: initialData.pageSize });
  const [selected, setSelected] = useState<string[]>([]), [editing, setEditing] = useState<Row | "new" | null>(null);
  const [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [showImport, setShowImport] = useState(false);
  const [standardPlan,setStandardPlan]=useState<{updated:number;created:number;archived:number;total:number}|null>(null);
  const [preserveOverrides,setPreserveOverrides]=useState(true);
  async function load(next: ItemLibraryQuery) { setBusy(true); setError(""); try { setData(await listItemLibraryAction(next)); setQuery(next); setSelected([]); } catch (reason) { setError(msg(reason)); } finally { setBusy(false); } }
  async function run(operation: () => Promise<unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { await operation(); setMessage(success); await load(query); } catch (reason) { setError(msg(reason)); } finally { setBusy(false); } }
  async function download() { const csv = await exportItemLibraryAction(), url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })), anchor = document.createElement("a"); anchor.href = url; anchor.download = "item-library.csv"; anchor.click(); URL.revokeObjectURL(url); }
  return <main className="mx-auto max-w-7xl p-4 sm:p-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Item Library</h1><p className="mt-1 text-slate-600 dark:text-slate-300">Company-owned item pricing and removal requirements.</p></div><div className="flex flex-wrap gap-2"><button className={secondary} onClick={() => void download()}><Download size={18} /> Export CSV</button>{canManage && <><button className={secondary} onClick={() => setShowImport(true)}><Upload size={18} /> Import CSV</button><button className={secondary} onClick={() => { const category = window.prompt("Category to update"); if (!category) return; const percent = window.prompt(`Price percentage change for ${category}`); if (percent !== null) void run(() => bulkUpdateItemLibraryAction({ category, pricePercent: Number(percent) }), `${category} prices updated.`); }}>Category pricing</button><button className={secondary} onClick={() => { const category = window.prompt("Category to archive"); if (category && window.confirm(`Archive every active item in ${category}?`)) void run(() => bulkUpdateItemLibraryAction({ category, active: false }), `${category} archived.`); }}>Archive category</button><button className={secondary} disabled={busy} onClick={() => {setBusy(true);setError("");void previewStandardLibraryAction().then(setStandardPlan).catch(reason=>setError(msg(reason))).finally(()=>setBusy(false));}}><RotateCcw size={18}/> Apply JunkQuote Standard Library</button><button className={primary} onClick={() => setEditing("new")}><Plus size={18} /> New Item</button></>}</div></header>
    <section className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950 dark:border-blue-900 dark:bg-blue-950 dark:text-blue-100"><h2 className="font-semibold">JunkQuote Standard Library philosophy</h2><p className="mt-1">Base prices are intentionally conservative. Pricing Rules, labor, disposal, distance, and other modifiers produce the final quote. Items marked Estimate Required must be reviewed before pricing.</p></section>
    {standardPlan&&<section role="dialog" aria-labelledby="apply-standard-title" className="mt-5 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-950 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100"><h2 id="apply-standard-title" className="text-lg font-semibold">Apply JunkQuote Standard Library</h2><p className="mt-1 text-sm">This replaces current active library values while preserving historical estimate snapshots and all non-library business records.</p><dl className="mt-4 grid grid-cols-3 gap-3 text-center"><Metric label="Updated" value={String(standardPlan.updated)}/><Metric label="Created" value={String(standardPlan.created)}/><Metric label="Archived" value={String(standardPlan.archived)}/></dl><label className="mt-4 flex min-h-11 items-center gap-2"><input type="checkbox" checked={preserveOverrides} onChange={event=>setPreserveOverrides(event.target.checked)}/>Preserve Pricing Profile overrides</label><div className="mt-3 flex flex-wrap gap-2"><button className={primary} disabled={busy} onClick={()=>{if(!window.confirm(`Apply JunkQuote Standard Library? ${standardPlan.updated} items will be updated, ${standardPlan.created} created, and ${standardPlan.archived} archived.`))return;void run(()=>applyStandardLibraryAction(!preserveOverrides),"JunkQuote Standard Library applied.").then(()=>setStandardPlan(null));}}>Confirm and apply</button><button className={secondary} disabled={busy} onClick={()=>setStandardPlan(null)}>Cancel</button></div></section>}
    {!canManage && <p className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">The Item Library is read only for your role.</p>}
    {error && <p role="alert" className="mt-4 rounded-xl border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}{message && <p role="status" className="mt-4 rounded-xl border border-green-300 bg-green-50 p-3 text-green-800">{message}</p>}
    {showImport && <CsvImport onClose={() => setShowImport(false)} onImported={() => { setShowImport(false); void load(query); }} />}
    {editing && <ItemForm item={editing === "new" ? undefined : editing} onCancel={() => setEditing(null)} onSaved={() => { setEditing(null); void load(query); }} />}
    <section className="mt-6 grid gap-3 rounded-2xl border border-[var(--border-color)] bg-[var(--surface)] p-4 sm:grid-cols-2 lg:grid-cols-5">
      <input aria-label="Search item library" placeholder="Search items…" className={control} value={query.search ?? ""} onChange={(event) => setQuery((current) => ({ ...current, search: event.target.value }))} onKeyDown={(event) => { if (event.key === "Enter") void load({ ...query, page: 1 }); }} />
      <select aria-label="Category filter" className={control} value={query.category ?? ""} onChange={(event) => void load({ ...query, category: event.target.value || undefined, page: 1 })}><option value="">All categories</option>{data.categories.map((category) => <option key={category}>{category}</option>)}</select>
      <select aria-label="Status filter" className={control} value={query.active === undefined ? "all" : String(query.active)} onChange={(event) => void load({ ...query, active: event.target.value === "all" ? undefined : event.target.value === "true", page: 1 })}><option value="true">Active</option><option value="false">Archived</option><option value="all">All statuses</option></select>
      <select aria-label="Sort items" className={control} value={query.sort ?? "displayOrder"} onChange={(event) => void load({ ...query, sort: event.target.value as ItemLibraryQuery["sort"], page: 1 })}><option value="displayOrder">Display order</option><option value="name">Name</option><option value="category">Category</option><option value="price">Price</option></select>
      <button className={secondary} disabled={busy} onClick={() => void load({ ...query, page: 1 })}>Search</button>
    </section>
    {canManage && selected.length > 0 && <BulkPanel count={selected.length} categories={data.categories} disabled={busy} onApply={(update) => run(() => bulkUpdateItemLibraryAction({ ...update, ids: selected }), "Selected items updated.")} onArchive={(active) => run(() => setItemLibraryActiveAction(selected, active), active ? "Items restored." : "Items archived.")} />}
    <div className="mt-6 hidden overflow-visible rounded-2xl border border-[var(--border-color)] bg-[var(--surface)] md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 dark:bg-slate-900"><tr><th className="p-3">{canManage && <input aria-label="Select page" type="checkbox" checked={selected.length === data.items.length && data.items.length > 0} onChange={(event) => setSelected(event.target.checked ? data.items.map((item) => item.id) : [])} />}</th>{["Item", "Category", "Base price", "Disposal", "Labor", "Crew", "Status", ""].map((label) => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{data.items.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="p-3">{canManage && <input aria-label={`Select ${item.name}`} type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} />}</td><td className="p-3"><strong>{item.name}</strong><p className="max-w-52 truncate text-xs text-slate-500">{item.description || "No description"}</p></td><td className="p-3">{item.category}</td><td className="p-3">{item.estimateRequired?<span className="font-semibold text-amber-700 dark:text-amber-300">Estimate Required</span>:money(item.basePrice)}</td><td className="p-3">{money(item.disposalFee)}</td><td className="p-3">{item.laborHours} hr</td><td className="p-3">{item.requiresTwoPeople ? "2+" : "1+"}</td><td className="p-3">{item.active ? "Active" : "Archived"}</td><td className="p-3">{canManage && <Actions item={item} profiles={profiles} disabled={busy} onEdit={() => setEditing(item)} run={run} />}</td></tr>)}</tbody></table></div>
    <div className="mt-6 grid gap-4 md:hidden">{data.items.map((item) => <article className="rounded-2xl border border-[var(--border-color)] bg-[var(--surface)] p-4" key={item.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{item.name}</h2><p className="text-sm text-slate-500">{item.category}</p></div>{canManage && <input aria-label={`Select ${item.name}`} type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} />}</div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="Base price" value={item.estimateRequired?"Estimate Required":money(item.basePrice)} /><Metric label="Disposal" value={money(item.disposalFee)} /><Metric label="Labor" value={`${item.laborHours} hr`} /><Metric label="Crew" value={item.requiresTwoPeople ? "2+" : "1+"} /><Metric label="Status" value={item.active ? "Active" : "Archived"} /><Metric label="Used" value={String(item._count.estimateItems)} /></dl>{canManage && <div className="mt-4"><Actions item={item} profiles={profiles} disabled={busy} onEdit={() => setEditing(item)} run={run} /></div>}</article>)}</div>
    {!data.items.length && <p className="mt-6 rounded-2xl border border-dashed p-10 text-center text-slate-500">No matching library items.</p>}
    <nav aria-label="Item library pages" className="mt-6 flex min-h-11 items-center justify-between"><button className={secondary} disabled={data.page <= 1 || busy} onClick={() => void load({ ...query, page: data.page - 1 })}>Previous</button><span className="text-sm">Page {data.page} of {data.pageCount} · {data.total} items</span><button className={secondary} disabled={data.page >= data.pageCount || busy} onClick={() => void load({ ...query, page: data.page + 1 })}>Next</button></nav>
  </main>;
}

function ItemForm({ item, onCancel, onSaved }: { item?: Row; onCancel: () => void; onSaved: () => void }) {
  const [value, setValue] = useState<ItemLibraryInput>(item ? { ...item, weightClass: item.weightClass as ItemLibraryInput["weightClass"] } : empty), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const set = <K extends keyof ItemLibraryInput>(key: K, next: ItemLibraryInput[K]) => setValue((current) => ({ ...current, [key]: next }));
  async function save() { setSaving(true); setError(""); try { if (item) await updateItemLibraryItemAction(item.id, value); else await createItemLibraryItemAction(value); onSaved(); } catch (reason) { setError(msg(reason)); } finally { setSaving(false); } }
  return <section className="mt-6 rounded-2xl border border-[var(--border-color)] bg-[var(--surface)] p-4 sm:p-6"><h2 className="text-xl font-semibold">{item ? "Edit Item" : "Create Item"}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Text label="Name" value={value.name} onChange={(next) => set("name", next)} /><Text label="Category" value={value.category} list="item-categories" onChange={(next) => set("category", next)} /><datalist id="item-categories">{STANDARD_ITEM_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</datalist><Text label="Description" value={value.description ?? ""} onChange={(next) => set("description", next)} /><NumField label="Base price" value={value.basePrice} onChange={(next) => set("basePrice", next)} /><NumField label="Disposal fee" value={value.disposalFee} onChange={(next) => set("disposalFee", next)} /><NumField label="Labor hours" value={value.laborHours} min={.01} onChange={(next) => set("laborHours", next)} /><NumField label="Estimated volume" value={value.estimatedVolume} onChange={(next) => set("estimatedVolume", next)} /><label className="grid gap-1 text-sm font-medium">Weight class<select className={control} value={value.weightClass} onChange={(event) => set("weightClass", event.target.value as ItemLibraryInput["weightClass"])}>{WEIGHT_CLASSES.map((weight) => <option key={weight}>{weight}</option>)}</select></label><NumField label="Display order" value={value.displayOrder} step={1} onChange={(next) => set("displayOrder", next)} />{flagFields.map(([key, label]) => <label className="flex min-h-11 items-center gap-2 text-sm" key={key}><input type="checkbox" checked={Boolean(value[key])} onChange={(event) => set(key, event.target.checked)} />{label}</label>)}</div>{error && <p role="alert" className="mt-4 text-red-700">{error}</p>}<div className="mt-5 flex gap-3"><button className={primary} disabled={saving} onClick={() => void save()}>{saving ? "Saving…" : "Save Item"}</button><button className={secondary} disabled={saving} onClick={onCancel}>Cancel</button></div></section>;
}
const flagFields = [["recyclable", "Recyclable"], ["donationEligible", "Donation eligible"], ["hazardous", "Hazardous"], ["refrigerant", "Refrigerant"], ["electronics", "Electronics"], ["mattress", "Mattress"], ["tire", "Tire"], ["appliance", "Appliance"], ["constructionDebris", "Construction debris"], ["yardWaste", "Yard waste"], ["requiresTwoPeople", "Requires two people"], ["requiresDisassembly", "Requires disassembly"], ["requiresSpecialEquipment", "Special equipment"], ["estimateRequired", "Estimate Required"]] as const;

function Actions({ item, profiles, disabled, onEdit, run }: { item: Row; profiles: PricingProfile[]; disabled: boolean; onEdit: () => void; run: (operation: () => Promise<unknown>, success: string) => Promise<void> }) {
  return <details className="relative"><summary aria-label={`Actions for ${item.name}`} className="inline-flex min-h-11 min-w-11 cursor-pointer list-none items-center justify-center rounded-lg border focus-visible:ring-2"><MoreHorizontal /></summary><div className="absolute right-0 z-30 mt-1 grid min-w-56 rounded-xl border bg-white p-1 text-slate-950 shadow-xl">{item.active && <Action label="Edit" onClick={onEdit} disabled={disabled} />}<Action label="Duplicate" icon={Copy} onClick={() => void run(() => duplicateItemLibraryItemAction(item.id), "Item duplicated.")} disabled={disabled} /><Action label={item.active ? "Archive" : "Restore"} icon={item.active ? Archive : RotateCcw} onClick={() => void run(() => setItemLibraryActiveAction([item.id], !item.active), item.active ? "Item archived." : "Item restored.")} disabled={disabled} />{profiles.map((profile) => <Override key={profile.id} item={item} profile={profile} disabled={disabled} run={run} />)}{!item.active && <Action label="Delete" icon={Trash2} destructive disabled={disabled} onClick={() => { if (window.confirm(`Delete "${item.name}"?`)) void run(() => deleteItemLibraryItemAction(item.id), "Item deleted."); }} />}</div></details>;
}
function Override({ item, profile, disabled, run }: { item: Row; profile: PricingProfile; disabled: boolean; run: ActionsProps["run"] }) {
  return <button className="min-h-11 rounded-lg px-3 text-left text-sm hover:bg-slate-100" disabled={disabled} onClick={() => {
    const price = window.prompt(`${profile.name} base price. Blank inherits ${money(item.basePrice)}.`);
    if (price === null) return;
    const disposal = window.prompt(`${profile.name} disposal fee. Blank inherits ${money(item.disposalFee)}.`);
    if (disposal === null) return;
    const labor = window.prompt(`${profile.name} labor hours. Blank inherits ${item.laborHours}.`);
    if (labor === null) return;
    const crew = window.prompt(`${profile.name} crew requirement. Blank inherits ${item.requiresTwoPeople ? 2 : 1}.`);
    if (crew === null) return;
    const optionalNumber = (raw: string) => raw.trim() === "" ? null : Number(raw);
    void run(() => upsertItemOverrideAction(profile.id, item.id, {
      basePrice: optionalNumber(price), disposalFee: optionalNumber(disposal),
      laborHours: optionalNumber(labor), crewRequirement: optionalNumber(crew),
    }), `${profile.name} override saved.`);
  }}>Set {profile.name} override</button>;
}
type ActionsProps = { run: (operation: () => Promise<unknown>, success: string) => Promise<void> };
function BulkPanel({ count, categories, disabled, onApply, onArchive }: { count: number; categories: string[]; disabled: boolean; onApply: (update: BulkItemUpdate) => Promise<void>; onArchive: (active: boolean) => Promise<void> }) {
  return <section className="mt-4 flex flex-wrap items-center gap-2 rounded-xl border border-blue-300 bg-blue-50 p-3 text-slate-950"><strong>{count} selected</strong><button className={secondary} disabled={disabled} onClick={() => { const value = window.prompt("Increase prices by percent"); if (value) void onApply({ pricePercent: Number(value) }); }}>Price %</button><button className={secondary} disabled={disabled} onClick={() => { const value = window.prompt("Labor hours"); if (value) void onApply({ laborHours: Number(value) }); }}>Labor</button><button className={secondary} disabled={disabled} onClick={() => { const value = window.prompt("Disposal fee"); if (value) void onApply({ disposalFee: Number(value) }); }}>Disposal</button><select aria-label="Move selected category" className={control} defaultValue="" onChange={(event) => { if (event.target.value) void onApply({ moveCategory: event.target.value }); }}><option value="">Move category…</option>{categories.map((category) => <option key={category}>{category}</option>)}</select><button className={secondary} disabled={disabled} onClick={() => void onApply({ recyclable: true })}>Mark recyclable</button><button className={secondary} disabled={disabled} onClick={() => void onArchive(false)}>Archive</button><button className={secondary} disabled={disabled} onClick={() => void onArchive(true)}>Restore</button></section>;
}
function CsvImport({ onClose, onImported }: { onClose: () => void; onImported: () => void }) {
  const [csv, setCsv] = useState(""), [preview, setPreview] = useState<{ items: ItemLibraryInput[]; errors: string[] } | null>(null), [busy, setBusy] = useState(false);
  async function inspect() { setBusy(true); try { setPreview(await previewItemImportAction(csv)); } finally { setBusy(false); } }
  async function commit() { setBusy(true); try { await importItemLibraryAction(csv); onImported(); } finally { setBusy(false); } }
  return <section className="mt-6 rounded-2xl border p-4"><h2 className="text-xl font-semibold">Import Item Library CSV</h2><input aria-label="Choose CSV file" className={`${control} mt-3`} type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) void file.text().then(setCsv); }} /><textarea aria-label="CSV contents" value={csv} onChange={(event) => setCsv(event.target.value)} className={`${control} mt-3 min-h-32`} placeholder="Paste CSV contents for preview" />{preview && <div className="mt-3"><p role="status">{preview.items.length} valid items ready.</p>{preview.errors.map((error) => <p role="alert" className="text-red-700" key={error}>{error}</p>)}</div>}<div className="mt-3 flex gap-2"><button className={secondary} disabled={busy || !csv} onClick={() => void inspect()}>Preview</button><button className={primary} disabled={busy || !preview || preview.errors.length > 0 || preview.items.length === 0} onClick={() => void commit()}>Import</button><button className={secondary} onClick={onClose}>Cancel</button></div></section>;
}
function Action({ label, onClick, disabled, destructive, icon: Icon }: { label: string; onClick: () => void; disabled: boolean; destructive?: boolean; icon?: typeof Copy }) { return <button className={`flex min-h-11 items-center gap-2 rounded-lg px-3 text-left text-sm hover:bg-slate-100 ${destructive ? "text-red-700" : ""}`} disabled={disabled} onClick={onClick}>{Icon && <Icon size={16} />}{label}</button>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="font-medium">{value}</dd></div>; }
function Text({ label, value, onChange, list }: { label: string; value: string; onChange: (value: string) => void; list?: string }) { return <label className="grid gap-1 text-sm font-medium">{label}<input className={control} required value={value} list={list} onChange={(event) => onChange(event.target.value)} /></label>; }
function NumField({ label, value, onChange, min = 0, step = .01 }: { label: string; value: number; onChange: (value: number) => void; min?: number; step?: number }) { return <label className="grid gap-1 text-sm font-medium">{label}<input className={control} type="number" min={min} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
const control = "min-h-11 rounded-xl border border-[var(--border-color)] bg-[var(--surface)] px-3";
const primary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 font-semibold text-white disabled:opacity-50 focus-visible:ring-2";
const secondary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border px-3 font-semibold disabled:opacity-50 focus-visible:ring-2";
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
const msg = (reason: unknown) => reason instanceof Error ? reason.message : "Item Library operation failed.";
