import Link from "next/link";
import AppLayout from "@/components/layout/AppLayout";
import { requireCompanyRole } from "@/lib/auth/tenant";
import { getCommunicationCenter, type CommunicationCenterFilters } from "@/lib/communications/center";
import { ensureDefaultCommunicationConfiguration } from "@/lib/communications/engine";
import {
  manualSendCommunicationAction, markAllNotificationsReadAction, markNotificationReadAction,
  retryCommunicationAction, saveCommunicationPreferencesAction, saveCommunicationTemplateAction,
  toggleCommunicationRuleAction,
} from "@/app/actions/communications/communications";

const button="inline-flex min-h-11 items-center justify-center rounded-xl border border-[var(--border-color)] px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600";
const views=["activity","scheduled","failed","templates","automation","preferences","notifications"] as const;

export default async function CommunicationsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  const context=await requireCompanyRole("Owner","Admin","Office","Crew");
  const query=await searchParams;
  const requested=views.includes(query.view as typeof views[number])?query.view as typeof views[number]:"activity";
  const view=context.role==="Crew"?"notifications":requested;
  if(["Owner","Admin"].includes(context.role))await ensureDefaultCommunicationConfiguration(context.companyId);
  const data=await getCommunicationCenter(context.companyId,context.user.id,context.role,{view,eventType:query.eventType,channel:query.channel,status:query.status,customerId:query.customerId,sourceId:query.sourceId,page:Number(query.page)||1});
  return <AppLayout><main className="mx-auto max-w-7xl p-4 sm:p-6">
    <header><p className="font-semibold text-blue-700 dark:text-blue-300">Customer Communication Engine</p><h1 className="text-3xl font-bold">Communications</h1><p className="mt-1 text-slate-600 dark:text-slate-300">Auditable messages, scheduled delivery, templates, and internal notifications.</p></header>
    <nav aria-label="Communication views" className="mt-5 flex gap-2 overflow-x-auto pb-2">{views.filter((item)=>data.management||!["templates","automation","preferences"].includes(item)).map((item)=><Link key={item} href={`/communications?view=${item}`} aria-current={view===item?"page":undefined} className={`${button} whitespace-nowrap ${view===item?"bg-blue-700 text-white":""}`}>{title(item)}{item==="notifications"&&data.unreadCount>0?` (${data.unreadCount})`:""}</Link>)}</nav>
    {["activity","scheduled","failed"].includes(view)&&<Activity data={data} view={view} manual={{customerId:query.customerId,sourceType:query.sourceType,sourceId:query.sourceId}}/>}
    {view==="templates"&&data.management&&<Templates data={data}/>}
    {view==="automation"&&data.management&&<Automation data={data}/>}
    {view==="preferences"&&data.management&&<Preferences data={data}/>}
    {view==="notifications"&&<Notifications data={data}/>}
  </main></AppLayout>;
}

function Activity({data,view,manual}:{data:Awaited<ReturnType<typeof getCommunicationCenter>>;view:string;manual:{customerId?:string;sourceType?:string;sourceId?:string}}) {
  return <section className="mt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">{title(view)} deliveries</h2><p className="text-sm">{data.total} matching records</p></div><details open={Boolean(manual.customerId)}><summary className={`${button} cursor-pointer list-none`}>Manual email</summary><form action={manualSendCommunicationAction} className="mt-2 grid min-w-80 gap-3 rounded-xl border bg-[var(--surface)] p-4"><input type="hidden" name="sourceType" value={manual.sourceType??"Customer"}/><input type="hidden" name="sourceId" value={manual.sourceId??manual.customerId??""}/><label>Customer<select required name="customerId" defaultValue={manual.customerId??""} className="mt-1 min-h-11 w-full rounded-xl border bg-[var(--surface)] px-3"><option value="">Select customer</option>{data.customers.map((row)=><option key={row.id} value={row.id}>{row.firstName} {row.lastName} · {row.email}</option>)}</select></label><label>Subject<input required name="subject" maxLength={300} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label>Message preview<textarea required name="body" maxLength={20000} className="mt-1 min-h-32 w-full rounded-xl border p-3"/></label><p className="text-xs">Review the final recipient, subject, and message above before sending.</p><button className={`${button} bg-blue-700 text-white`}>Send email</button></form></details></div>
    <form className="mt-4 grid gap-2 rounded-xl border bg-[var(--surface)] p-4 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="view" value={view}/><label>Event<input name="eventType" className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label>Channel<select name="channel" className="mt-1 min-h-11 w-full rounded-xl border bg-[var(--surface)] px-3"><option value="">All</option><option>Email</option><option>Sms</option><option>Internal</option><option>Portal</option></select></label><label>Status<input name="status" className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label>Source ID<input name="sourceId" className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><button className={button}>Apply filters</button></form>
    <div className="mt-4 grid gap-3 md:hidden">{data.deliveries.map((row)=><DeliveryCard key={row.id} row={row}/>)}</div>
    <div className="mt-4 hidden overflow-x-auto rounded-xl border md:block"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Event</th><th>Channel</th><th>Recipient</th><th>Status</th><th>Scheduled/sent</th><th>Result</th></tr></thead><tbody>{data.deliveries.map((row)=><tr key={row.id} className="border-b last:border-0"><td className="p-3">{row.event?.eventType??"Manual"}<br/><span className="text-xs">{row.event?.sourceType} {row.event?.sourceId}</span></td><td>{row.channel}</td><td>{row.recipientType??"Protected"}<br/><span className="text-xs">{row.destination??row.recipientHash.slice(0,10)}</span></td><td><span aria-label={`Delivery status ${row.status}`} className="rounded-full border px-2 py-1">{row.status}</span></td><td>{date(row.sentAt??row.scheduledFor)}</td><td>{row.failureReason??row.delayReason??(row.deliveredAt?"Delivered":"—")}{["Failed","Bounced","Rejected"].includes(row.status)&&row.backgroundJobId&&<form action={retryCommunicationAction}><input type="hidden" name="deliveryId" value={row.id}/><button className={`${button} mt-2`}>Retry</button></form>}</td></tr>)}</tbody></table></div>
  </section>;
}
function DeliveryCard({row}:{row:Awaited<ReturnType<typeof getCommunicationCenter>>["deliveries"][number]}) {return <article className="rounded-xl border bg-[var(--surface)] p-4"><div className="flex justify-between gap-2"><strong>{row.event?.eventType??"Manual email"}</strong><span aria-label={`Delivery status ${row.status}`} className="rounded-full border px-2 py-1 text-xs">{row.status}</span></div><p className="mt-2">{row.channel} · {row.recipientType??"Protected recipient"}</p><p className="text-sm">{date(row.sentAt??row.scheduledFor)}</p>{row.subject&&<p className="mt-2 font-medium">{row.subject}</p>}<p className="mt-1 line-clamp-3 whitespace-pre-wrap text-sm">{row.renderedBody??"Message body protected."}</p>{(row.failureReason||row.delayReason)&&<p className="mt-2 text-sm">{row.failureReason??row.delayReason}</p>}</article>}
function Templates({data}:{data:Awaited<ReturnType<typeof getCommunicationCenter>>}) {return <section className="mt-6"><h2 className="text-xl font-bold">Templates</h2><p className="text-sm">Only validated safe variables are supported.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{data.templates.map((row)=><form action={saveCommunicationTemplateAction} key={row.id} className="rounded-xl border bg-[var(--surface)] p-4"><input type="hidden" name="id" value={row.id}/><p className="text-xs font-bold">{row.eventType} · {row.channel}</p><h3 className="font-bold">{row.name}</h3><label className="mt-3 block">Subject<input name="subject" defaultValue={row.subject??""} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label className="mt-3 block">Body<textarea name="body" defaultValue={row.body} className="mt-1 min-h-40 w-full rounded-xl border p-3"/></label><label className="mt-3 flex min-h-11 items-center gap-2"><input type="checkbox" name="active" defaultChecked={row.active}/>Active</label><button className={button}>Save template</button></form>)}</div></section>}
function Automation({data}:{data:Awaited<ReturnType<typeof getCommunicationCenter>>}) {return <section className="mt-6"><h2 className="text-xl font-bold">Automation settings</h2><div className="mt-4 grid gap-3">{data.rules.map((row)=><article key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-[var(--surface)] p-4"><div><strong>{row.eventType}</strong><p className="text-sm">{row.channel} to {row.recipientType} · {row.template.name} · {row.delayMinutes?`${row.delayMinutes} minute delay`:"Immediate"} · {row.respectQuietHours?"Quiet hours respected":"Urgent"}</p></div><form action={toggleCommunicationRuleAction}><input type="hidden" name="id" value={row.id}/><button className={button}>{row.enabled?"Disable":"Enable"}</button></form></article>)}</div></section>}
function Preferences({data}:{data:Awaited<ReturnType<typeof getCommunicationCenter>>}) {const row=data.preference;return <section className="mt-6 max-w-2xl"><h2 className="text-xl font-bold">Company preferences</h2><form action={saveCommunicationPreferencesAction} className="mt-4 grid gap-4 rounded-xl border bg-[var(--surface)] p-4"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="emailEnabled" defaultChecked={row?.emailEnabled??true}/>Email enabled</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" disabled/>SMS unavailable — no provider configured</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="internalEnabled" defaultChecked={row?.internalEnabled??true}/>Internal notifications</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="portalEnabled" defaultChecked={row?.portalEnabled??true}/>Portal messages</label><label>Quiet hours start<input name="quietHoursStart" type="time" defaultValue={row?.quietHoursStart??""} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label>Quiet hours end<input name="quietHoursEnd" type="time" defaultValue={row?.quietHoursEnd??""} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label>Time zone<input required name="timeZone" defaultValue={row?.timeZone??"America/New_York"} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><button className={`${button} bg-blue-700 text-white`}>Save preferences</button></form></section>}
function Notifications({data}:{data:Awaited<ReturnType<typeof getCommunicationCenter>>}) {return <section className="mt-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Internal notifications</h2><p className="text-sm">{data.unreadCount} unread</p></div><form action={markAllNotificationsReadAction}><button className={button}>Mark all read</button></form></div><div className="mt-4 grid gap-3">{data.notifications.map((row)=><article key={row.id} className={`rounded-xl border p-4 ${row.readAt?"bg-[var(--surface)]":"border-blue-400 bg-blue-50 dark:bg-blue-950"}`}><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-bold">{row.title}</h3><p className="whitespace-pre-wrap text-sm">{row.body}</p><p className="mt-1 text-xs">{date(row.createdAt)}</p></div><div className="flex gap-2">{row.link&&<Link className={button} href={row.link}>Open</Link>}{!row.readAt&&<form action={markNotificationReadAction}><input type="hidden" name="id" value={row.id}/><button className={button}>Mark read</button></form>}</div></div></article>)}</div></section>}
const title=(value:string)=>value.replace(/([A-Z])/g," $1").replace(/^./,(letter)=>letter.toUpperCase());
const date=(value:Date|null)=>value?value.toLocaleString():"—";
