CREATE TYPE "SubscriptionPlan" AS ENUM ('Starter','Professional','Business');
CREATE TYPE "SubscriptionStatus" AS ENUM ('Trialing','Active','PastDue','Unpaid','Canceled','Incomplete','Paused');
ALTER TABLE "company_memberships" ADD COLUMN "billingAdmin" BOOLEAN NOT NULL DEFAULT false;
CREATE TABLE "company_subscriptions" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"stripeCustomerId" TEXT,"stripeSubscriptionId" TEXT,"plan" "SubscriptionPlan" NOT NULL DEFAULT 'Starter',"status" "SubscriptionStatus" NOT NULL DEFAULT 'Trialing',"trialStart" TIMESTAMP(3),"trialEnd" TIMESTAMP(3),"currentPeriodStart" TIMESTAMP(3),"currentPeriodEnd" TIMESTAMP(3),"cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT false,"canceledAt" TIMESTAMP(3),"gracePeriodEnd" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "company_subscriptions_pkey" PRIMARY KEY ("id"),CONSTRAINT "company_subscriptions_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "subscription_history" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"plan" "SubscriptionPlan" NOT NULL,"status" "SubscriptionStatus" NOT NULL,"stripeSubscriptionId" TEXT,"source" TEXT NOT NULL,"effectiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"metadata" JSONB,CONSTRAINT "subscription_history_pkey" PRIMARY KEY ("id"),CONSTRAINT "subscription_history_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "stripe_webhook_events" ("id" TEXT NOT NULL,"companyId" TEXT,"stripeEventId" TEXT NOT NULL,"type" TEXT NOT NULL,"processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "stripe_webhook_events_pkey" PRIMARY KEY ("id"),CONSTRAINT "stripe_webhook_events_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX "company_subscriptions_companyId_key" ON "company_subscriptions"("companyId"); CREATE UNIQUE INDEX "company_subscriptions_stripeCustomerId_key" ON "company_subscriptions"("stripeCustomerId"); CREATE UNIQUE INDEX "company_subscriptions_stripeSubscriptionId_key" ON "company_subscriptions"("stripeSubscriptionId"); CREATE INDEX "company_subscriptions_status_trialEnd_idx" ON "company_subscriptions"("status","trialEnd"); CREATE INDEX "subscription_history_companyId_effectiveAt_idx" ON "subscription_history"("companyId","effectiveAt"); CREATE UNIQUE INDEX "stripe_webhook_events_stripeEventId_key" ON "stripe_webhook_events"("stripeEventId"); CREATE INDEX "stripe_webhook_events_companyId_processedAt_idx" ON "stripe_webhook_events"("companyId","processedAt");
-- Existing tenants receive the same safe trial transition as new signups.
INSERT INTO "company_subscriptions" ("id","companyId","plan","status","trialStart","trialEnd","updatedAt") SELECT gen_random_uuid()::text,"id",'Professional','Trialing',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + INTERVAL '14 days',CURRENT_TIMESTAMP FROM "companies";
