import Link from "next/link";
import Image from "next/image";
import { ArrowRight } from "lucide-react";
import ProductWorkflowStory from "@/components/marketing/ProductWorkflowStory";
import { plans } from "@/lib/billing/config";
import { billingFeatureLabel } from "@/lib/billing/presentation";
import { marketingMetadata, siteUrl } from "@/lib/marketing/metadata";
import { homepageFaqs, homepageStructuredData } from "@/lib/marketing/homepage";

export const metadata = marketingMetadata(
  "/",
  "Junk Removal Estimating & Job Management Software | JunkQuote Pro",
  "Estimating and job management software built specifically for junk removal businesses. Create quotes faster, organize jobs, manage customers, and run your operation from one place.",
);

const structuredData = homepageStructuredData(siteUrl);

const outcomes = [["Win the job before competitors respond", "Build consistent estimates and send them for customer approval while the customer is still on the phone."], ["Stop missing pickups and dispatching by group text", "See all jobs, crews, and fleet information in one view so no truck sits idle."], ["Get paid on-site, not next week", "Move from completed work to invoicing to payment collection without chasing customers."], ["Stop underpricing jobs you quoted over the phone.", "Build estimates from consistent pricing so the crew arrives to a job that matches the quote."]] as const;
const faqs = homepageFaqs;

export default function Home() {
  const professional = plans.Professional;
  return <main className="min-h-screen overflow-x-hidden bg-[#050806] text-white">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replaceAll("<", "\\u003c") }} />
    <header className="border-b border-[#a4ef29]/20 bg-black/80"><nav aria-label="Public navigation" className="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-x-4 px-5 py-2 sm:px-8"><Link href="/" className="inline-flex min-h-11 items-center text-lg font-black tracking-tight">JunkQuote <span className="ml-1 text-[#a4ef29]">Pro</span></Link><div className="flex w-full flex-wrap items-center justify-end gap-1 sm:w-auto"><Link href="/features" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Features</Link><Link href="/compare" aria-label="Pricing and software comparisons" className="order-last mt-1 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-[#a4ef29]/50 bg-[#a4ef29]/10 px-4 font-bold text-[#a4ef29] shadow-sm transition-colors hover:bg-[#a4ef29]/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#a4ef29] sm:order-none sm:mt-0 sm:w-auto"><span>Pricing</span><ArrowRight aria-hidden="true" size={16} /></Link><Link href="/about" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">About</Link><Link href="/sign-in" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Sign in</Link></div></nav></header>
    <section className="relative border-b border-white/10 px-5 py-16 sm:px-8 sm:py-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(164,239,41,.14),transparent_34%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><p className="font-bold uppercase tracking-[.22em] text-[#a4ef29]">Built for junk removal pros</p><h1 className="mt-4 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl">Estimating &amp; Job Management Software <span className="text-[#a4ef29]">Built for Junk Removal Pros</span></h1><p className="mt-6 max-w-2xl text-xl font-semibold text-slate-200 sm:text-2xl">Estimate, schedule, dispatch, invoice, and collect payment — all in one organized platform for junk removal pros.</p><div className="mt-8 flex flex-wrap gap-3 text-sm font-bold"><span className="rounded-full border border-[#a4ef29]/50 bg-[#a4ef29]/10 px-4 py-2">30-Day Professional Trial</span><span className="rounded-full border border-white/20 px-4 py-2">No Credit Card Required</span><span className="rounded-full border border-white/20 px-4 py-2">Full Professional Access</span></div><Link href="/sign-up" className="mt-8 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#a4ef29] px-6 py-3 text-center text-base font-black text-black">Start Your 30-Day Professional Trial</Link><p className="mt-4 text-sm font-semibold text-slate-300">Secured by Stripe. 30-day money-back guarantee on all paid plans. No questions asked.</p></div><aside aria-labelledby="founder-card-heading" className="overflow-hidden rounded-3xl border border-[#a4ef29]/30 bg-[#0d130e] shadow-2xl sm:grid sm:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-64 sm:min-h-full"><Image src="/branding/chris-founder.jpg" alt="Chris, founder of JunkQuote Pro" fill priority sizes="(min-width: 1024px) 16vw, (min-width: 640px) 35vw, 100vw" className="object-cover object-[32%_25%]" /></div><div className="p-6"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">Built from the work</p><h2 id="founder-card-heading" className="mt-3 text-2xl font-black leading-tight">Built by a Junk Removal Business Owner</h2><p className="mt-4 leading-relaxed text-slate-300">I built JunkQuote Pro to solve the estimating and organization problems I was dealing with in my own junk removal business.</p><p className="mt-4 font-bold text-white">Chris<br /><span className="text-slate-300">Founder, JunkQuote Pro</span></p><Link href="/about" className="mt-5 inline-flex min-h-11 items-center font-bold text-[#a4ef29] underline decoration-2 underline-offset-4">Meet the Founder →</Link></div></aside></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">One organized platform</p><h2 className="mt-3 max-w-3xl text-3xl font-black sm:text-5xl">Less paperwork. Less chaos. More control.</h2><p className="mt-4 max-w-2xl text-lg text-slate-300">More time to serve customers, lead your team, and grow the business.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{outcomes.map(([title, copy]) => <article key={title} className="rounded-2xl border border-white/10 bg-[#0d130e] p-6"><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-slate-300">{copy}</p></article>)}</div></section>
    <ProductWorkflowStory />
    <section aria-label="Why operators trust JunkQuote Pro" className="border-t border-white/10 bg-[#090d0a] px-5 py-10 sm:px-8"><ul className="mx-auto grid max-w-7xl gap-3 sm:grid-cols-2 lg:grid-cols-4"><li className="rounded-xl border border-white/10 px-4 py-4 font-bold">Built by a Junk Removal Business Owner</li><li className="rounded-xl border border-white/10 px-4 py-4 font-bold">30-Day Professional Trial</li><li className="rounded-xl border border-white/10 px-4 py-4 font-bold">Pricing Per Company — Not Per User</li><li className="rounded-xl border border-white/10 px-4 py-4 font-bold">Built Specifically for Junk Removal</li></ul></section>
    <section className="border-y border-white/10 bg-[#090d0a] px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">Professional access</p><h2 className="mt-2 text-3xl font-black">Try the tools built for a growing operation.</h2></div><Link href="/compare" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#a4ef29]/50 bg-[#a4ef29]/10 px-4 font-bold text-[#a4ef29] transition-colors hover:bg-[#a4ef29]/20"><span>View Pricing &amp; Compare</span><ArrowRight aria-hidden="true" size={17} /></Link></div><ul className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{professional.features.slice(0, 8).map(feature => <li key={feature} className="rounded-xl border border-white/10 p-4 text-slate-200">✓ {billingFeatureLabel(feature)}</li>)}</ul></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">Questions, answered</p><h2 className="mt-3 text-3xl font-black">Built around how junk removal work gets done.</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{faqs.map(([question, answer]) => <article key={question} className="rounded-2xl border border-white/10 bg-[#0d130e] p-6"><h3 className="font-bold">{question}</h3><p className="mt-3 text-slate-300">{answer}</p></article>)}</div></section>
    <footer className="px-5 py-12 text-center"><h2 className="text-3xl font-black">Ready to make business easier?</h2><Link href="/sign-up" className="mt-6 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#a4ef29] px-6 font-black text-black">Start Your 30-Day Professional Trial</Link><p className="mt-4 text-sm text-slate-400">No credit card required. Full Professional access for 30 days.</p><p className="mt-6 text-sm text-slate-400"><Link className="underline" href="/features">Features</Link><span className="px-2">·</span><Link className="underline" href="/customer-stories">Customer Stories</Link><span className="px-2">·</span><Link className="underline" href="/about">About</Link></p></footer>
  </main>;
}
