import Link from "next/link";
import Image from "next/image";
import { plans } from "@/lib/billing/config";
import { billingFeatureLabel } from "@/lib/billing/presentation";

const outcomes = [["Win the job before competitors respond", "Build consistent estimates and send them for customer approval while the customer is still on the phone."], ["Stop missing pickups and dispatching by group text", "See all jobs, crews, and fleet information in one view so no truck sits idle."], ["Get paid on-site, not next week", "Move from completed work to invoicing to payment collection without chasing customers."]] as const;
const faqs = [["Is JunkQuote Pro built specifically for junk removal?", "Yes. Every feature — estimating, scheduling, dispatch, invoicing, and payments — is designed for junk removal operators, not adapted from HVAC or plumbing."], ["What happens after my 30-day trial?", "You automatically move to the Free plan with 6 estimates per month. No charge and no credit card required."], ["Does it integrate with QuickBooks?", "JunkQuote Pro provides QuickBooks-ready payment exports. Direct QuickBooks synchronization is not currently available."], ["How is pricing structured?", "Per company, not per seat. A 10-person crew pays the same as a 3-person crew."]] as const;

export default function Home() {
  const professional = plans.Professional;
  return <main className="min-h-screen overflow-x-hidden bg-[#050806] text-white">
    <header className="border-b border-[#a4ef29]/20 bg-black/80"><nav aria-label="Public navigation" className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-5 sm:px-8"><Link href="/" className="inline-flex min-h-11 items-center text-lg font-black tracking-tight">JunkQuote <span className="ml-1 text-[#a4ef29]">Pro</span></Link><div className="flex items-center gap-1"><Link href="/features" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Features</Link><Link href="/pricing" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Pricing</Link><Link href="/sign-in" className="inline-flex min-h-11 items-center px-3 font-semibold text-slate-200">Sign in</Link></div></nav></header>
    <section className="relative border-b border-white/10 px-5 py-16 sm:px-8 sm:py-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(164,239,41,.14),transparent_34%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><p className="font-bold uppercase tracking-[.22em] text-[#a4ef29]">Built for junk removal pros</p><h1 className="mt-4 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl">Run Your Junk Removal Business. <span className="text-[#a4ef29]">Not Your Paperwork.</span></h1><p className="mt-6 max-w-2xl text-xl font-semibold text-slate-200 sm:text-2xl">Estimate, schedule, dispatch, invoice, and collect payment — all in one organized platform for junk removal pros.</p><div className="mt-8 flex flex-wrap gap-3 text-sm font-bold"><span className="rounded-full border border-[#a4ef29]/50 bg-[#a4ef29]/10 px-4 py-2">30-Day Professional Trial</span><span className="rounded-full border border-white/20 px-4 py-2">No Credit Card Required</span><span className="rounded-full border border-white/20 px-4 py-2">Full Professional Access</span></div><Link href="/sign-up" className="mt-8 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#a4ef29] px-6 py-3 text-center text-base font-black text-black">Start Your 30-Day Professional Trial</Link><p className="mt-4 text-sm font-semibold text-slate-300">Secured by Stripe. 30-day money-back guarantee on all paid plans. No questions asked.</p></div><figure className="overflow-hidden rounded-3xl border border-[#a4ef29]/30 bg-[#0d130e] shadow-2xl"><Image src="/branding/dispatch-board.png" alt="JunkQuote Pro dispatch board showing 6 scheduled pickups across 3 trucks with crew assignments and job statuses." width={1870} height={938} priority className="h-auto w-full" /><figcaption className="px-5 py-4 text-sm text-slate-300">See jobs, crews, vehicles, availability, and dispatch status in one place.</figcaption></figure></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">One organized platform</p><h2 className="mt-3 max-w-3xl text-3xl font-black sm:text-5xl">Less paperwork. Less chaos. More control.</h2><p className="mt-4 max-w-2xl text-lg text-slate-300">More time to serve customers, lead your team, and grow the business.</p><div className="mt-10 grid gap-5 md:grid-cols-3">{outcomes.map(([title, copy]) => <article key={title} className="rounded-2xl border border-white/10 bg-[#0d130e] p-6"><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-slate-300">{copy}</p></article>)}</div></section>
    <section className="border-y border-white/10 bg-[#090d0a] px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-5xl items-center gap-8 md:grid-cols-[180px_1fr]"><Image src="/branding/chris-founder.jpeg" alt="Chris, founder of JunkQuote Pro" width={180} height={180} className="aspect-square rounded-2xl object-cover object-[32%_25%]" /><blockquote><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">Built from the work, not a boardroom</p><p className="mt-4 text-xl font-semibold leading-relaxed text-slate-100">JunkQuote Pro was created by a junk removal business owner who got tired of wasting time on estimates, paperwork, and trying to keep everything organized.</p><p className="mt-4 leading-relaxed text-slate-300">I built JunkQuote Pro to solve the problems I was dealing with in my own business — and to give other junk removal companies a simpler way to quote jobs, manage customers, and keep their business moving.</p><p className="mt-4 font-bold text-[#a4ef29]">Real problems. Real experience. Software built specifically for junk removal.</p><footer className="mt-4 font-bold text-white">— Chris, Founder of JunkQuote Pro</footer></blockquote></div></section>
    <section className="border-y border-white/10 bg-[#090d0a] px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">Professional access</p><h2 className="mt-2 text-3xl font-black">Try the tools built for a growing operation.</h2></div><Link href="/pricing" className="inline-flex min-h-11 items-center font-bold text-[#a4ef29] underline decoration-2 underline-offset-4">Compare all plans</Link></div><ul className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{professional.features.slice(0, 8).map(feature => <li key={feature} className="rounded-xl border border-white/10 p-4 text-slate-200">✓ {billingFeatureLabel(feature)}</li>)}</ul></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a4ef29]">Questions, answered</p><h2 className="mt-3 text-3xl font-black">Built around how junk removal work gets done.</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{faqs.map(([question, answer]) => <article key={question} className="rounded-2xl border border-white/10 bg-[#0d130e] p-6"><h3 className="font-bold">{question}</h3><p className="mt-3 text-slate-300">{answer}</p></article>)}</div></section>
    <footer className="px-5 py-12 text-center"><h2 className="text-3xl font-black">Ready to make business easier?</h2><Link href="/sign-up" className="mt-6 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#a4ef29] px-6 font-black text-black">Start Your 30-Day Professional Trial</Link><p className="mt-4 text-sm text-slate-400">No credit card required. Full Professional access for 30 days.</p><p className="mt-6 text-sm text-slate-400"><Link className="underline" href="/features">Features</Link><span className="px-2">·</span><Link className="underline" href="/customers">Customers</Link><span className="px-2">·</span><Link className="underline" href="/about">About</Link></p></footer>
  </main>;
}
