import{prisma}from"@/lib/prisma";import{calculateProfitability,percentage}from"./calculations";
export type OperationsPeriod="daily"|"weekly"|"monthly"|"quarterly"|"yearly";
export function periodStart(period:OperationsPeriod,now=new Date()){const d=new Date(now);d.setHours(0,0,0,0);if(period==="weekly")d.setDate(d.getDate()-((d.getDay()+6)%7));if(period==="monthly")d.setDate(1);if(period==="quarterly"){d.setMonth(Math.floor(d.getMonth()/3)*3,1)}if(period==="yearly")d.setMonth(0,1);return d;}
export async function getOperationsCenter(companyId:string,period:OperationsPeriod="monthly",now=new Date()){const day=new Date(now);day.setHours(0,0,0,0);const tomorrow=new Date(day);tomorrow.setDate(day.getDate()+1);const weekEnd=new Date(day);weekEnd.setDate(day.getDate()+7);const month=new Date(now.getFullYear(),now.getMonth(),1);const start=periodStart(period,now);const warningDate=new Date(now);warningDate.setDate(now.getDate()+30);
const[jobs,estimates,invoices,payments,employees,assets,disposals]=await Promise.all([
prisma.job.findMany({where:{companyId,OR:[{scheduledStart:{gte:start}},{completedAt:{gte:start}}]},include:{invoice:{select:{total:true,balanceDue:true}},assignments:{select:{employeeId:true,crewId:true}},disposalRecords:true,assignedFleetAsset:true}}),
prisma.estimate.findMany({where:{companyId,createdAt:{gte:start}},select:{status:true,signedAt:true,pricingTotal:true}}),
prisma.invoice.findMany({where:{companyId,createdAt:{gte:start}},select:{status:true,total:true,balanceDue:true,dueDate:true}}),
prisma.payment.findMany({where:{companyId,paymentDate:{gte:start,lte:now}},select:{amount:true,paymentDate:true}}),
prisma.employee.findMany({where:{companyId,status:"Active"},include:{assignedTruck:true,timeEntries:{where:{clockIn:{gte:start}},orderBy:{clockIn:"desc"}},assignments:{where:{job:{OR:[{scheduledStart:{gte:start}},{completedAt:{gte:start}}]}},include:{job:{select:{status:true,scheduledStart:true,scheduledEnd:true,completedAt:true,invoice:{select:{total:true}}}}}}}}),
prisma.fleetAsset.findMany({where:{companyId,status:{not:"Retired"}},include:{maintenance:{orderBy:{servicedAt:"desc"},take:5},jobs:{where:{OR:[{scheduledStart:{gte:start}},{completedAt:{gte:start}}]},select:{id:true,status:true,scheduledStart:true,completedAt:true}}}}),
prisma.disposalRecord.findMany({where:{companyId,createdAt:{gte:start}},include:{job:{select:{jobNumber:true,invoice:{select:{total:true}}}}}})]);
const completed=jobs.filter(j=>j.status==="Completed");const revenue=payments.reduce((s,p)=>s+p.amount,0);const todayPayments=payments.filter(p=>p.paymentDate>=day).reduce((s,p)=>s+p.amount,0);const laborCost=completed.reduce((s,j)=>s+(j.actualLaborCost??0),0);const disposalCost=disposals.reduce((s,d)=>s+d.cost,0);const fuelEstimate=completed.reduce((s,j)=>s+(j.actualTravelCost??0),0);const dumpFees=completed.reduce((s,j)=>s+(j.actualDisposalCost??0),0);const processingFees=revenue*.029;const profitability=calculateProfitability({revenue,laborCost,fuelEstimate,disposalCost,dumpFees,processingFees});const approved=estimates.filter(e=>e.signedAt||e.status==="Approved"||e.status==="Scheduled"||e.status==="Completed").length;const scheduledHours=jobs.reduce((s,j)=>s+(j.scheduledStart&&j.scheduledEnd?Math.max(0,(j.scheduledEnd.getTime()-j.scheduledStart.getTime())/36e5):0),0);const workedHours=employees.flatMap(e=>e.timeEntries).filter(t=>t.type==="Work").reduce((s,t)=>s+(t.clockOut?Math.max(0,(t.clockOut.getTime()-t.clockIn.getTime())/36e5):0),0);const truckJobs=assets.reduce((s,a)=>s+a.jobs.length,0);const completionMinutes=completed.filter(j=>j.scheduledStart&&j.completedAt).map(j=>(j.completedAt!.getTime()-j.scheduledStart!.getTime())/6e4);
const alerts=[...assets.flatMap(a=>[{show:Boolean(a.insuranceExpiresAt&&a.insuranceExpiresAt<=warningDate),type:"Insurance Expiring",message:`${a.name} insurance expires ${a.insuranceExpiresAt?.toLocaleDateString()}`},{show:Boolean(a.registrationExpiresAt&&a.registrationExpiresAt<=warningDate),type:"Registration Expiring",message:`${a.name} registration expires ${a.registrationExpiresAt?.toLocaleDateString()}`},{show:Boolean((a.oilChangeDueAt&&a.odometer&&a.odometer>=a.oilChangeDueAt)||(a.tireServiceDueAt&&a.odometer&&a.odometer>=a.tireServiceDueAt)),type:"Maintenance Due",message:`${a.name} has mileage-based service due`}]).filter(x=>x.show),...invoices.filter(i=>i.balanceDue>0&&i.dueDate&&i.dueDate<now).map(i=>({type:"Unpaid Invoice",message:`${i.status} invoice has $${i.balanceDue.toFixed(2)} overdue`})),...jobs.filter(j=>j.status!=="Completed"&&j.status!=="Cancelled"&&j.scheduledEnd&&j.scheduledEnd<now).map(j=>({type:"Job Running Late",message:`${j.jobNumber??"Job"} is running late`})),...jobs.filter(j=>j.status==="Scheduled"&&!j.assignments.length).map(j=>({type:"Crew Missing",message:`${j.jobNumber??"Job"} has no assigned crew`})),...(percentage(approved,estimates.length)<30&&estimates.length>=5?[{type:"Low Conversion Rate",message:`Estimate approval is ${percentage(approved,estimates.length).toFixed(1)}%`}]:[])];
return{period,start,live:{jobsToday:jobs.filter(j=>j.scheduledStart&&j.scheduledStart>=day&&j.scheduledStart<tomorrow).length,jobsWeek:jobs.filter(j=>j.scheduledStart&&j.scheduledStart>=day&&j.scheduledStart<weekEnd).length,pendingEstimates:estimates.filter(e=>["Draft","Ready"].includes(e.status)).length,awaitingApproval:estimates.filter(e=>e.status==="Sent").length,scheduledJobs:jobs.filter(j=>j.status==="Scheduled").length,inProgressJobs:jobs.filter(j=>j.status==="InProgress").length,completedToday:completed.filter(j=>j.completedAt&&j.completedAt>=day).length,revenueToday:todayPayments,revenueMonth:payments.filter(p=>p.paymentDate>=month).reduce((s,p)=>s+p.amount,0),outstandingInvoices:invoices.reduce((s,i)=>s+i.balanceDue,0),averageTicket:completed.length?completed.reduce((s,j)=>s+(j.invoice?.total??0),0)/completed.length:0,conversionRate:percentage(approved,estimates.length)},profitability,kpis:{monthlyRevenue:payments.filter(p=>p.paymentDate>=month).reduce((s,p)=>s+p.amount,0),monthlyJobs:completed.filter(j=>j.completedAt&&j.completedAt>=month).length,averageTicket:completed.length?completed.reduce((s,j)=>s+(j.invoice?.total??0),0)/completed.length:0,estimateApprovalRate:percentage(approved,estimates.length),leadConversion:percentage(jobs.length,estimates.length),crewUtilization:percentage(workedHours,Math.max(scheduledHours,employees.length*40)),truckUtilization:percentage(truckJobs,Math.max(assets.length*5,1)),averageCompletionMinutes:completionMinutes.length?completionMinutes.reduce((a,b)=>a+b,0)/completionMinutes.length:0},employees,assets,disposals,alerts};}
