import type { EstimateStatus } from "@/generated/prisma/client";
export const ESTIMATE_STATUSES=["Draft","Sent","Viewed","Approved","Scheduled","InProgress","Completed","Invoiced","Paid","Declined","Expired","Canceled"] as const satisfies readonly EstimateStatus[];
export const estimateTransitions:Readonly<Record<EstimateStatus,readonly EstimateStatus[]>>={Draft:["Sent","Canceled"],Sent:["Viewed","Approved","Declined","Expired","Canceled"],Viewed:["Approved","Declined","Expired"],Approved:["Scheduled"],Scheduled:["InProgress"],InProgress:["Completed"],Completed:["Invoiced"],Invoiced:["Paid"],Paid:[],Declined:[],Expired:["Sent"],Canceled:[]};
const editable=new Set<EstimateStatus>(["Draft","Sent","Viewed","Declined","Expired"]);const deletable=new Set(editable);
export function isEstimateEditable(e:{status:EstimateStatus|string}){return editable.has(e.status as EstimateStatus)}
export function canDeleteEstimate(e:{status:EstimateStatus|string}){return deletable.has(e.status as EstimateStatus)}
export function canTransitionEstimateStatus(from:EstimateStatus,to:EstimateStatus){return estimateTransitions[from].includes(to)}
export const ESTIMATE_READ_ONLY_MESSAGE="This estimate is read-only in its current lifecycle state. Create a revision to make changes.";
export const ESTIMATE_DELETE_MESSAGE="This estimate cannot be deleted in its current lifecycle state.";
export const estimateStatusBadges:Record<EstimateStatus,{label:string;className:string;color:string}>={Draft:{label:"Draft",className:"bg-slate-100 text-slate-700",color:"grey"},Sent:{label:"Sent",className:"bg-blue-100 text-blue-800",color:"blue"},Viewed:{label:"Viewed",className:"bg-purple-100 text-purple-800",color:"purple"},Approved:{label:"Approved",className:"bg-green-100 text-green-800",color:"green"},Scheduled:{label:"Scheduled",className:"bg-orange-100 text-orange-800",color:"orange"},InProgress:{label:"In Progress",className:"bg-yellow-100 text-yellow-900",color:"yellow"},Completed:{label:"Completed",className:"bg-teal-100 text-teal-800",color:"teal"},Invoiced:{label:"Invoiced",className:"bg-indigo-100 text-indigo-800",color:"indigo"},Paid:{label:"Paid",className:"bg-emerald-900 text-white",color:"dark green"},Declined:{label:"Declined",className:"bg-red-100 text-red-800",color:"red"},Expired:{label:"Expired",className:"bg-amber-100 text-amber-900",color:"amber"},Canceled:{label:"Canceled",className:"bg-slate-700 text-white",color:"dark grey"}};
