"use client";
import { useState } from "react";
import { updateJobAction } from "@/app/actions/jobs/updateJob";
type Values = { actualLaborHours: number | null; actualLaborCost: number | null; actualDisposalCost: number | null; actualTravelCost: number | null; otherActualCost: number | null; finalInvoiceAmount: number | null; actualCostNotes: string };
export default function ActualCosts({ jobId, initial }: { jobId: string; initial: Values }) {
  const [value, setValue] = useState(() => ({ ...initial, actualLaborHours: text(initial.actualLaborHours), actualLaborCost: text(initial.actualLaborCost), actualDisposalCost: text(initial.actualDisposalCost), actualTravelCost: text(initial.actualTravelCost), otherActualCost: text(initial.otherActualCost), finalInvoiceAmount: text(initial.finalInvoiceAmount) })); const [message, setMessage] = useState("");
  async function save() { await updateJobAction({ id: jobId, actualLaborHours: number(value.actualLaborHours), actualLaborCost: number(value.actualLaborCost), actualDisposalCost: number(value.actualDisposalCost), actualTravelCost: number(value.actualTravelCost), otherActualCost: number(value.otherActualCost), finalInvoiceAmount: number(value.finalInvoiceAmount), actualCostNotes: value.actualCostNotes }); setMessage("Actual costs and final invoice amount saved."); }
  return <section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Completion costs</h2><p className="mt-1 text-sm text-slate-500">Blank values remain incomplete and are never silently treated as zero.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{([['actualLaborHours','Actual labor hours'],['actualLaborCost','Actual labor cost'],['actualDisposalCost','Actual disposal cost'],['actualTravelCost','Actual travel cost'],['otherActualCost','Other actual cost'],['finalInvoiceAmount','Final invoice amount']] as const).map(([key,label]) => <label key={key} className="grid gap-1 text-sm font-medium">{label}<input className="rounded-xl border p-3" type="number" min="0" step="0.01" value={value[key]} onChange={(event) => setValue((current) => ({ ...current, [key]: event.target.value }))}/></label>)}</div><label className="mt-3 grid gap-1 text-sm font-medium">Internal notes<textarea className="min-h-20 rounded-xl border p-3" value={value.actualCostNotes} onChange={(event) => setValue((current) => ({ ...current, actualCostNotes: event.target.value }))}/></label><button className="mt-4 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white" onClick={() => void save()}>Save completion costs</button>{message && <p className="mt-2 text-sm text-green-700">{message}</p>}</section>;
}
const text = (value: number | null) => value === null ? "" : String(value);
const number = (value: string) => value.trim() === "" ? null : Number(value);
