"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { listCrews } from "@/app/actions/crews/management";
import { scheduleApprovedEstimateAction } from "@/app/actions/jobs/scheduleApprovedEstimate";

export default function ScheduleJobButton({ estimateId }: { estimateId: string }) {
  const router = useRouter(); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [crews,setCrews]=useState<Awaited<ReturnType<typeof listCrews>>>([]);
  const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [crewId,setCrewId]=useState(""); const [truck,setTruck]=useState(""); const [notes,setNotes]=useState("");
  useEffect(()=>{if(open&&!crews.length)void listCrews(true).then(setCrews).catch(()=>setError("Unable to load crews."));},[open,crews.length]);
  async function schedule(){setBusy(true);setError(null);try{const job=await scheduleApprovedEstimateAction({estimateId,scheduledStart:new Date(start).toISOString(),scheduledEnd:new Date(end).toISOString(),crewId:crewId||undefined,truck,notes});router.push(`/jobs/${job.id}`);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to schedule job.");setBusy(false);}}
  return <div>{!open?<button type="button" onClick={()=>setOpen(true)} className="rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white">Schedule Job</button>:<div className="min-w-72 rounded-xl border bg-white p-4 shadow-lg"><h3 className="font-bold">Schedule Job</h3><div className="mt-3 grid gap-3"><label className="grid gap-1 text-sm">Start<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} className="rounded border p-2"/></label><label className="grid gap-1 text-sm">End<input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="rounded border p-2"/></label><label className="grid gap-1 text-sm">Crew<select value={crewId} onChange={e=>setCrewId(e.target.value)} className="rounded border p-2"><option value="">Unassigned</option>{crews.map(crew=><option key={crew.id} value={crew.id}>{crew.name}</option>)}</select></label><label className="grid gap-1 text-sm">Truck<input value={truck} onChange={e=>setTruck(e.target.value)} className="rounded border p-2" placeholder="Truck 1"/></label><label className="grid gap-1 text-sm">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="rounded border p-2"/></label></div><div className="mt-3 flex gap-2"><button disabled={busy||!start||!end} onClick={()=>void schedule()} className="rounded bg-blue-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?"Scheduling...":"Schedule"}</button><button disabled={busy} onClick={()=>setOpen(false)} className="rounded border px-3 py-2 text-sm">Cancel</button></div>{error&&<p className="mt-2 text-sm text-red-600">{error}</p>}</div>}</div>;
}
