export type RecurrencePlan = { recurrenceType: "Weekly" | "Monthly" | "CustomInterval"; interval: number; daysOfWeek: number[]; dayOfMonth: number | null; shortMonthBehavior: "LastDay" | "Skip"; startDate: Date; endDate: Date | null; preferredStartTime: string | null };
export function validateRecurrence(plan: RecurrencePlan) { const errors: string[] = []; if (!Number.isInteger(plan.interval) || plan.interval < 1) errors.push("Interval must be a positive whole number."); if (plan.recurrenceType === "Weekly" && (!plan.daysOfWeek.length || plan.daysOfWeek.some((day) => !Number.isInteger(day) || day < 0 || day > 6))) errors.push("Weekly plans require valid selected weekdays."); if (plan.recurrenceType === "Monthly" && (!plan.dayOfMonth || plan.dayOfMonth < 1 || plan.dayOfMonth > 31)) errors.push("Monthly plans require a day from 1 to 31."); if (plan.endDate && plan.endDate < plan.startDate) errors.push("End date must follow start date."); if (plan.preferredStartTime && !/^([01]\d|2[0-3]):[0-5]\d$/.test(plan.preferredStartTime)) errors.push("Preferred start time must use HH:mm."); return errors; }
const localParts = (date: Date, timeZone: string) => Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(date).filter((part) => part.type !== "literal").map((part) => [part.type, Number(part.value)])) as Record<"year"|"month"|"day"|"hour"|"minute", number>;
function zonedDate(year: number, month: number, day: number, time: string | null, timeZone: string) { const [hour, minute] = (time ?? "09:00").split(":").map(Number); const target = Date.UTC(year, month - 1, day, hour, minute); let guess = target; for (let i = 0; i < 4; i++) { const p = localParts(new Date(guess), timeZone); const represented = Date.UTC(p.year, p.month - 1, p.day, p.hour, p.minute); const delta = target - represented; if (!delta) break; guess += delta; } return new Date(guess); }
const dateKey = (date: Date, timeZone: string) => { const p = localParts(date, timeZone); return Date.UTC(p.year, p.month - 1, p.day); };
const daysInMonth = (year: number, month: number) => new Date(Date.UTC(year, month, 0)).getUTCDate();
function occursOn(plan: RecurrencePlan, cursor: Date, startKey: number) { const year = cursor.getUTCFullYear(), month = cursor.getUTCMonth() + 1, day = cursor.getUTCDate(); const diffDays = Math.floor((cursor.getTime() - startKey) / 86400000); if (diffDays < 0) return false; if (plan.recurrenceType === "CustomInterval") return diffDays % plan.interval === 0; if (plan.recurrenceType === "Weekly") { const week = Math.floor(diffDays / 7); return week % plan.interval === 0 && plan.daysOfWeek.includes(cursor.getUTCDay()); } const start = new Date(startKey); const monthDiff = (year - start.getUTCFullYear()) * 12 + month - (start.getUTCMonth() + 1); if (monthDiff < 0 || monthDiff % plan.interval) return false; const wanted = plan.dayOfMonth!; const max = daysInMonth(year, month); return wanted <= max ? day === wanted : plan.shortMonthBehavior === "LastDay" && day === max; }
export function listUpcomingOccurrences(plan: RecurrencePlan, range: { from: Date; to: Date }, timeZone: string) { const errors = validateRecurrence(plan); if (errors.length) throw new Error(errors.join(" ")); const startKey = dateKey(plan.startDate, timeZone); const fromKey = Math.max(startKey, dateKey(range.from, timeZone)); const toKey = dateKey(range.to, timeZone); const endKey = plan.endDate ? dateKey(plan.endDate, timeZone) : Number.POSITIVE_INFINITY; const occurrences: Date[] = []; for (let key = fromKey; key <= toKey && key <= endKey; key += 86400000) { const cursor = new Date(key); if (!occursOn(plan, cursor, startKey)) continue; const occurrence = zonedDate(cursor.getUTCFullYear(), cursor.getUTCMonth() + 1, cursor.getUTCDate(), plan.preferredStartTime, timeZone); if (occurrence >= range.from && occurrence <= range.to && !occurrences.some((value) => value.getTime() === occurrence.getTime())) occurrences.push(occurrence); } return occurrences; }
export function calculateNextOccurrence(plan: RecurrencePlan, fromDate: Date, timeZone: string) { const horizon = new Date(fromDate); horizon.setUTCFullYear(horizon.getUTCFullYear() + 10); return listUpcomingOccurrences(plan, { from: new Date(fromDate.getTime() + 1), to: horizon }, timeZone)[0] ?? null; }
