import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import type { RecurrenceType, ServicePlanStatus, ShortMonthBehavior } from "@/generated/prisma/client";
import { calculateNextOccurrence, listUpcomingOccurrences, validateRecurrence } from "./recurrence";

export interface ServicePlanInput { customerId: string; propertyId?: string | null; name: string; description?: string; status?: ServicePlanStatus; recurrenceType: RecurrenceType; interval: number; daysOfWeek?: number[]; dayOfMonth?: number | null; shortMonthBehavior?: ShortMonthBehavior; startDate: Date; endDate?: Date | null; preferredStartTime?: string; preferredEndTime?: string; defaultDurationMinutes?: number | null; assignedCrewId?: string | null; employeeIds?: string[]; defaultJobNotes?: string; defaultInternalNotes?: string; defaultPrice?: number | null; autoCreateJobs?: boolean; autoCreateInvoices?: boolean; }
async function validateRelations(companyId: string, input: ServicePlanInput) { const [customer, property, crew, employees] = await Promise.all([prisma.customer.findFirst({ where: { id: input.customerId, companyId }, select: { id: true } }), input.propertyId ? prisma.property.findFirst({ where: { id: input.propertyId, customerId: input.customerId, customer: { companyId } }, select: { id: true } }) : null, input.assignedCrewId ? prisma.crew.findFirst({ where: { id: input.assignedCrewId, companyId, active: true }, select: { id: true } }) : null, prisma.employee.findMany({ where: { id: { in: input.employeeIds ?? [] }, companyId, status: "Active" }, select: { id: true } })]); if (!customer) throw new Error("Customer not found."); if (input.propertyId && !property) throw new Error("Property not found for customer."); if (input.assignedCrewId && !crew) throw new Error("Crew not found."); if (employees.length !== new Set(input.employeeIds ?? []).size) throw new Error("One or more employees were not found."); const errors = validateRecurrence({ recurrenceType: input.recurrenceType, interval: input.interval, daysOfWeek: input.daysOfWeek ?? [], dayOfMonth: input.dayOfMonth ?? null, shortMonthBehavior: input.shortMonthBehavior ?? "LastDay", startDate: input.startDate, endDate: input.endDate ?? null, preferredStartTime: input.preferredStartTime ?? null }); if (errors.length) throw new Error(errors.join(" ")); }
const data = (input: ServicePlanInput) => ({ customerId: input.customerId, propertyId: input.propertyId ?? null, name: input.name.trim(), description: input.description?.trim() || null, status: input.status ?? "Draft" as const, recurrenceType: input.recurrenceType, interval: input.interval, daysOfWeek: [...new Set(input.daysOfWeek ?? [])], dayOfMonth: input.dayOfMonth ?? null, shortMonthBehavior: input.shortMonthBehavior ?? "LastDay" as const, startDate: input.startDate, endDate: input.endDate ?? null, preferredStartTime: input.preferredStartTime?.trim() || null, preferredEndTime: input.preferredEndTime?.trim() || null, defaultDurationMinutes: input.defaultDurationMinutes ?? null, assignedCrewId: input.assignedCrewId ?? null, defaultJobNotes: input.defaultJobNotes?.trim() || null, defaultInternalNotes: input.defaultInternalNotes?.trim() || null, defaultPrice: input.defaultPrice ?? null, autoCreateJobs: input.autoCreateJobs ?? false, autoCreateInvoices: input.autoCreateInvoices ?? false });
export async function createServicePlan(companyId: string, createdByUserId: string, input: ServicePlanInput) { if (!input.name.trim()) throw new Error("Plan name is required."); await validateRelations(companyId, input); const company = await prisma.company.findUnique({ where: { id: companyId }, select: { timezone: true } }); if (!company) throw new Error("Company not found."); const planData = data(input); const nextRunAt = input.status === "Active" ? calculateNextOccurrence(planData, new Date(input.startDate.getTime() - 1), company.timezone) : null; return prisma.servicePlan.create({ data: { companyId, createdByUserId, ...planData, nextRunAt, employeeAssignments: { create: (input.employeeIds ?? []).map((employeeId) => ({ employeeId })) } } }); }
export async function updateServicePlan(companyId: string, servicePlanId: string, input: ServicePlanInput) { const plan = await prisma.servicePlan.findFirst({ where: { id: servicePlanId, companyId }, select: { id: true } }); if (!plan) throw new Error("Service plan not found."); await validateRelations(companyId, input); const company = await prisma.company.findUnique({ where: { id: companyId }, select: { timezone: true } }); const planData = data(input); const nextRunAt = input.status === "Active" && company ? calculateNextOccurrence(planData, new Date(), company.timezone) : null; return prisma.$transaction(async (tx) => { await tx.servicePlanEmployee.deleteMany({ where: { servicePlanId: plan.id } }); return tx.servicePlan.update({ where: { id: plan.id }, data: { ...planData, nextRunAt, employeeAssignments: { create: (input.employeeIds ?? []).map((employeeId) => ({ employeeId })) } } }); }); }
export async function setServicePlanStatus(companyId: string, servicePlanId: string, status: ServicePlanStatus) { const plan = await prisma.servicePlan.findFirst({ where: { id: servicePlanId, companyId }, include: { company: { select: { timezone: true } } } }); if (!plan) throw new Error("Service plan not found."); if (["Completed","Cancelled"].includes(plan.status) && status === "Active") throw new Error("Completed or cancelled plans cannot be resumed."); const nextRunAt = status === "Active" ? calculateNextOccurrence(plan, new Date(), plan.company.timezone) : null; return prisma.servicePlan.update({ where: { id: plan.id }, data: { status, nextRunAt } }); }
export async function listServicePlans(companyId: string, filters: { search?: string; customerId?: string; status?: ServicePlanStatus } = {}) { if (filters.customerId && !await prisma.customer.findFirst({ where: { id: filters.customerId, companyId }, select: { id: true } })) throw new Error("Customer filter not available."); return prisma.servicePlan.findMany({ where: { companyId, ...(filters.customerId ? { customerId: filters.customerId } : {}), ...(filters.status ? { status: filters.status } : {}), ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: "insensitive" } }, { customer: { OR: [{ firstName: { contains: filters.search, mode: "insensitive" } }, { lastName: { contains: filters.search, mode: "insensitive" } }] } }] } : {}) }, include: { customer: true, property: true, assignedCrew: true }, orderBy: { updatedAt: "desc" } }); }
export async function getServicePlan(companyId: string, servicePlanId: string) { return prisma.servicePlan.findFirst({ where: { id: servicePlanId, companyId }, include: { customer: true, property: true, assignedCrew: true, employeeAssignments: { include: { employee: true } }, jobs: { orderBy: { servicePlanOccurrence: "desc" }, take: 20, include: { invoice: true } }, company: { select: { timezone: true } } } }); }
export async function previewServicePlanOccurrences(companyId: string, servicePlanId: string, through: Date) { const plan = await getServicePlan(companyId, servicePlanId); if (!plan) throw new Error("Service plan not found."); return listUpcomingOccurrences(plan, { from: new Date(), to: through }, plan.company.timezone); }

export async function generateJobFromServicePlan(companyId: string, servicePlanId: string, occurrenceDate: Date) {
  const existing = await prisma.job.findFirst({ where: { companyId, servicePlanId, servicePlanOccurrence: occurrenceDate } }); if (existing) return existing;
  const plan = await prisma.servicePlan.findFirst({ where: { id: servicePlanId, companyId, status: "Active" }, include: { company: true, employeeAssignments: true } }); if (!plan) throw new Error("Active service plan not found."); if (!plan.propertyId) throw new Error("A property is required before generating jobs.");
  const end = new Date(occurrenceDate.getTime() + (plan.defaultDurationMinutes ?? 60) * 60000);
  try { const job = await prisma.$transaction(async (tx) => { const pricingProfile = await tx.pricingProfile.findFirst({ where: { companyId, active: true, defaultProfile: true }, select: { id: true } }); if (!pricingProfile) throw new Error("A default pricing profile is required."); const estimate = await tx.estimate.create({ data: { companyId, pricingProfileId: pricingProfile.id, customerId: plan.customerId, propertyId: plan.propertyId!, status: "Approved", displayNumber: `${plan.company.estimatePrefix}-RP-${randomUUID().slice(0,8).toUpperCase()}`, pricingSubtotal: plan.defaultPrice ?? 0, pricingTotal: plan.defaultPrice ?? 0 } }); const created = await tx.job.create({ data: { companyId, estimateId: estimate.id, customerId: plan.customerId, propertyId: plan.propertyId!, status: "Scheduled", scheduledStart: occurrenceDate, scheduledEnd: end, customerNotes: plan.defaultJobNotes ?? "", crewNotes: plan.defaultInternalNotes ?? "", servicePlanId: plan.id, servicePlanOccurrence: occurrenceDate } }); const assignments = [...(plan.assignedCrewId ? [{ companyId, jobId: created.id, crewId: plan.assignedCrewId }] : []), ...plan.employeeAssignments.map((row) => ({ companyId, jobId: created.id, employeeId: row.employeeId }))]; if (assignments.length) await tx.jobAssignment.createMany({ data: assignments }); return created; }); const nextRunAt = calculateNextOccurrence(plan, occurrenceDate, plan.company.timezone); await prisma.servicePlan.update({ where: { id: plan.id }, data: { lastRunAt: occurrenceDate, nextRunAt, ...(nextRunAt ? {} : { status: "Completed" }) } }); return job; } catch (error) { const duplicate = await prisma.job.findFirst({ where: { companyId, servicePlanId, servicePlanOccurrence: occurrenceDate } }); if (duplicate) return duplicate; throw error; }
}
export async function generateDueServicePlanJobs(companyId: string, options: { through?: Date; limit?: number } = {}) { const through = options.through ?? new Date(); const plans = await prisma.servicePlan.findMany({ where: { companyId, status: "Active", autoCreateJobs: true, nextRunAt: { lte: through } }, take: options.limit ?? 100, orderBy: { nextRunAt: "asc" } }); const jobs = []; for (const plan of plans) { const occurrences = await previewServicePlanOccurrences(companyId, plan.id, through); for (const occurrence of occurrences) jobs.push(await generateJobFromServicePlan(companyId, plan.id, occurrence)); } return jobs; }
export async function generateServicePlanJobsThrough(companyId: string, servicePlanId: string, through: Date) { const occurrences = await previewServicePlanOccurrences(companyId, servicePlanId, through); const jobs = []; for (const occurrence of occurrences) jobs.push(await generateJobFromServicePlan(companyId, servicePlanId, occurrence)); return jobs; }
