"use client";
import { useState } from "react";
import { updateSmartPricingSettingsAction } from "@/app/actions/company/smartPricing";
import type { getSmartPricingSettings } from "@/lib/smartPricing/settings";
type Settings = Awaited<ReturnType<typeof getSmartPricingSettings>>;
export default function SmartPricingSettings({ initial }: { initial: Settings }) {
  const [value, setValue] = useState(initial); const [message, setMessage] = useState("");
  const toggle = (key: keyof Settings) => setValue((current) => ({ ...current, [key]: !current[key] }));
  async function save() { await updateSmartPricingSettingsAction({ enabled: value.smartPricingEnabled, minimumSampleSize: value.smartPricingMinimumSampleSize, confidenceThreshold: value.smartPricingConfidenceThreshold, useLaborHistory: value.smartPricingUseLaborHistory, useDisposalHistory: value.smartPricingUseDisposalHistory, useTravelHistory: value.smartPricingUseTravelHistory }); setMessage("Smart Pricing settings saved."); }
  return <section className="mx-auto mt-6 max-w-6xl rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Smart Pricing</h2><p className="mt-1 text-sm text-slate-600">Optional company-local recommendations. Manual pricing remains authoritative.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Check label="Enable Smart Pricing" checked={value.smartPricingEnabled} onChange={() => toggle("smartPricingEnabled")}/><label className="grid gap-1 text-sm font-medium">Minimum sample size<input className="rounded border p-2" type="number" min="1" value={value.smartPricingMinimumSampleSize} onChange={(e) => setValue((v) => ({ ...v, smartPricingMinimumSampleSize: Number(e.target.value) }))}/></label><label className="grid gap-1 text-sm font-medium">Confidence threshold<input className="rounded border p-2" type="number" min="0" max="100" value={value.smartPricingConfidenceThreshold} onChange={(e) => setValue((v) => ({ ...v, smartPricingConfidenceThreshold: Number(e.target.value) }))}/></label><Check label="Use labor history" checked={value.smartPricingUseLaborHistory} onChange={() => toggle("smartPricingUseLaborHistory")}/><Check label="Use disposal history" checked={value.smartPricingUseDisposalHistory} onChange={() => toggle("smartPricingUseDisposalHistory")}/><Check label="Use travel history (future)" checked={value.smartPricingUseTravelHistory} onChange={() => toggle("smartPricingUseTravelHistory")}/></div><button className="mt-5 rounded bg-blue-700 px-4 py-2 font-semibold text-white" onClick={() => void save()}>Save Smart Pricing</button>{message && <p className="mt-2 text-sm text-green-700">{message}</p>}</section>;
}
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: () => void }) { return <label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={checked} onChange={onChange}/>{label}</label>; }
