"use server";
import { createHash, randomBytes } from "node:crypto";
import { headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { requirePlatformAdmin } from "@/lib/admin/platformAuth";
import { prisma } from "@/lib/prisma";
import { validateRollout } from "@/lib/featureFlags/service";
import { createNotification } from "@/lib/notifications/service";
import type { Prisma, SubscriptionPlan } from "@/generated/prisma/client";
import { withDistributedLock } from "@/lib/distributed/locks";
import { checkRateLimit, ratePolicies } from "@/lib/security/rateLimit";

const auditData=(adminId:string,companyId:string|null,eventType:string,entityType="Company",entityId?:string,metadata?:Record<string,unknown>)=>({companyId,actingUserId:adminId,eventType,entityType,entityId:entityId??companyId,metadata:metadata as Prisma.InputJsonValue|undefined});

export async function setCompanyActiveAction(companyId:string,active:boolean){const admin=await requirePlatformAdmin();await prisma.$transaction(async tx=>{const company=await tx.company.findUnique({where:{id:companyId},select:{id:true}});if(!company)throw new Error("Company not found.");await tx.company.update({where:{id:companyId},data:{active}});if(!active){await tx.user.updateMany({where:{companyId},data:{sessionVersion:{increment:1}}});await tx.customerPortalSession.updateMany({where:{portalAccess:{companyId},revokedAt:null},data:{revokedAt:new Date()}})}await tx.auditEvent.create({data:auditData(admin.id,companyId,active?"admin.company_reactivated":"admin.company_suspended")})});revalidatePath("/system-admin")}

export async function forceLogoutCompanyAction(companyId:string){const admin=await requirePlatformAdmin();await prisma.$transaction(async tx=>{const company=await tx.company.findUnique({where:{id:companyId},select:{id:true}});if(!company)throw new Error("Company not found.");const result=await tx.user.updateMany({where:{companyId},data:{sessionVersion:{increment:1}}});await tx.customerPortalSession.updateMany({where:{portalAccess:{companyId},revokedAt:null},data:{revokedAt:new Date()}});await tx.userDevice.updateMany({where:{user:{companyId},revokedAt:null},data:{revokedAt:new Date()}});await tx.auditEvent.create({data:auditData(admin.id,companyId,"admin.force_logout","Company",companyId,{users:result.count})})})}

export async function resetOwnerPasswordAction(companyId:string){const admin=await requirePlatformAdmin();const raw=randomBytes(32).toString("base64url");const tokenHash=createHash("sha256").update(raw).digest("hex");const expiresAt=new Date(Date.now()+30*60_000);const owner=await prisma.$transaction(async tx=>{const user=await tx.user.findFirst({where:{companyId,active:true,memberships:{some:{companyId,role:"Owner",status:"Active"}}},select:{id:true,email:true}});if(!user)throw new Error("Company owner not found.");await tx.adminPasswordResetToken.updateMany({where:{userId:user.id,usedAt:null},data:{usedAt:new Date()}});await tx.adminPasswordResetToken.create({data:{userId:user.id,tokenHash,expiresAt,createdByAdminId:admin.id}});await tx.user.update({where:{id:user.id},data:{sessionVersion:{increment:1}}});await tx.auditEvent.create({data:auditData(admin.id,companyId,"admin.owner_password_reset_requested","User",user.id)});return user});const base=process.env.NEXT_PUBLIC_APP_URL;if(!base)throw new Error("NEXT_PUBLIC_APP_URL is required to send password reset links.");await createNotification({companyId,userId:owner.id,channel:"email",to:owner.email,title:"Reset your JunkQuote Pro password",body:`A platform administrator requested a password reset. This single-use link expires in 30 minutes: ${base}/reset-password?token=${encodeURIComponent(raw)}`});}

export async function beginImpersonationAction(companyId:string,reason:string){const admin=await requirePlatformAdmin();const normalized=reason.trim();if(normalized.length<10)throw new Error("A support reason of at least 10 characters is required.");const h=await headers();const ip=h.get("x-forwarded-for")?.split(",")[0]?.trim();const ipHash=ip?createHash("sha256").update(ip).digest("hex"):null;const userAgent=h.get("user-agent")?.slice(0,500)??null;return prisma.$transaction(async tx=>{const nested=await tx.adminImpersonation.findFirst({where:{adminUserId:admin.id,endedAt:null,expiresAt:{gt:new Date()}}});if(nested)throw new Error("End the active support session before starting another.");const target=await tx.user.findFirst({where:{companyId,active:true,memberships:{some:{companyId,role:"Owner",status:"Active"}}},select:{id:true}});if(!target)throw new Error("Target company owner not found.");const row=await tx.adminImpersonation.create({data:{companyId,adminUserId:admin.id,targetUserId:target.id,reason:normalized,ipHash,userAgent,expiresAt:new Date(Date.now()+30*60_000)}});await tx.auditEvent.create({data:auditData(admin.id,companyId,"admin.impersonation_started","AdminImpersonation",row.id,{reason:normalized,targetUserId:target.id,expiresAt:row.expiresAt.toISOString()})});return row})}

export async function endImpersonationAction(impersonationId:string){const admin=await requirePlatformAdmin();await prisma.$transaction(async tx=>{const row=await tx.adminImpersonation.findFirst({where:{id:impersonationId,adminUserId:admin.id,endedAt:null}});if(!row)throw new Error("Active support session not found.");await tx.adminImpersonation.update({where:{id:row.id},data:{endedAt:new Date()}});await tx.auditEvent.create({data:auditData(admin.id,row.companyId,"admin.impersonation_ended","AdminImpersonation",row.id)})});revalidatePath("/system-admin")}

export async function retrySystemJobAction(jobId:string){const admin=await requirePlatformAdmin();if(!(await checkRateLimit(`system-admin:retry:${admin.id}`,ratePolicies.systemAdmin)).allowed)throw new Error("Too many administrative requests. Try again later.");await withDistributedLock("admin-job-retry",jobId,60_000,()=>prisma.$transaction(async tx=>{const job=await tx.backgroundJob.findFirst({where:{id:jobId,status:{in:["Failed","Cancelled"]}}});if(!job)throw new Error("This job is already pending/running or is not retryable.");const claimed=await tx.backgroundJob.updateMany({where:{id:job.id,status:job.status},data:{status:"Pending",attempts:0,availableAt:new Date(),startedAt:null,completedAt:null,lastError:null}});if(claimed.count!==1)throw new Error("The job was already retried by another administrator.");await tx.auditEvent.create({data:auditData(admin.id,job.companyId,"admin.background_job_retried","BackgroundJob",job.id,{previousStatus:job.status})})}));revalidatePath("/system-admin")}

export async function upsertFeatureFlagAction(input:{key:string;enabled:boolean;description?:string;companyId?:string|null;plan?:SubscriptionPlan|null;environment?:string|null;rolloutPercent:number}){const admin=await requirePlatformAdmin();validateRollout(input.rolloutPercent);const key=input.key.trim();if(!key)throw new Error("Feature flag key is required.");await prisma.$transaction(async tx=>{if(input.companyId&&!await tx.company.findUnique({where:{id:input.companyId},select:{id:true}}))throw new Error("Target company not found.");const row=await tx.featureFlag.create({data:{...input,key,description:input.description?.trim()??""}});await tx.auditEvent.create({data:auditData(admin.id,input.companyId??null,"admin.feature_flag_created","FeatureFlag",row.id,{key,enabled:row.enabled,rolloutPercent:row.rolloutPercent,plan:row.plan,environment:row.environment})})});revalidatePath("/system-admin")}
